#!/usr/bin/env python3
"""Render the contributor link sheet from api/_contributor-roster.js.

WHY THIS EXISTS. The sheet was hand-maintained. When V-HC-01 was withdrawn from
the roster on 2026-08-13 the sheet kept his row, so the file the owner would
have sent on the confirmation deadline contained a link that returns 404. One
contributor would have received a dead link on the last day they could respond.

That is the same defect as a hand-written count: a second copy of a fact with
nothing forcing it to agree with the first. It is now generated, so a person
removed from the roster disappears from the sheet in the same commit.

Run:
    python3 research/build_contributor_links.py

Exit code: 0 on success, 1 if the roster could not be read.

PRIVATE. The output lists unguessable per-person keys and must never be
deployed or published. research/ is excluded from the deploy for this reason.
"""
import io
import json
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
ROSTER_JS = os.path.join(ROOT, "api", "_contributor-roster.js")
CONTRIB_JS = os.path.join(ROOT, "api", "contributor.js")
BASE = "https://www.jrsstandard.com/contributor.html?k="

# Group label per roster `kind`. Order is the order they appear in the sheet.
GROUPS = [
    ("panel", "International detection panel"),
    ("author", "Co-authors"),
    ("facil", "Domain pilot facilitators"),
]


def read_roster():
    """Read the roster through node so this file never re-transcribes it."""
    src = ("import {ROSTER} from '%s';"
           "console.log(JSON.stringify(Object.entries(ROSTER).map("
           "([k,p])=>({key:k, code:p.code, kind:p.kind, name:p.name, title:p.title, note:p.note||''}))));"
           % ROSTER_JS)
    r = subprocess.run(["node", "--input-type=module", "-e", src],
                       capture_output=True, text=True)
    if r.returncode != 0:
        sys.stderr.write("Could not read the roster:\n" + r.stderr + "\n")
        sys.exit(1)
    return json.loads(r.stdout)


def fallback_date():
    """The deadline, read from api/contributor.js rather than restated here."""
    s = io.open(CONTRIB_JS, encoding="utf-8").read()
    m = re.search(r"const FALLBACK_DATE = '([^']+)'", s)
    return m.group(1) if m else "[NOT FOUND IN api/contributor.js]"


def main():
    people = read_roster()
    date = fallback_date()

    L = []
    A = L.append
    A("# Contributor confirmation links")
    A("")
    A("**PRIVATE. Do not publish this file.** It lists one unguessable key per person, "
      "and `research/` is excluded from the deploy for exactly this reason.")
    A("")
    A("**Generated by `research/build_contributor_links.py` from `api/_contributor-roster.js`.** "
      "Do not edit it by hand. It was hand-maintained until 2026-08-13, and when a "
      "contributor was withdrawn from the roster the sheet kept their row, leaving a link "
      "that returns 404 in the file the owner would have sent.")
    A("")
    A("Each link opens a page that captures how the person wants their name and title "
      "printed, a contact address, and three forced-choice permissions, then releases the "
      "initiatives, the Investigator Field Guide, the training, the private diagnostic and "
      "the results summary.")
    A("")
    A("**THE RESULTS SUMMARY IS GATED AND THE GATE IS STRUCTURAL, NOT COSMETIC.** "
      "`api/contributor.js` returns the summary only from the POST branch, after all "
      "three forced choices validate. A GET on the same link returns the person and "
      "nothing else, so opening the URL, sharing it, or fetching it does not disclose "
      "the findings. Verified by position in the source: the GET branch contains no "
      "reference to results at all.")
    A("")
    A("**Released 2026-08-15.** Both studies are closed and the analysis is locked, so "
      "`RESULTS_RELEASED` is now true and a contributor who submits sees the full "
      "finding, including the comparison result that did not meet its pre-registered "
      "bar. Everyone gets the same summary on the same terms.")
    A("")
    A("**Fallback date, read from `api/contributor.js`: %s.** If a person does not respond "
      "by then the paper uses what is on file. Where there is no naming election on file "
      "the fallback is anonymous: **a name is never printed on silence alone.**" % date)
    A("")
    A("**Anonymity does not require identifying yourself.** Since 2026-08-13 a contributor "
      "electing anonymity confirms with the three permission choices alone; name, title and "
      "organization are requested only from someone who has asked to be named.")
    A("")
    A("---")
    A("")

    total = 0
    seen_kinds = set()
    for kind, label in GROUPS:
        rows = [p for p in people if p["kind"] == kind]
        seen_kinds.add(kind)
        if not rows:
            continue
        A("## %s" % label)
        A("")
        A("| Person | Code | Role note | Link |")
        A("|---|---|---|---|")
        for p in sorted(rows, key=lambda x: x["code"]):
            A("| %s | `%s` | %s | %s%s |"
              % (p["name"], p["code"], (p["note"] or "").replace("|", "/") or "",
                 BASE, p["key"]))
            total += 1
        A("")

    # A kind the script does not know about must be listed, not dropped. A
    # silently omitted contributor is how this file went wrong in the first place.
    unknown = [p for p in people if p["kind"] not in seen_kinds]
    if unknown:
        A("## Ungrouped")
        A("")
        A("**These carry a `kind` this script does not have a heading for. Listed rather "
          "than dropped.**")
        A("")
        A("| Person | Code | Kind | Link |")
        A("|---|---|---|---|")
        for p in sorted(unknown, key=lambda x: x["code"]):
            A("| %s | `%s` | %s | %s%s |" % (p["name"], p["code"], p["kind"], BASE, p["key"]))
            total += 1
        A("")

    A("---")
    A("")
    A("**%d people on the roster, %d links listed.** These two numbers are the same by "
      "construction: every roster entry is rendered and nothing else is." % (len(people), total))
    A("")
    A("**Comparison-arm reviewers (RR-### codes) are on this sheet since 2026-08-14**, on the "
      "owner's instruction. The line here used to say they were absent and must not be added, "
      "which stopped being true the day they were added.")

    out = os.path.join(HERE, "Contributor_Links.md")
    io.open(out, "w", encoding="utf-8").write("\n".join(L) + "\n")
    print("wrote %s" % out)
    print("  roster entries: %d | links rendered: %d | fallback date: %s"
          % (len(people), total, date))
    return 0


if __name__ == "__main__":
    sys.exit(main())
