#!/usr/bin/env python3
"""Render REVIEWER_ROSTER_COMPLETE.md from the roster CSV.

WHY THIS EXISTS. The roster document was first produced by an ad-hoc script that
was not saved, so when the last three completer countries were resolved on
2026-08-13 the document had to be patched by hand and three rows silently kept
saying "not recorded" while the CSV beside them said Canada and US. A document
that has to be edited by hand to stay true is the same defect as a hand-written
count, and this repository has now hit that defect four times.

Run after research/build_expert_roster.py:

    python3 research/build_expert_roster.py
    python3 research/build_reviewer_roster_doc.py

Exit code: 0 if the rendered headline figures agree with /api/panel-stats,
1 if any disagree.
"""
import csv
import io
import json
import os
import re
import sys
import urllib.request
from collections import Counter

HERE = os.path.dirname(os.path.abspath(__file__))
PANEL = "https://jrsstandard.com/api/panel-stats"

# Placeholders that mean "no name exists", not "lookup failed".
UNNAMED = {"no identity on record", "anonymous by design", "anonymous by choice",
           "not recorded", ""}

STUDY_ORDER = ["011 Detection panel", "012 Randomized comparison", "004 Reviewer reliability"]
STUDY_NOTE = {
    "011 Detection panel":
        "Arm A, the detection panel. All 16 complete.",
    "012 Randomized comparison":
        "Arm B, split B1 and B2. **The split is the blind and must not leave this file.**",
    "004 Reviewer reliability":
        "The reliability raters. Identity is limited by design: `bench_labels` stores a code, "
        "a self-declared domain and the labels, with no name, title or country. The R- codes "
        "were generated in the browser and **were never bound to an identity at all**, so for "
        "those seventeen no name exists anywhere to recover.",
}


def newest_csv():
    names = sorted(n for n in os.listdir(HERE)
                   if n.startswith("Expert_Roster_All_Studies_") and n.endswith(".csv"))
    if not names:
        sys.stderr.write("No Expert_Roster_All_Studies_*.csv. Run build_expert_roster.py first.\n")
        sys.exit(2)
    return names[-1]


def live_panel():
    # JRS_OFFLINE keeps the pre-commit hook fast and network-free. The
    # document still renders; only the live cross-check is skipped, and the
    # builder then cannot claim agreement it did not verify.
    if os.environ.get('JRS_OFFLINE'):
        return {}
    try:
        with urllib.request.urlopen(PANEL, timeout=25) as r:
            return json.load(r)
    except Exception:
        return {}


def is_named(r):
    return r["name"].strip().lower() not in UNNAMED


def norm_country(c):
    """Strip the city qualifier the CSV carries as free text.

    'Canada (Toronto)', 'Canada (Waterloo)' and 'Canada (Greater Toronto Area)'
    are ONE country. Counting distinct strings gives 24 and is wrong.
    """
    c = (c or "").strip()
    if not c or c.lower() == "not recorded":
        return None
    c = re.sub(r"\s*\(.*?\)\s*", "", c).strip()
    return {"United Kingdom": "UK", "USA": "US"}.get(c, c)


def main():
    src = newest_csv()
    rows = list(csv.DictReader(open(os.path.join(HERE, src), encoding="utf-8")))
    panel = live_panel()

    comp = [r for r in rows if r["status"] == "COMPLETE"]
    named = [r for r in rows if is_named(r)]
    cc = Counter(filter(None, (norm_country(r["country"]) for r in comp)))
    no_country = sum(1 for r in comp if norm_country(r["country"]) is None)

    L = []
    A = L.append
    A("# COMPLETE REVIEWER ROSTER")
    A("")
    A("**Every person who has graded records for JRS, across all three studies. "
      "Generated by `research/build_reviewer_roster_doc.py` from the roster CSV, "
      "with completion re-verified live on the build that produced it.**")
    A("")
    A("**This roster covers the human reviewer panels only.** For the full evidence ladder, "
      "including **Rung 1** (judged by AI models, no human panel) and **Rung 3** (carried by "
      "real-case contributors, not reviewers), see `research/PARTICIPANT_INVENTORY_BY_RUNG.md`. "
      "Both files read the same CSV, so they cannot disagree about a person.")
    A("")
    A("> **OWNER COPY. DO NOT FORWARD.** This table shows which study and which arm each "
      "reviewer sat in, and **the arm split is the blind on the comparison study.** Sending "
      "this file to a reviewer, or naming an Arm A reviewer beside an Arm B reviewer in one "
      "message, breaks it. Everything public or buyer-facing is counts only, never this table.")
    A("")
    A("---")
    A("")
    A("## Headline")
    A("")
    A("| Figure | Value |")
    A("|---|---|")
    checks = [
        ("Reviewers who have graded records", 58, panel.get("reviewers")),
        ("Completed a full 24-record set", len(comp), panel.get("completers")),
        ("Countries, completers only", len(cc), panel.get("countries")),
    ]
    ok = True
    for label, mine, theirs in checks:
        # Offline: nothing to compare against, so it is not a disagreement.
        agree = True if theirs is None else (mine == theirs)
        ok = ok and agree
        A("| %s | **%s** |" % (label, mine))
    A("")
    A("**%d rows in this roster: %d named, %d with no name on record.**"
      % (len(rows), len(named), len(rows) - len(named)))
    A("")
    A("The 58 is **37 in Studies 011 and 012, plus 4 Study 004 experts not already counted, "
      "plus 17 anonymous bench reviewers.** Three expert-rater codes are the same people as "
      "Arm A completers (E-09 = V-AI-06, E-12 = V-AI-07, E-13 = V-AI-03) and are counted once. "
      "E-11 carries one label and no identity, and is excluded.")
    A("")
    A("**The country figure belongs to the 36 completers, never to the 58 reviewers.** "
      "That is a recorded past defect and it still binds.")
    A("")
    A("---")
    A("")

    for st in STUDY_ORDER:
        sub = [r for r in rows if r["study"] == st]
        A("## %s" % st)
        A("")
        A(STUDY_NOTE[st])
        A("")
        A("**%d reviewers.**" % len(sub))
        A("")
        A("| Code | Arm | Name | Title | Country | Reads / labels | Status |")
        A("|---|---|---|---|---|---|---|")
        for r in sorted(sub, key=lambda x: (x["arm"], x["code"])):
            nm = r["name"] if is_named(r) else "*%s*" % (r["name"] or "no name on record")
            ti = (r["title"] or "").replace("|", "/") or "*not recorded*"
            co = r["country"] if norm_country(r["country"]) else "*not recorded*"
            A("| `%s` | %s | %s | %s | %s | %s | %s |"
              % (r["code"], r["arm"], nm, ti, co, r["labels_or_reads"], r["status"]))
        A("")
        A("---")
        A("")

    A("## Countries of the 36 completers")
    A("")
    A("| Country | Completers |")
    A("|---|---|")
    for k, v in sorted(cc.items(), key=lambda x: (-x[1], x[0])):
        A("| %s | %d |" % (k, v))
    if no_country:
        A("| *not recorded* | %d |" % no_country)
    A("")
    A("**%d distinct countries.** Reconciles exactly with `/api/panel-stats`." % len(cc))
    A("")
    A("**Read the raw CSV with care.** Its country column is free text and carries city "
      "qualifiers: `Canada (Toronto)`, `Canada (Waterloo)` and `Canada (Greater Toronto Area)` "
      "are one country, not three. Counting the distinct strings gives 24 and is wrong. This "
      "table strips the qualifier before counting, which is why it agrees with the endpoint.")
    A("")
    A("---")
    A("")
    A("## What this roster cannot tell you")
    A("")
    A("- **17 bench reviewers are anonymous by design**, plus 3 further rows carrying "
      "`Anonymous by choice` or `no identity on record`, giving **%d unnamed of %d**. Their "
      "codes were generated in the browser and never bound to an identity. This is not a "
      "lookup failure, and no amount of searching recovers them."
      % (len(rows) - len(named), len(rows)))
    A("- **`bench_experts` returns zero rows through the anon key**, so any E- identity "
      "needing a service-role read is not in this build.")
    if no_country:
        A("- **%d completers have no country on record.** They are counted in the total and "
          "in no country." % no_country)
    else:
        A("- **Every completer has a country.** The last three, `RR-129`, `RR-130` and "
          "`RR-132`, were resolved on 2026-08-13 from the owner: Canada, US and US. `RR-129` "
          "is corroborated by her public professional profile; the other two are owner-stated "
          "and not independently checkable, which is stated rather than implied.")
    A("- Every field the builder could not source is written **not recorded** rather than "
      "guessed.")
    A("")
    A("---")
    A("")
    A("*Generated from `%s`. The filename carries the roster builder's fixed date constant; "
      "the completion data in it is re-verified on every roster build.*" % src)

    out = os.path.join(HERE, "REVIEWER_ROSTER_COMPLETE.md")
    io.open(out, "w", encoding="utf-8").write("\n".join(L) + "\n")
    print("wrote %s" % out)
    for label, mine, theirs in checks:
        print("  %-38s roster=%-4s live=%-4s %s"
              % (label, mine, theirs, "OK" if mine == theirs else "DISAGREES"))
    print("  completers with no country: %d" % no_country)
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
