#!/usr/bin/env python3
"""Build the downloadable reviewer roster across ALL THREE studies.

Emits, next to this script:
  Expert_Roster_All_Studies_<date>.csv   one row per reviewer, all three studies
  Study004_Raters_<date>.csv             the reliability raters on their own

The Study 011 / 012 rows are transcribed from the study record (MASTER_TRACKER
sections 12 and 12B, the recruit notes, api/contributor.js, and the two
certificate registries) and completion is re-verified live on every run against
pilot_progress and armb_progress. The Study 004 rows are pulled live from
bench_labels, which is the only place that study's participation is recorded.

IDENTITY LIMIT FOR STUDY 004, stated rather than papered over: bench_labels
stores a labeler_code, a self-declared role, and the labels. It stores no name,
no title, and no country. bench_experts, which would hold the E- code identities,
returns zero rows through the anon key, so those names are not reachable without
a service-role read. The R- codes are browser-generated by bench-review.html and
were never attached to an identity at all, so for those sixteen no name exists
anywhere to recover. Every field this script cannot source is written as
"not recorded" rather than guessed.

  python3 research/build_expert_roster.py
"""
import csv
import json
import os
import urllib.request
from collections import OrderedDict

SB = "https://pjzxkeviouofdseagvpf.supabase.co"
KEY = "sb_publishable_mkdtg6-NgJ44_JVr9vZf6Q_30BVgY4e"  # anon key; public by design
HERE = os.path.dirname(os.path.abspath(__file__))
DATE = "2026-08-06"
NEEDED = 24

FIELDS = ["study", "arm", "code", "name", "title", "country", "labels_or_reads", "status"]

# --- Study 011, detection panel (Arm A). Transcribed from the study record. ---
ARM_A = [
    ("V-AI-01", "Jake McDonough", "AI governance, self-accountable AI runtimes; SAEONYX Global Holdings", "US"),
    ("V-AI-03", "Frank Schouten", "AI Governance and Assurance; risk and accountability; AEGF", "Australia"),
    ("V-AI-06", "Dr Nitin Deshpande", "Chief Human Resources Officer; 38+ years HR and industrial relations", "India"),
    ("V-AI-07", "Saurabh Nanda", "General Manager, APAC business leader (P&L); Align Technology", "India"),
    ("V-AI-08", "Gabriela Cortez", "Civil-rights records and bilingual intake; Maryland Commission on Civil Rights", "US"),
    ("V-AI-10", "Lawal Olabanji", "Operations and records management; ALTV Engineering", "Nigeria"),
    ("V-AI-11", "Andrey Ekhmenin", "Founder, EAS; governance diagnostics and post-execution review", "Poland / EU"),
    ("V-AI-12", "Kyle McMullan", "Chief Audit Executive; internal audit and financial crimes", "UK / Ireland"),
    ("V-AI-16", "Dr Gabriela Bar", "Attorney, PhD; AI ethics advisor (EU); Gabriela Bar Law & AI", "Poland / EU"),
    ("V-AI-20", "Hekim Colpan", "AI Governance and Compliance Manager; ISO/IEC 42001 auditor; EU AI Act, GDPR, DORA", "Germany"),
    ("V-AI-23", "Niloofar Kandi", "AI Governance and Strategy Specialist; ISO/IEC 42001 Lead Implementer; PhD Researcher, University of Wollongong", "Australia"),
    ("V-AI-24", "SungSoo In", "AI Governance and Responsible AI; author, Athena Governance Architecture", "South Korea"),
    ("V-AI-27", "Sidharth Borah", "Advocate, High Court of Delhi (13+ years); Partner, Gurinder & Partners", "India"),
    ("V-AI-28", "Nigel Hee", "AI Ethics, Safety and Governance; Co-founder, OpenNexus; researcher, University of Glasgow", "Singapore"),
    ("V-AI-29", "Marguerite Maroudis, PhD", "AI and Law Expert; DPO and AI Governance Consultant; PhD Private Law; Founder, TechLegalExperts", "UAE (Dubai)"),
    ("V-AI-30", "Andres Lage Freire", "AI Governance Lead and Responsible AI Architect; EU AI Act, ISO 42001", "Spain (Madrid)"),
]

# --- Study 012, randomized comparison (Arm B). Arm assigned by deterministic hash. ---
ARM_B = [
    ("RR-101", "Boris Khazin", "AI Governance, Digital Risk and GRC leader; ClearView MRI; ex-EPAM Global Head of DRM/GRC", "US (North Carolina)", "B2"),
    ("RR-104", "Donavine Smith, MBA", "Chief Strategy and Transformation Officer; frontier AI strategy and governance; NED, Rape Crisis Cape Town Trust", "South Africa (Pretoria)", "B1"),
    ("RR-106", "Nicholas Evans", "AI Governance and Runtime Auditor; adversarial and non-adversarial testing; ex-USMC", "US", "B1"),
    ("RR-107", "Tuneer Mondal", "AI, HealthTech and Governance; Consultant, Operations and AI Solutions; Arcadia Impact; University of Cambridge", "Canada (Waterloo)", "B2"),
    ("RR-109", "Mostafa Mahmoudi", "AI Governance Researcher; Founder and Director, Iran Tech Diplomacy Institute; PhD candidate, University of Tehran", "Iran (Tehran)", "B2"),
    ("RR-110", "Jean-Luc Adade", "Regional IT Leader, West, Central and North Africa; IT governance and digital transformation", "West Africa", "B2"),
    ("RR-114", "MacKenzie McCowan", "AI Governance Specialist, Atomi; PhD candidate, University of Sydney; Sessional Lecturer, Avondale University", "Australia (Sydney)", "B2"),
    ("RR-116", "Dr. Eric J. W. Orlowski", "AI Governance Specialist, Ethnographer, Tech Policy Researcher; Research Fellow, NUS AI Institute; PhD, UCL", "Singapore", "B2"),
    ("RR-121", "Dr Sharon Licqurish, PhD", "CEO, Chief Scientist and AI Governance Architect, AIIP", "Australia (Melbourne)", "B2"),
    ("RR-123", "Greg Searle", "AI Governance and Model Behaviour Researcher; Master's candidate", "Australia (Brisbane)", "B2"),
    ("RR-124", "Adesh Sharma", "Data and AI Governance Leader, Digital Frontier Partners; IAPP AIGP", "Australia (Melbourne)", "B1"),
    ("RR-125", "Muhammad Dauda", "Programme leadership, sustainability and governance; UN SDSN Youth Nigeria; Miva Open University; PgMP", "Nigeria", "B2"),
    ("RR-126", "Joseph Mungai", "Public-Interest Technology and AI Ethics/Governance Professional; Maasai Mara University", "Kenya (Kitale)", "B1"),
    ("RR-128", "Sagarika Banerjee", "AI Governance and Software QA Leader; ISO/IEC 42001, NIST AI RMF", "Canada (Toronto)", "B1"),
    ("RR-130", "Anonymous by choice", "JRS-naive expert professional", "not recorded", "B2"),
    ("RR-132", "Anonymous by choice", "JRS-naive expert professional", "not recorded", "B2"),
]

# Study 004 expert-rater identities, read from bench_experts with the
# service-role connection on 2026-08-06. Country is taken from the affiliation
# field where the affiliation names a place, and left "not recorded" where it
# does not. Nothing is inferred from a person's name.
#
# THREE OF THESE ARE ALSO ARM A COMPLETERS, so they are the same human being
# holding two study codes: E-09 is V-AI-06, E-12 is V-AI-07, E-13 is V-AI-03.
# E-14 is V-AI-05, who registered for Arm A but never started, so he is a
# distinct person from the 32. This is what the "may overlap" caveat in
# count_participants.py was guarding against, now resolved with actual data.
S004_KNOWN = {
    "E-03": ("Andrzej Skulski", "Founder, Dom Ciszy - Resonance Lab; AI Governance and Decision Systems", "not recorded"),
    "E-08": ("Stacy Young", "Deputy Records Access Officer, NYC Dept. of Housing Preservation and Development; records governance and FOIL administration; 22 years", "US"),
    "E-09": ("Dr Nitin Deshpande", "Chief Human Resources Officer, Cooper Corporation Pvt. Ltd.; 38+ years HR and industrial relations", "India"),
    "E-10": ("Rahul Potdar", "Independent Director (IICA Certified); Corporate Governance, Risk Management and ESG Strategy; Board Adviser; Leontra Technologies; IIM Raipur", "India"),
    "E-11": (None, None, None),
    "E-12": ("Saurabh Nanda", "General Manager, APAC Business Leader, Align Technology; 22+ years P&L leadership", "India"),
    "E-13": ("Frank Schouten", "AI Governance and Assurance; Interim Steering Committee, AI Execution Governance Forum; CAMA-certified ISO 55001 assessor", "Australia (Perth)"),
    "E-14": ("Alankar Yaduvanshi", "Data Privacy Professional (CIPP-E), WNS; 8+ years data privacy and corporate compliance", "India"),
}

# Same person, two study codes. Used to report distinct humans honestly.
CROSS_STUDY_SAME_PERSON = {"E-09": "V-AI-06", "E-12": "V-AI-07", "E-13": "V-AI-03"}


def q(path):
    req = urllib.request.Request(SB + path, headers={"apikey": KEY, "Authorization": "Bearer " + KEY})
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.loads(r.read().decode())


def study_004_rows():
    """One row per reliability rater, live from bench_labels."""
    labels = q("/rest/v1/bench_labels?select=labeler_code,role,created_at,record_id&limit=20000")
    agg = OrderedDict()
    for r in sorted(labels, key=lambda x: x["created_at"]):
        a = agg.setdefault(r["labeler_code"], {"n": 0, "roles": set(), "recs": set(), "first": r["created_at"]})
        a["n"] += 1
        if r.get("role"):
            a["roles"].add(r["role"])
        a["recs"].add(r["record_id"])

    rows = []
    for code, a in agg.items():
        is_expert = str(code).startswith("E-")
        name, title, country = S004_KNOWN.get(code, (None, None, None))
        role = "; ".join(sorted(a["roles"])) or "not recorded"
        dup = CROSS_STUDY_SAME_PERSON.get(code)
        status = "%d labels on %d records, first %s" % (a["n"], len(a["recs"]), a["first"][:10])
        if dup:
            status += "; same person as %s in Study 011" % dup
        rows.append({
            "study": "004 Reviewer reliability",
            "arm": "expert rater" if is_expert else "bench reviewer",
            "code": code,
            "name": name or ("no identity on record" if is_expert else "anonymous by design"),
            "title": title or ("self-declared domain: " + role),
            "country": country or "not recorded",
            "labels_or_reads": a["n"],
            "status": status,
        })
    return rows


def main():
    a_live = {r["code"]: (r.get("total_reads") or 0)
              for r in q("/rest/v1/pilot_progress?select=code,total_reads&limit=5000")}
    b_live = {r["code"]: (r.get("reads") or 0)
              for r in q("/rest/v1/armb_progress?select=code,reads&limit=5000")}

    rows = []
    for code, name, title, country in ARM_A:
        n = a_live.get(code, 0)
        rows.append({"study": "011 Detection panel", "arm": "A", "code": code, "name": name,
                     "title": title, "country": country, "labels_or_reads": n,
                     "status": "COMPLETE" if n >= NEEDED else "NOT COMPLETE (%d)" % n})
    for code, name, title, country, arm in ARM_B:
        n = b_live.get(code, 0)
        rows.append({"study": "012 Randomized comparison", "arm": arm, "code": code, "name": name,
                     "title": title, "country": country, "labels_or_reads": n,
                     "status": "COMPLETE" if n >= NEEDED else "NOT COMPLETE (%d)" % n})

    s004 = study_004_rows()
    rows += s004

    full = os.path.join(HERE, "Expert_Roster_All_Studies_%s.csv" % DATE)
    with open(full, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=FIELDS)
        w.writeheader()
        w.writerows(rows)

    only4 = os.path.join(HERE, "Study004_Raters_%s.csv" % DATE)
    with open(only4, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=FIELDS)
        w.writeheader()
        w.writerows(s004)

    incomplete = [r for r in rows if r["status"].startswith("NOT COMPLETE")]
    print("wrote %s (%d rows)" % (full, len(rows)))
    print("wrote %s (%d rows)" % (only4, len(s004)))
    print("Study 011 + 012 completers: %d | Study 004 raters: %d | total rows: %d"
          % (len(ARM_A) + len(ARM_B), len(s004), len(rows)))
    unnamed = ("no identity on record", "anonymous by design", "Anonymous by choice")
    print("named rows: %d | unnamed rows: %d"
          % (sum(1 for r in rows if r["name"] not in unnamed),
             sum(1 for r in rows if r["name"] in unnamed)))
    dup = len(CROSS_STUDY_SAME_PERSON)
    bench = sum(1 for r in s004 if r["arm"] == "bench reviewer")
    new_experts = sum(1 for r in s004 if r["arm"] == "expert rater"
                      and r["code"] not in CROSS_STUDY_SAME_PERSON
                      and r["name"] != "no identity on record")
    print("DISTINCT HUMANS: %d = 32 completers + %d Study 004 experts who are not "
          "already completers + %d anonymous bench reviewers"
          % (32 + new_experts + bench, new_experts, bench))
    print("  %d expert rater codes are the same people as Arm A completers: %s"
          % (dup, ", ".join("%s=%s" % (k, v) for k, v in CROSS_STUDY_SAME_PERSON.items())))
    print("  E-11 carries 1 label and no identity on record; excluded from the count.")
    if incomplete:
        print("WARNING, live completion check disagrees with the transcribed roster:")
        for r in incomplete:
            print("  ", r["code"], r["status"])


if __name__ == "__main__":
    main()
