#!/usr/bin/env python3
"""Programme-wide participant count across EVERY study (reproducible source of
truth for the reviewer figures used on the site and in outreach copy).

WHY THIS EXISTS: the public copy carried "32", which is the number of people who
completed a full 24-record set across Study 011 (Arm A) and Study 012 (Arm B).
That silently excluded Study 004, the reliability study, whose raters graded a
shared record set through a different instrument with different codes. This
script counts every study and prints the figures actually safe to publish.

NO SERVICE KEY NEEDED: reads the same anon-readable aggregate views the public
status page uses. Raw read tables stay RLS-locked.

  python3 research/count_participants.py

IDENTITY RESOLVED 2026-08-06: the E- rater identities were read from
bench_experts with the service-role connection, so the old "may overlap" floor is
superseded. Exactly three expert-rater codes belong to people already counted as
Arm A completers (E-09 = V-AI-06 Dr Nitin Deshpande, E-12 = V-AI-07 Saurabh
Nanda, E-13 = V-AI-03 Frank Schouten). Four expert raters are people the other
two studies never touched (E-03 Andrzej Skulski, E-08 Stacy Young, E-10 Rahul
Potdar, E-14 Alankar Yaduvanshi, who holds V-AI-05 but never started Arm A).
E-11 carries one label and no identity row, so it is excluded from the count
rather than assumed to be a new person. The R- codes are browser-generated by
bench-review.html, were never attached to an identity, and are a separately
recruited pool, so they are counted.

DISTINCT PEOPLE = 32 completers + 4 new expert raters + 16 bench reviewers = 52.
Named roster: research/Expert_Roster_All_Studies_2026-08-06.md.
"""
import json
import urllib.request

SB = "https://pjzxkeviouofdseagvpf.supabase.co"
KEY = "sb_publishable_mkdtg6-NgJ44_JVr9vZf6Q_30BVgY4e"  # anon key; public by design
NEEDED = 24


def q(path):
    req = urllib.request.Request(SB + path, headers={"apikey": KEY, "Authorization": "Bearer " + KEY})
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.loads(r.read().decode())


def main():
    a = q("/rest/v1/pilot_progress?select=code,total_reads&limit=5000")
    b = q("/rest/v1/armb_progress?select=code,arm_code,reads&limit=5000")
    lab = q("/rest/v1/bench_labels?select=labeler_code,record_id&limit=20000")

    a_reg = {r["code"] for r in a}
    a_done = {r["code"] for r in a if (r["total_reads"] or 0) >= NEEDED}
    b_reg = {r["code"] for r in b}
    b_done = {r["code"] for r in b if (r["reads"] or 0) >= NEEDED}

    raters = {r["labeler_code"] for r in lab}
    experts = {c for c in raters if str(c).startswith("E-")}
    bench = raters - experts

    print("STUDY 011  Detection panel (Arm A, V-AI-##)")
    print("  registered %d | completed a full %d-record set %d" % (len(a_reg), NEEDED, len(a_done)))
    print("STUDY 012  Randomized comparison (Arm B, RR-###)")
    print("  registered %d | completed a full %d-record set %d" % (len(b_reg), NEEDED, len(b_done)))
    print("STUDY 004  Reviewer reliability (shared record set)")
    print("  raters %d (%d E- experts, %d bench reviewers) | labels %d"
          % (len(raters), len(experts), len(bench), len(lab)))

    # Resolved from bench_experts on 2026-08-06. Three rater codes belong to
    # people already counted as Arm A completers; one code has no identity row.
    OVERLAP = {"E-09", "E-12", "E-13"}
    UNRESOLVED = {"E-11"}
    new_experts = experts - OVERLAP - UNRESOLVED
    distinct = len(a_done) + len(b_done) + len(new_experts) + len(bench)

    print()
    print("DISTINCT PEOPLE ACROSS ALL THREE STUDIES: %d" % distinct)
    print("  %d completers (Arm A %d + Arm B %d)" % (len(a_done) + len(b_done), len(a_done), len(b_done)))
    print("  + %d expert raters the other studies never touched: %s"
          % (len(new_experts), ", ".join(sorted(new_experts))))
    print("  + %d anonymous bench reviewers" % len(bench))
    print("  excluded: %s (same people as Arm A completers), %s (no identity row)"
          % (", ".join(sorted(OVERLAP)), ", ".join(sorted(UNRESOLVED))))
    print("REGISTERED PARTICIPANT CODES ACROSS ALL STUDIES: %d"
          % (len(a_reg) + len(b_reg) + len(raters)))


if __name__ == "__main__":
    main()
