// Viewer isolation: no network, storage, analytics, submission, login, token or telemetry; synthetic
// and not-live labels; accessible structure; loopback-only server; deployment exclusion; no public link.
import { execFileSync } from 'node:child_process';
import { request } from 'node:http';
import { t, done, ROOT, IN_REPO, PKG, read } from './_helpers.mjs';

const strip = (src) => src.replace(/\/\*[\s\S]*?\*\//g, '').replace(/(^|[^:'"])\/\/.*$/gm, '$1');
const html = read('tools/frozen-demo/viewer/index.html'), js = strip(read('tools/frozen-demo/viewer/viewer.js')), css = read('tools/frozen-demo/viewer/viewer.css');
const BANNED = [['fetch', /\bfetch\s*\(/], ['XMLHttpRequest', /XMLHttpRequest/], ['WebSocket', /WebSocket/], ['EventSource', /EventSource/], ['sendBeacon', /sendBeacon/],
  ['localStorage', /localStorage/], ['sessionStorage', /sessionStorage/], ['indexedDB', /indexedDB/i], ['cookies', /document\.cookie|cookieStore/], ['Cache API', /\bcaches\./],
  ['service worker', /serviceWorker/], ['Worker', /new\s+(Shared)?Worker/], ['dynamic import', /import\s*\(/], ['URL loading', /\b(?:window|document)\.location|location\.(?:href|search|hash|assign|replace)|URLSearchParams/], ['postMessage', /postMessage|BroadcastChannel/],
  ['HTML injection', /innerHTML|outerHTML|insertAdjacentHTML|document\.write|DOMParser/], ['eval', /\beval\s*\(|new Function\s*\(/], ['console', /console\./],
  ['analytics or telemetry', /gtag|googletagmanager|analytics|telemetry|\bG-[A-Z0-9]{6,}\b/i], ['remote URL', /https?:\/\//], ['file upload', /FileReader|showOpenFilePicker/], ['download', /createObjectURL|download=/]];
for (const [n, re] of BANNED) t('viewer code uses no ' + n, !re.test(js + css));
t('the viewer imports only its own data and the workspace core', [...js.matchAll(/^\s*import\s[^'"]*['"]([^'"]+)['"]/gm)].map((x) => x[1]).join() === './demo-data.js,./core.js');
t('index.html loads no remote resource', !/(src|href)\s*=\s*["']\s*(https?:)?\/\//i.test(html));
t("index.html carries a CSP with default-src 'none' and connect-src 'none'", /http-equiv="Content-Security-Policy"[^>]*default-src 'none'[^>]*connect-src 'none'/.test(html));
t('index.html is noindex and sends no referrer', /name="robots" content="noindex,nofollow"/.test(html) && /name="referrer" content="no-referrer"/.test(html));
t('the viewer has no form, text input, file input, password or submit control', !/<form\b|<input\b|<textarea\b|type=["'](submit|password|file)/i.test(html));
t('the viewer states the cases are synthetic', /SYNTHETIC CASES\. Every record shown here is fictional/.test(html));
t('the viewer states the Engine is not running against a live model and output is pre-generated with a mock', /not running against a live model/.test(html) && /pre-generated by the local candidate with a scripted mock adapter/.test(html));
t('the viewer states it has no submission, network, login, API, token, analytics, storage or telemetry function', /no record submission, network, login, API, token, analytics, storage or telemetry function/.test(html));
t('the viewer states it makes no pass, ready or approval decision', /makes no pass, ready or approval decision about any record/.test(html));
// A negated mention ('It carries no score') is a limitation, not a score.
const own = (html.replace(/<[^>]+>/g, ' ') + ' ' + [...js.matchAll(/'([^'\\]|\\.)*'/g)].map((x) => x[0]).join(' ')).replace(/\s+/g, ' ').replace(/\bno (score|rating|percentage)\b/gi, '');
t('no final pass, ready or approved decision in the viewer text', !/\b(?:overall|final)\s+(?:result|decision|status|verdict)\b|\b(?:record|case|exception|package)\s+(?:is|are)\s+(?:ready|approved|passed|compliant)\b|\bRESULT: PASS\b/i.test(own));
t('no score, rating or percentage in the viewer text', !/\b(score|rating|percent|percentage|grade)\b|\d+\s*%/i.test(own), (own.match(/.{30}(\b(score|rating|percent|percentage|grade)\b|\d+\s*%).{10}/i) || [])[0]);
t('no "verified" or "validated" badge in the viewer text', !/\bverified\b|\bvalidated\b/i.test(own));
t('no em dash in the viewer', !/—/.test(html + js + css));
// Required elements and accessibility.
t('the five required case-detail sections exist as tabs', ['Source preparation', 'Candidate findings', 'Reviewer packet', 'Human disposition example', 'What this case does not establish'].every((n) => html.includes('>' + n + '</button>')));
t('tabs use role tab and tabpanel with aria-controls, aria-selected and aria-labelledby', (html.match(/role="tab"/g) || []).length === 5 && (html.match(/role="tabpanel"/g) || []).length === 5 && (html.match(/aria-controls="panel-/g) || []).length === 5 && (html.match(/aria-labelledby="tab-/g) || []).length === 5);
t('tabs support arrow, Home and End keys', /ArrowRight/.test(js) && /ArrowLeft/.test(js) && /'Home'/.test(js) && /'End'/.test(js));
t('the case selector is labelled', /<label for="case-select">/.test(html) && /<select id="case-select">/.test(html));
t('the page has a language, a skip link, one h1, and a live region for the manifest check', /<html lang="en">/.test(html) && /class="skip" href="#main"/.test(html) && (html.match(/<h1\b/g) || []).length === 1 && /id="check-status" role="status" aria-live="polite"/.test(html));
t('a scope and limitations panel and an identity panel exist', /id="scope-h">Scope and limitations</.test(html) && /id="identity-h">Package, candidate and record identity</.test(html));
t('a local manifest check control exists', /id="check-btn">Check the frozen manifest</.test(html));
t('focus is visible and colours come from the design tokens', /:focus-visible/.test(css) && /--accent: #BE9447/.test(css) && (css.replace(/:root[^}]*\}/, '').match(/#[0-9A-Fa-f]{3,6}\b/g) || []).length === 0);
t('the refusal case has its own banner', /id="refusal-banner"/.test(html) && /Refusal case:/.test(js));

// The loopback server.
const S = await import(PKG + 'serve-viewer.mjs');
t('the server refuses a non-loopback bind address', (() => { try { S.assertLoopbackHost('0.0.0.0'); return false; } catch { return true; } })());
t('the server serves only the fixed viewer files and the workspace core', Object.keys(S.FILES).join() === '/,/index.html,/viewer.css,/viewer.js,/demo-data.js,/core.js,/correspondence.js');
const server = await S.startViewer({ port: 0 }), port = server.address().port;
const hit = (method, path, host) => new Promise((res) => { const q = request({ host: '127.0.0.1', port, method, path, headers: { host: host || '127.0.0.1:' + port } }, (r) => { let b = ''; r.on('data', (d) => b += d); r.on('end', () => res({ status: r.statusCode, headers: r.headers, body: b })); }); q.on('error', () => res({ status: 0 })); q.end(method === 'POST' ? '{"text":"x"}' : undefined); });
const g = await hit('GET', '/');
t("GET / returns the page with connect-src 'none' and no-store", g.status === 200 && /connect-src 'none'/.test(g.headers['content-security-policy']) && g.headers['cache-control'] === 'no-store' && /noindex/.test(g.headers['x-robots-tag']));
t('POST is refused (no record submission)', (await hit('POST', '/')).status === 405);
t('a non-loopback Host header is refused', (await hit('GET', '/', 'evil.example:' + port)).status === 421);
t('any other path is not found', (await hit('GET', '/demo-manifest.json')).status === 404 && (await hit('GET', '/../demo-manifest.json')).status === 404);
t('the served core.js is the workspace core, unchanged', (await hit('GET', '/core.js')).body === read('tools/local-reviewer-workspace/app/core.js'));
server.close();

// Deployment exclusion and public isolation.
if (IN_REPO) {
  const files = execFileSync('git', ['ls-files', '--others', '--cached', '--exclude-standard', 'tools/frozen-demo', 'tests/frozen-demo', 'docs/architecture'], { cwd: ROOT, encoding: 'utf8' }).split('\n').filter((f) => f && (/frozen-demo/.test(f) || /FROZEN_DEMONSTRATION/.test(f)));
  const out = execFileSync('git', ['-c', 'core.excludesFile=.vercelignore', 'check-ignore', '--no-index', '-v', '--stdin'], { cwd: ROOT, input: files.join('\n') + '\n', encoding: 'utf8' });
  const ex = new Set(out.trim().split('\n').filter(Boolean).map((l) => l.split('\t')[1]));
  t('every file of the package is excluded from deployment by .vercelignore (' + files.length + ' files)', files.length > 20 && files.every((f) => ex.has(f)), files.filter((f) => !ex.has(f)).join(', '));
  t('no package output is JSON under docs/architecture (which .vercelignore would not exclude)', !files.some((f) => /^docs\/architecture\/.*\.json$/.test(f)));
  let linked = '';
  try { linked = execFileSync('git', ['grep', '-l', '-I', '-e', 'frozen-demo', '-e', 'serve-viewer', '-e', 'demo-viewer', '--', '*.html', 'api', 'vercel.json', 'sitemap.xml', 'openapi*.json', '*.webmanifest', 'robots.txt'], { cwd: ROOT, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim(); } catch (e) { linked = e.status === 1 ? '' : 'git grep failed'; }
  t('no public page, API route, sitemap, OpenAPI file or Vercel configuration names the viewer', linked === '', linked);
  t('vercel.json names no tools path', !/tools\/|frozen/.test(read('vercel.json')));
}
done();
