// Provenance audit: report rendering. INTERNAL, LOCAL ONLY. Pure: a function of the analysis.
import { AREAS, ROUTING_NOTE, METADATA_NOTE, AUDIT_VERSION, DEP_STATUSES } from './analyze.js';

export const JSON_OUTPUTS = Object.freeze({
  snapshot: 'tools/provenance-audit/generated/snapshot.json',
  assets: 'tools/provenance-audit/generated/asset-inventory.json',
  boundary: 'tools/provenance-audit/generated/boundary-map.json',
  dependencies: 'tools/provenance-audit/generated/dependency-inventory.json',
  contribution: 'tools/provenance-audit/generated/contribution-map.json',
});
export const NON_CONCLUSION = 'This package records repository-visible evidence only. It does not establish chain of title, copyright ownership, trademark clearance, legal compliance, production readiness, licensing readiness, sale readiness or release authorization, and it is not a license opinion.';

const cell = (s) => String(s === null || s === undefined ? '' : s).replace(/\|/g, '\\|').replace(/\n/g, ' ');
const label = (id) => (AREAS.find((a) => a.id === id) || { label: 'Unclassified' }).label;
const head = (title, a) => [
  '# ' + title, '',
  '**Internal and non-public. Generated, do not edit by hand.** Generated by `tools/provenance-audit/run.mjs` (' + AUDIT_VERSION + ') from commit `' + a.snapshot.source_commit + '` (' + a.snapshot.commit_date + '). Inventory digest `' + a.snapshot.inventory_digest + '`. Regenerate with `node tools/provenance-audit/run.mjs --write`.', '',
  NON_CONCLUSION, '',
];
const byArea = (a) => { const m = {}; for (const f of a.files) (m[f.area] = m[f.area] || []).push(f); return m; };

export function renderInventory(a) {
  const L = head('Software asset and provenance inventory', a);
  const areas = byArea(a);
  L.push('## 1. Snapshot');
  L.push('| Field | Value |', '|---|---|');
  L.push('| Source commit | `' + a.snapshot.source_commit + '` |', '| Commit date | ' + a.snapshot.commit_date + ' |', '| Tracked files inventoried | ' + a.snapshot.tracked_files + ' |');
  L.push('| Commits available | ' + a.snapshot.commits_available + (a.snapshot.shallow_history ? ' (shallow clone: earlier history is not available here)' : '') + ' |');
  L.push('| Machine-readable outputs | `tools/provenance-audit/generated/` (excluded by `.vercelignore` `tools/`). JSON under `docs/architecture/` would not be excluded, so none is written there. |', '');
  L.push('The tool\'s own outputs are not inventoried. Paths with an opaque slug are shown as `-<slug>`.', '');
  L.push('## 2. Deployment boundary', ROUTING_NOTE, 'PUBLIC_SITE means deployed and reachable at an address on the site. The restricted surfaces of CLAUDE.md 36.3 (the private owner page and the confidential buyer pages) are deployed and unlinked, and are flagged as restricted in the asset inventory. DEPLOYED_SERVER_MODULE is code uploaded with the functions that is not addressable as a route.', '');
  L.push('| Boundary | Files |', '|---|---|');
  for (const [k, v] of Object.entries(a.totals.by_boundary)) L.push('| ' + k + ' | ' + v + ' |');
  L.push('');
  L.push('## 3. Areas', '| Area | Files | Boundaries | Exclusion rule | Purpose |', '|---|---|---|---|---|');
  for (const ar of AREAS.concat([{ id: 'UNCLASSIFIED', purpose: 'No area rule matches: REQUIRES_REVIEW' }])) {
    const fs = areas[ar.id]; if (!fs) continue;
    const bs = [...new Set(fs.map((f) => f.boundary))].sort().join(', '), rules = [...new Set(fs.map((f) => f.deployment_exclusion || 'deployed'))].sort().join('; ');
    L.push('| ' + cell(label(ar.id)) + ' | ' + fs.length + ' | ' + bs + ' | ' + cell(rules) + ' | ' + cell(ar.purpose) + ' |');
  }
  L.push('');
  L.push('## 4. API and route code', 'Route status is read from the code: `CONTROLLED_REFUSAL_STUB` imports `api/_controlled-review.js`; `SERVER_MODULE_NOT_A_ROUTE` is an underscore module; every other route is `DEPLOYED_ROUTE_BEHAVIOUR_NOT_ASSESSED`, because this audit does not exercise production.', '');
  L.push('| File | Route status | Restricted surface (CLAUDE.md 36.3) |', '|---|---|---|');
  for (const f of a.files.filter((x) => x.route_status)) L.push('| `' + f.path + '` | ' + f.route_status + ' | ' + (f.restricted_surface ? 'yes' : '') + ' |');
  L.push('');
  L.push('## 5. Engine candidate', 'Local development candidate, mock adapter only, excluded from deployment.', '', '| File | Exclusion rule | Version identifier |', '|---|---|---|');
  for (const f of areas['engine-candidate'] || []) L.push('| `' + f.path + '` | ' + cell(f.deployment_exclusion || 'DEPLOYED: REQUIRES_REVIEW') + ' | ' + cell(f.version_id || '') + ' |');
  L.push('');
  const tests = a.files.filter((f) => f.asset_class === 'TEST_OR_FIXTURE');
  const syn = tests.filter((f) => f.synthetic_material);
  L.push('## 6. Tests and fixtures', '- Test and fixture files: ' + tests.length + '.', '- Synthetic or constructed material: ' + syn.length + ' files, of which ' + syn.filter((f) => f.holdout_exclusion === 'REGISTERED_DEVELOPMENT_MATERIAL').length + ' are registered as development material (excluded from any holdout by `lib/engine-candidate/dev-material.js`).');
  const unreg = syn.filter((f) => f.holdout_exclusion === 'NOT_REGISTERED');
  L.push('- Synthetic or constructed files not in that registry: ' + unreg.length + '. Holdout status for them is NOT_ESTABLISHED by this audit; many are test code or expectations rather than record texts.', '');
  L.push('## 7. Local-only tools');
  for (const id of ['provenance-audit', 'local-reviewer-workspace', 'other-tools', 'scripts', 'retention-policy']) if (areas[id]) L.push('- ' + label(id) + ': ' + areas[id].length + ' files; ' + [...new Set(areas[id].map((f) => f.deployment_exclusion || 'deployed'))].join('; ') + '.');
  L.push('');
  L.push('## 8. Schemas and internal protocols', '| File | Version identifier |', '|---|---|');
  for (const f of a.files.filter((x) => x.asset_class === 'SCHEMA_OR_PROTOCOL' && x.version_id)) L.push('| `' + f.path + '` | ' + cell(f.version_id) + ' |');
  L.push('');
  L.push('## 9. Research and documentation', 'Contents are not reproduced here. Research files may contain study-participant material, so each is marked INCLUDE_AFTER_REVIEW for any future package.', '');
  for (const id of ['research', 'docs-architecture', 'docs-other', 'control-state', 'unpublished-standard', 'office-documents', 'instructions', 'root-markdown']) if (areas[id]) L.push('- ' + label(id) + ': ' + areas[id].length + ' files, boundary ' + [...new Set(areas[id].map((f) => f.boundary))].join(', ') + '.');
  L.push('');
  L.push('## 10. Configuration', 'No configuration value is reproduced. Significance:', '');
  const sig = { 'vercel.json': 'Vercel routing, redirects, rewrites, headers, crons and the forced-build ignore command', '.vercelignore': 'Deployment exclusion rules (routing, not confidentiality)', '.gitignore': 'Files git does not track', 'CNAME': 'A custom-domain record file; which host reads it is NOT_ESTABLISHED by this audit' };
  for (const f of a.files.filter((x) => x.area === 'deploy-config' || x.area === 'ci-config' || x.area === 'database-schema' || x.area === 'agent-config')) L.push('- `' + f.path + '`: ' + (sig[f.path] || label(f.area)) + '; ' + (f.deployment_exclusion ? 'excluded (' + f.deployment_exclusion + ')' : 'deployed with the site') + '.');
  L.push('');
  L.push('## 11. Generated files', '| File | Generator recorded in the file |', '|---|---|');
  for (const f of a.files.filter((x) => x.generated)) L.push('| `' + f.path + '` | ' + cell(f.generated_source) + ' |');
  L.push('');
  L.push('## 12. Public and private boundary map', ROUTING_NOTE, '', '| Area | Boundary | Files | Exclusion rule | Synthetic files | May hold record excerpts | Future diligence package | Exclude from public release |', '|---|---|---|---|---|---|---|---|');
  for (const g of a.boundary_groups) L.push('| ' + cell(label(g.area)) + ' | ' + g.boundary + ' | ' + g.files + ' | ' + cell(g.exclusion_rules.join('; ') || 'deployed') + ' | ' + g.synthetic_files + ' | ' + g.may_contain_record_excerpts.join(', ') + ' | ' + g.diligence.join(', ') + ' | ' + (g.exclude_from_public_release ? 'yes' : 'no') + ' |');
  L.push('');
  L.push('## 13. Contribution map', METADATA_NOTE, '', '| Area | Files | Earliest available commit | Most recent commit | Commits | With AI-tool markers | Origin labels | Identities in git metadata |', '|---|---|---|---|---|---|---|---|');
  for (const r of a.contribution) L.push('| ' + cell(label(r.area)) + ' | ' + r.files + ' | ' + (r.earliest_available_commit ? '`' + r.earliest_available_commit.hash.slice(0, 7) + '` ' + r.earliest_available_commit.date : 'none') + ' | ' + (r.most_recent_available_commit ? '`' + r.most_recent_available_commit.hash.slice(0, 7) + '` ' + r.most_recent_available_commit.date : 'none') + ' | ' + r.commits_touching + ' | ' + r.commits_with_ai_tool_markers + ' | ' + r.origin_labels.join(', ') + ' | ' + cell(r.contributor_identities.map((x) => x.identity + ' (' + x.commits + ')').join('; ')) + ' |');
  L.push('', 'Email addresses are masked. Counts are commits recorded in the available history, not an authorship measure and not an ownership share.', '');
  L.push('## 14. Credential-like pattern scan', 'Pattern names and file paths only; no value is reproduced.', '');
  const sp = Object.entries(a.secret_patterns);
  if (!sp.length) L.push('No credential-like pattern matched.');
  for (const [k, v] of sp) L.push('- `' + k + '`: ' + v.count + ' file(s) (' + v.files.map((p) => '`' + p + '`').join(', ') + '). ' + v.note);
  L.push('');
  L.push('## 15. Unknown and REQUIRES_REVIEW items');
  for (const u of unknowns(a)) L.push('- ' + u);
  L.push('');
  return L.join('\n');
}

export function unknowns(a) {
  const u = [];
  const unc = a.files.filter((f) => f.area === 'UNCLASSIFIED'), unb = a.files.filter((f) => f.boundary === 'UNKNOWN');
  u.push(unc.length ? 'UNKNOWN: ' + unc.length + ' tracked file(s) match no area rule: ' + unc.map((f) => '`' + f.path + '`').join(', ') + '.' : 'Every tracked file matched an area rule.');
  if (unb.length) u.push('REQUIRES_REVIEW: ' + unb.length + ' file(s) are deployed but are not of a kind expected on the site: ' + unb.slice(0, 20).map((f) => '`' + f.path + '`').join(', ') + (unb.length > 20 ? ', and ' + (unb.length - 20) + ' more (see boundary-map.json).' : '.'));
  u.push('UNKNOWN: repository license. ' + a.dependencies.repository_license + '.');
  u.push('MISSING_LOCAL_LICENSE_METADATA: ' + a.dependencies.components.filter((c) => c.status === 'MISSING_LOCAL_LICENSE_METADATA').length + ' third-party component(s); no package manifest, lockfile or notice file is tracked.');
  const routes = a.files.filter((f) => f.route_status === 'DEPLOYED_ROUTE_BEHAVIOUR_NOT_ASSESSED').length;
  u.push('REQUIRES_REVIEW: ' + routes + ' deployed route(s) whose production behaviour this audit does not exercise.');
  if (Object.keys(a.secret_patterns).length) u.push('REQUIRES_REVIEW: credential-like pattern matches listed in section 14.');
  u.push('REQUIRES_REVIEW: research and diligence documents that may contain study-participant or record material (' + a.files.filter((f) => f.may_contain_record_excerpts === 'REQUIRES_REVIEW').length + ' files).');
  if (a.snapshot.shallow_history) u.push('UNKNOWN: history before the shallow-clone boundary, including the origin of files first seen at the earliest available commit.');
  u.push('UNKNOWN: contributor, contractor, assignment and license instruments. None is identified by this audit; whether any exists outside the repository is not established here.');
  return u;
}

export function renderThirdParty(a) {
  const d = a.dependencies, L = head('Third-party components and notices', a);
  L.push('A dependency inventory is not a license opinion. It lists only evidence present in the repository at the source commit. No registry, repository host, vendor site or license service was consulted.', '');
  L.push('## Manifests and notices', '- Package manifests and lockfiles tracked: ' + (d.manifests.length ? d.manifests.map((x) => '`' + x + '`').join(', ') : 'none') + '.', '- License, COPYING or NOTICE files tracked: ' + (d.license_files.length ? d.license_files.map((x) => '`' + x + '`').join(', ') : 'none') + '.', '- Repository license: ' + d.repository_license + '.', '');
  L.push('## Status values', '- **RECORDED:** a local license field or notice for the component is tracked. No component has this status at this commit.', '- **MISSING_LOCAL_LICENSE_METADATA:** the component is used, and no local license field, notice or package metadata for it is tracked.', '- **UNKNOWN:** the evidence does not identify the component\'s terms (for example a runtime built-in module).', '- **REQUIRES_REVIEW:** the evidence is present but needs a person to interpret it.', '');
  L.push('## Components', '| Component | Ecosystem | Kind | Declared version | Local license evidence | Status | Seen in |', '|---|---|---|---|---|---|---|');
  for (const c of d.components) L.push('| `' + cell(c.name) + '` | ' + c.ecosystem + ' | ' + cell(c.kind) + ' | ' + cell(c.declared_version) + ' | ' + c.local_license_evidence + ' | ' + c.status + ' | ' + c.location_count + ' file(s) |');
  L.push('', 'Test-environment tools that are not tracked, such as the Playwright and Chromium installation the browser tests use when present, are not repository components and are not listed. Locations per component are in `tools/provenance-audit/generated/dependency-inventory.json`.', '');
  return L.join('\n');
}

export function renderDisclosure(a) {
  const L = head('AI-assisted development disclosure', a);
  const ai = a.contribution.filter((r) => r.commits_with_ai_tool_markers > 0);
  const ids = new Map(); for (const r of a.contribution) for (const x of r.contributor_identities) ids.set(x.identity, true);
  L.push('## What the repository shows');
  L.push('- AI-assisted tools may have contributed to code and documentation in this repository. The available history (' + a.snapshot.commits_available + ' commits' + (a.snapshot.shallow_history ? ', shallow' : '') + ') includes commits whose git author identity is an AI tool, and commits carrying AI co-author or session trailers.');
  L.push('- Identities recorded in git metadata (emails masked): ' + [...ids.keys()].sort().map((x) => '`' + x + '`').join(', ') + '.');
  L.push('- Areas with at least one commit carrying an AI-tool marker: ' + ai.length + ' of ' + a.contribution.length + '. Per-area counts are in the inventory, section 13.', '');
  L.push('## What it does not show');
  L.push('- ' + METADATA_NOTE);
  L.push('- A marker records that a tool took part in a commit. Its absence does not show that a person wrote a change, and its presence does not show how much of a change a tool produced.');
  L.push('- Tool-assisted generation is a provenance fact. It is distinct from legal authorship and from ownership, and this disclosure makes no determination about either.');
  L.push('- No AI tool or provider is recorded here as having assigned, licensed or transferred any right, and this disclosure does not claim that any did.');
  L.push('- Records of human direction, review, selection and acceptance may exist separately, for example in session transcripts, review threads or the owner\'s own records. They are not reproduced here, and no prompt, key, private conversation or development transcript is included.', '');
  L.push('## For a future transaction');
  L.push('If a counterparty requires ownership or provenance representations, transaction-specific legal review is needed. It would consider the applicable tool and provider terms, the human contribution records, and any contributor instruments. This disclosure is an input to that review, not a substitute for it.', '');
  return L.join('\n');
}

export function renderReadiness(a) {
  const L = head('Technical diligence readiness report', a);
  const t = a.totals.by_boundary, comp = a.dependencies.components;
  L.push('## 1. Purpose and scope', 'This report organizes what a prospective technical reviewer could inspect in the repository and what would need separate evidence. It may support future diligence preparation, but it does not make JRS transaction-ready. It is based only on repository-visible evidence at the source commit.', '');
  L.push('## 2. What the repository currently documents');
  L.push('- A tracked tree of ' + a.snapshot.tracked_files + ' files, classified into ' + Object.keys(a.totals.by_area).length + ' areas (`SOFTWARE_ASSET_AND_PROVENANCE_INVENTORY.md`).');
  L.push('- The deployment boundary through `.vercelignore` and `vercel.json`.', '- A local Review Engine candidate with its architecture, runbook, tests and constructed corpora (`lib/engine-candidate/`).', '- An internal release-gate package whose current record shows every gate open (`lib/release-gate/`, `docs/architecture/CURRENT_RELEASE_GATE_REPORT.md`).', '- A local reviewer workspace for offline human review of candidate packets (`tools/local-reviewer-workspace/`).', '- Control state, registers and reconciliation documents (`.jrs/`, `docs/`).', '');
  L.push('## 3. What a prospective technical reviewer could inspect now');
  L.push('- Public site source (' + (t.PUBLIC_SITE || 0) + ' files) and route code (' + ((t.PUBLIC_ROUTE || 0) + (t.CONTROLLED_OR_CLOSED_ROUTE || 0)) + ' route files, ' + (t.CONTROLLED_OR_CLOSED_ROUTE || 0) + ' of them controlled refusal stubs).', '- Local-internal code and tests, with their deterministic test commands.', '- The machine-readable inventory in `tools/provenance-audit/generated/`.', '');
  L.push('## 4. What remains unavailable, unknown, or requires separate evidence');
  for (const u of unknowns(a)) L.push('- ' + u);
  L.push('- Production behaviour, operator controls and live data stores. This audit does not exercise them (release gate RG-2).', '');
  L.push('## 5. Public versus controlled versus local-only technical assets', ROUTING_NOTE, '', '| Boundary | Files |', '|---|---|');
  for (const [k, v] of Object.entries(t)) L.push('| ' + k + ' | ' + v + ' |');
  L.push('');
  L.push('## 6. Dependency and provenance limitations');
  L.push('- No package manifest, lockfile or license notice is tracked. ' + comp.filter((c) => c.status === 'MISSING_LOCAL_LICENSE_METADATA').length + ' third-party component(s) are recorded with MISSING_LOCAL_LICENSE_METADATA and ' + comp.filter((c) => c.status === 'UNKNOWN').length + ' runtime built-in module(s) as UNKNOWN.');
  L.push('- ' + METADATA_NOTE);
  if (a.snapshot.shallow_history) L.push('- The clone is shallow: the earliest available commit is a history boundary.');
  L.push('- AI-tool markers appear in the history; see `AI_ASSISTED_DEVELOPMENT_DISCLOSURE.md`.', '');
  L.push('## 7. Required future diligence items', 'A factual checklist for a future process. It does not ask for any action now.', '');
  for (const i of ['Executed rights instruments, if applicable.', 'Contributor and contractor terms, if applicable.', 'Publisher agreements.', 'Domain registrar evidence.', 'Trademark review.', 'Software dependency review.', 'Privacy and data-flow documentation.', 'Production-control evidence.', 'Release-gate evidence.', 'A proposed transaction-specific asset schedule.']) L.push('- [ ] ' + i);
  L.push('');
  L.push('## 8. Explicit non-conclusions');
  L.push('- ' + NON_CONCLUSION);
  L.push('- Git history and line attribution are evidence of repository activity, not legal authorship or ownership determinations.', '- Public availability of code or material does not establish unrestricted commercial rights.', '- A missing assignment, license, notice or contributor instrument is recorded as UNKNOWN or REQUIRES_REVIEW, not inferred.', '- No release gate advanced, and no production, licensing, sale, evaluation or real-record authorization is created.', '');
  return L.join('\n');
}

export function renderAll(a) {
  return {
    'docs/architecture/SOFTWARE_ASSET_AND_PROVENANCE_INVENTORY.md': renderInventory(a),
    'docs/architecture/THIRD_PARTY_COMPONENTS_AND_NOTICES.md': renderThirdParty(a),
    'docs/architecture/AI_ASSISTED_DEVELOPMENT_DISCLOSURE.md': renderDisclosure(a),
    'docs/architecture/TECHNICAL_DILIGENCE_READINESS_REPORT.md': renderReadiness(a),
    [JSON_OUTPUTS.snapshot]: json({ audit_version: a.audit_version, snapshot: a.snapshot, totals: a.totals, routing_note: a.routing_note, metadata_note: a.metadata_note, non_conclusion: NON_CONCLUSION, dependency_statuses: DEP_STATUSES }),
    [JSON_OUTPUTS.assets]: '{"source_commit":' + JSON.stringify(a.snapshot.source_commit) + ',"inventory_digest":' + JSON.stringify(a.snapshot.inventory_digest) + ',"files":[\n' + a.files.map((f) => JSON.stringify(f)).join(',\n') + '\n]}\n',
    [JSON_OUTPUTS.boundary]: json({ source_commit: a.snapshot.source_commit, inventory_digest: a.snapshot.inventory_digest, routing_note: a.routing_note, groups: a.boundary_groups }),
    [JSON_OUTPUTS.dependencies]: json({ source_commit: a.snapshot.source_commit, inventory_digest: a.snapshot.inventory_digest, note: 'A dependency inventory is not a license opinion.', ...a.dependencies }),
    [JSON_OUTPUTS.contribution]: json({ source_commit: a.snapshot.source_commit, inventory_digest: a.snapshot.inventory_digest, metadata_note: a.metadata_note, areas: a.contribution }),
  };
}
const json = (o) => JSON.stringify(o, null, 1) + '\n';
