// Claim provenance: claim categories for the public-claim limitation matrix and the claim cards.
// INTERNAL drafting controls, not public copy. Each category names the register topics it covers,
// so its cards always list the current claims and their evidence hashes.
//   may_say          what may be stated: a factual, dated, historic result, or a current fact with its limit;
//   must_accompany   what has to travel with it;
//   must_not         what must not be said;
//   market           whether this may be presented as a current capability (it never may, for research).

export const CATEGORIES = Object.freeze([
  { id: 'jrs-methodology', title: 'JRS methodology', topics: ['METHODOLOGY', 'CONDITION_BEHAVIOUR', 'RESEARCH_STATUS'],
    may_say: 'What the five review conditions ask, and that the methodology is under study. Descriptive results with their study, date and sample.',
    must_accompany: 'The five conditions are not psychometrically validated. Associations between the conditions and the overall determination are expected by construction.',
    must_not: 'That JRS is a validated, independently validated or psychometrically validated standard; that the conditions discriminate, on the strength of p-values from the condition and determination association.',
    market: 'May describe the method. May not market validation.',
    short_form: 'JRS is a five-condition review method for decision records. It is under study; it is not presented as validated.',
    prohibited_shorthand: ['validated standard', 'scientifically validated', 'the conditions predict the outcome'] },
  { id: 'constructed-detection', title: 'Constructed detection findings', topics: ['DETECTION'],
    may_say: 'A factual historic result: 16 reviewers, 24 constructed records, 384 graded reads, mean accuracy 83.9 percent (95 percent CI 72.7 to 95.1, participant level), data lock 15 August 2026; sensitivity 87.0 percent and specificity 80.7 percent; reviewer range 37.5 to 100 percent.',
    must_accompany: 'Constructed corpus and author-generated reference classification; mean of reviewer scores; not reliability and not field performance; the reviewer-level spread.',
    must_not: 'Accuracy on real records; a reliability or agreement figure; any per-reviewer expectation from the mean; any Engine performance figure.',
    market: 'May state a factual historic result. May not market a current detection capability.',
    short_form: 'On a constructed 24-record corpus, 16 reviewers matched the reference classification at a mean accuracy of 83.9 percent (data lock 15 August 2026).',
    prohibited_shorthand: ['JRS is 83.9 percent accurate', '83.9 percent reliable', 'detects DRR in real records'] },
  { id: 'reviewer-agreement', title: 'Reviewer agreement findings', topics: ['RELIABILITY'],
    may_say: 'A factual historic result from a separate 10-record sample: Gwet\'s AC1 0.739 (invited experts) and 0.623 (regular reviewers), with the pre-registered criterion not met.',
    must_accompany: 'Separate and smaller sample; 10 records; analytic lower bounds 0.402 and 0.252 against the required 0.41; interim.',
    must_not: 'That reviewers reliably agree; a verbal band such as "substantial"; agreement as correctness or as psychometric validation.',
    market: 'May state a factual historic result. May not market reliability.',
    short_form: 'In a separate 10-record sample, AC1 was 0.739 and 0.623; the pre-registered criterion was not met.',
    prohibited_shorthand: ['reviewers reliably agree', 'substantial agreement', 'reliable standard'] },
  { id: 'cross-model-agreement', title: 'Cross-model agreement findings', topics: ['CROSS_MODEL'],
    may_say: 'Factual historic consistency figures, each with its own denominator and window: 61 runs (12 June to 21 August 2026, 66.7 to 93.3 percent, mean 85.3 percent); 37 runs at the full 15-record set as read on 13 August 2026 (82.2 to 93.3 percent); 41 runs at the 15 August 2026 data lock.',
    must_accompany: 'Raw agreement only; the reproducibility criterion is not established because the required AC1 was not computed; the denominator and window of the figure used.',
    must_not: 'Accuracy, human reliability or independent validation; swapping one run count for another; a single "latest" run as the result.',
    market: 'May state a factual historic result. May not market model accuracy or reproducibility.',
    short_form: 'Across 61 recorded runs (12 June to 21 August 2026), raw agreement across three models ranged from 66.7 to 93.3 percent; this is consistency, not accuracy.',
    prohibited_shorthand: ['85 percent accurate AI', 'validated by three AI vendors', 'reproducible'] },
  { id: 'participation', title: 'Participant geography and participation counts', topics: ['PARTICIPATION'],
    may_say: '58 international reviewers across three studies; 36 completed the full 24-record set across 16 countries; the detection panel was 16 reviewers in 11 countries.',
    must_accompany: 'Which group each count describes. Participation is acknowledgment, not a result.',
    must_not: 'That participants validated, endorsed or confirmed JRS; mixing the 16-country and 11-country figures.',
    market: 'May state participation. May not present it as endorsement.',
    short_form: '58 international reviewers took part across three studies.',
    prohibited_shorthand: ['58 experts validated JRS', 'endorsed by experts in 16 countries'] },
  { id: 'local-engine-development', title: 'Local Engine development', topics: ['ENGINE_LOCAL_EVALUATION', 'ENGINE_REGRESSION', 'ENGINE_PROVENANCE', 'ENGINE_ROUTE_STATUS', 'MANIFEST'],
    may_say: 'That a controlled local-development candidate exists; that its repository tests use a mock adapter and constructed records; that public review routes refuse submissions.',
    must_accompany: 'Mock adapter; constructed development records; not a measure of accuracy, reliability or validity; no provider called.',
    must_not: 'That the Engine is tested on real records, evaluated, accurate, validated or ready; any research figure as Engine evidence.',
    market: 'May describe development status. May not market a capability.',
    short_form: 'The Review Engine is a controlled local-development candidate. It is not validated and not available for use.',
    prohibited_shorthand: ['production-ready', 'Engine accuracy', 'tested and validated'] },
  { id: 'source-grounding', title: 'Source-grounding controls', topics: ['ENGINE_SOURCE_GROUNDING'],
    may_say: 'That local tests check each candidate quotation occurs exactly in the record, and that unlocatable quotations are withheld.',
    must_accompany: 'Exact quotation presence is not semantic support; an anchor shows where text sits, not that it supports the finding.',
    must_not: 'That findings are correct, verified, hallucination-free or semantically supported because they are quoted.',
    market: 'Internal only.',
    short_form: 'Candidate quotations are checked to occur exactly in the record; this is not semantic support.',
    prohibited_shorthand: ['hallucination-free', 'every finding is verified'] },
  { id: 'public-resources-training', title: 'Public resources and training', topics: ['PROCEDURAL_GUIDANCE'],
    may_say: 'What the materials teach and how to begin, with guidance quantities presented as guidance.',
    must_accompany: 'Guidance quantities (records to start with, group sizes) are not research findings.',
    must_not: 'Guidance numbers phrased as measured results; certification or qualification claims.',
    market: 'May describe the materials. May not present guidance as evidence.',
    short_form: 'The training teaches the five review conditions. Guidance on how many records to start with is guidance, not a finding.',
    prohibited_shorthand: ['certified reviewer', 'proven in 3 records'] },
  { id: 'privacy-security-history', title: 'Privacy and security history', topics: ['PRIVACY_SECURITY'],
    may_say: 'Historical data flows as history; the current position that no route accepts record text.',
    must_accompany: 'Historical labelling; whether stored output remains is NOT ESTABLISHED; a written policy does not prove a live control.',
    must_not: 'Historical data flows in the present tense; that data is "secure" or that a control operates, without operator evidence.',
    market: 'May state history and current route status. May not market security.',
    short_form: 'An earlier implementation sent record text to a model provider; that data flow is no longer active.',
    prohibited_shorthand: ['secure by design', 'deleted after 90 days'] },
  { id: 'controlled-evaluation', title: 'Controlled evaluation discussions', topics: ['RELEASE_GATE', 'ENGINE_STATUS'],
    may_say: 'That no release gate has passed and no evaluation access is offered.',
    must_accompany: 'Every gate is BLOCKED or NOT_ASSESSED; any future evaluation needs a new owner instruction.',
    must_not: 'That an evaluation is available, under way or passed; that research results stand in for an Engine evaluation.',
    market: 'May state the gate status. May not offer an evaluation.',
    short_form: 'No release gate has passed, and no evaluation access is offered.',
    prohibited_shorthand: ['request an evaluation', 'evaluation-ready'] },
  { id: 'commercial-acquisition', title: 'Future commercial or acquisition language', topics: ['COMMERCIAL'],
    may_say: 'That no licensing, sale or acquisition pathway is offered.',
    must_accompany: 'Rights and title are not established; any future pathway requires owner authorization and legal review.',
    must_not: 'Licensing-ready, sale-ready, acquisition-ready, or any offer to license, sell or acquire.',
    market: 'Never.',
    short_form: 'No licensing, sale or acquisition pathway is offered.',
    prohibited_shorthand: ['licensing-ready', 'sale-ready', 'available for licensing'] },
  { id: 'drr-studies', title: 'DRR studies about AI drafting', topics: ['DRR_STUDY'],
    may_say: 'Study results with their reader, sample and scope.',
    must_accompany: 'Who or what the reader was, the number of texts, and that it is research about AI drafting tools, not Engine output or a DRR score.',
    must_not: 'A human-reader result where the reader was a model; an Engine or DRR-score figure.',
    market: 'May state a factual historic result. May not market a measurement capability.',
    short_form: 'On 29 texts, an AI reader given only one model\'s summary answered 77 percent of masked questions, against 97 percent from the original.',
    prohibited_shorthand: ['readers lose a fifth of the facts', 'the Engine measures DRR'] },
  { id: 'publication-status', title: 'Publication and editorial status', topics: ['PUBLICATION_STATUS'],
    may_say: 'An acceptance only where the venue\'s decision is on file, named with its venue type.',
    must_accompany: 'Venue type (practitioner magazine or journal); whether the acceptance is documented by the venue or only by the author\'s file.',
    must_not: 'A target venue as an acceptance; an invitation to revise as an acceptance; a magazine acceptance as peer review.',
    market: 'May state documented publication. May not imply peer-reviewed validation.',
    short_form: 'An article was accepted by CEP Magazine for its November 2026 issue.',
    prohibited_shorthand: ['peer-reviewed', 'published in the Journal of Business Ethics'] },
]);
