// Claim provenance: the current claim-evidence records. INTERNAL, LOCAL ONLY.
//
// One record per material claim. Figures, denominators, dates and populations are copied from
// the named source exactly; none is recalculated, rounded or merged with another window. The
// `scan` block tells the public-claim scanner how to recognise the claim in a public sentence:
//   figures     the numeric expressions this claim owns (a public figure no claim owns is unsupported);
//   signatures  any match links a sentence to this claim;
//   qualifiers  [name, pattern] that must appear in the sentence or its neighbours;
//   prohibited  [name, pattern] that must not appear in the sentence unless it is negated.
// This register is a control over wording. It is not new evidence and validates nothing.

const REVIEWED = [{ date: '2026-10-06', change: 'Registered by the claim-provenance package from repository-visible evidence. No figure recalculated.' }];
const ENGINE_SEPARATE = 'Research about JRS is not evidence about the Engine, and this record is not cited as Engine evidence.';

let n = 0;
function c(o) {
  n += 1;
  return {
    claim_id: 'CL-' + String(n).padStart(3, '0'),
    claim_text: o.text, claim_topic: o.topic, claim_type: o.type, surface: o.surface,
    evidence_id: o.evidence, source_path: null, source_location: o.at, source_hash: null,
    evidence_class: null, reproduction: o.reproduction || (o.evidence === 'EV-NONE' ? 'NOT_APPLICABLE' : 'SOURCE_REPORTED'),
    population: o.population || null,
    quantities: o.quantities || null,
    date_or_data_lock: o.date || null,
    limitation: o.limitation, limitation_key: o.limitationKey || null,
    permitted_wording: o.permitted, prohibited_overstatement: o.prohibitedWording || [],
    public_use: o.publicUse, status: o.status, engine_relationship: o.engine || 'NO_ENGINE_INFERENCE',
    scan: { figures: o.figures || [], signatures: o.signatures || [], qualifiers: o.qualifiers || [], prohibited: o.prohibited || [] },
    review_history: o.history || REVIEWED,
  };
}

const CONSTRUCTED = ['constructed corpus', 'constructed|24-record|author-generated'];
const PANEL = ['detection panel scope', '\\b16\\b|panel'];
const NOT_RELIABILITY = ['detection labelled reliability', '83\\.9(?:[^.;()]|\\.(?=\\d)){0,40}\\b(reliab\\w*|inter-rater|agreement)\\b|\\b(reliab\\w*|inter-rater|agreement)\\b(?:[^.;()]|\\.(?=\\d)){0,30}83\\.9'];
const NOT_FIELD = ['constructed result presented as real-world', '(83\\.9|87\\.0|80\\.7)(?:[^.;()]|\\.(?=\\d)){0,60}\\b(real[- ]world|field performance|in practice|real records)\\b|\\b(real[- ]world|field performance|in practice|real records)\\b(?:[^.;()]|\\.(?=\\d)){0,40}(83\\.9|87\\.0|80\\.7)'];
const NOT_ENGINE = ['research transferred to the Engine', '\\b(Review Engine|the Engine)\\b'];

const BASE = [
  // ---- 1. constructed-corpus detection panel ---------------------------------------------------------
  c({ text: 'Panel accuracy against the reference classification was 83.9 percent (95 percent CI 72.7 to 95.1 at participant level) on 24 constructed records, 16 reviewers, 384 graded reads; this cleared the pre-registered threshold of at least 70 percent.',
    topic: 'DETECTION', type: 'NUMERICAL_RESULT', surface: 'PUBLIC_PAGE', evidence: 'EV-DETECTION-ARTICLE', at: 'Abstract (Result) and Section 6.1, Table 1',
    population: '16 reviewers who completed all 24 constructed AI-generated records; 384 scorable graded reads (385 retained, 1 administrative row excluded)',
    quantities: { value: '83.9 percent', numerator: null, denominator: '16 reviewer-level accuracy scores, each out of 24 records', denominator_required: true, unit: 'mean of reviewer-level accuracy' },
    date: 'data lock 2026-08-15',
    limitation: 'A detection result on a constructed corpus against an author-generated reference classification. It is the mean of 16 reviewer scores, not a pooled proportion, not inter-rater reliability, and not an estimate of field performance on real records.',
    limitationKey: 'constructed',
    permitted: 'On a constructed 24-record corpus, 16 reviewers matched the reference classification at a mean accuracy of 83.9 percent (95 percent CI 72.7 to 95.1, participant level; 384 graded reads; data lock 15 August 2026). This is a detection result on constructed records, not reliability and not field performance.',
    prohibitedWording: ['JRS is 83.9 percent accurate', 'reviewers agree 83.9 percent of the time', '83.9 percent reliability', '83.9 percent accuracy on real records', 'the Engine detects at 83.9 percent'],
    publicUse: 'MAY_STATE_HISTORIC_RESULT_WITH_LIMITATION', status: 'SUPPORTED_WITH_LIMITATION',
    figures: ['83\\.9\\s?(%|percent)?', '72\\.7', '95\\.1', '95\\s?(%|percent)\\s+(CI|confidence)', '\\b384\\b', '\\b385\\b', '\\b70\\s?(%|percent)', '24-record', '\\b24 (constructed )?records\\b', '\\b16 (independent |detection-panel |individual )?(experts|reviewers|raters)\\b'],
    signatures: ['83\\.9', '72\\.7 to 95\\.1', '\\b384 (graded|determinations|judgments|reads)'],
    qualifiers: [CONSTRUCTED, PANEL], prohibited: [NOT_RELIABILITY, NOT_FIELD, NOT_ENGINE] }),
  c({ text: 'Sensitivity was 87.0 percent for unsupported records and specificity 80.7 percent for grounded ones, on the same constructed corpus.',
    topic: 'DETECTION', type: 'NUMERICAL_RESULT', surface: 'PUBLIC_PAGE', evidence: 'EV-DETECTION-ARTICLE', at: 'Abstract (Result); Section 6.4',
    population: 'the 384 graded reads of the detection panel', quantities: { value: '87.0 / 80.7 percent', numerator: null, denominator: 'unsupported and grounded records of the 24-record corpus', denominator_required: true, unit: 'percent' },
    date: 'data lock 2026-08-15', limitation: 'Constructed corpus only. Which direction of error is preferable depends on a cost model the programme has not built.', limitationKey: 'constructed',
    permitted: 'On the constructed 24-record corpus, sensitivity was 87.0 percent and specificity 80.7 percent.', prohibitedWording: ['JRS catches 87 percent of bad records'],
    publicUse: 'MAY_STATE_HISTORIC_RESULT_WITH_LIMITATION', status: 'SUPPORTED_WITH_LIMITATION',
    figures: ['87\\.0\\s?(%|percent)', '80\\.7\\s?(%|percent)'], signatures: ['87\\.0\\s?(%|percent)', '80\\.7\\s?(%|percent)'], qualifiers: [CONSTRUCTED], prohibited: [NOT_FIELD, NOT_ENGINE] }),
  c({ text: 'Reviewer-level accuracy ranged from 37.5 to 100 percent (SD 21.0); 6 of 16 reviewers scored all 24 records correctly.',
    topic: 'DETECTION', type: 'NUMERICAL_RESULT', surface: 'PUBLIC_PAGE', evidence: 'EV-DETECTION-ARTICLE', at: 'Abstract; Section 6.2, Table 2',
    population: '16 detection-panel reviewers', quantities: { value: '37.5 to 100 percent', numerator: null, denominator: '16 reviewers', denominator_required: true, unit: 'reviewer-level accuracy' },
    date: 'data lock 2026-08-15', limitation: 'Group-level detectability is not individual-level dependability: the panel mean is not any one reviewer\'s expected performance.', limitationKey: 'individual',
    permitted: 'Across the 16 panel reviewers, individual accuracy ranged from 37.5 to 100 percent (SD 21.0), so the panel mean is not any individual reviewer\'s expected performance.',
    publicUse: 'MAY_STATE_HISTORIC_RESULT_WITH_LIMITATION', status: 'SUPPORTED_WITH_LIMITATION',
    figures: ['37\\.5\\s+to\\s+100\\s?(%|percent)?', '\\b21\\.0\\b', '\\b6 of 16\\b', '\\bscored 100\\s?(%|percent)'], signatures: ['37\\.5\\s+to\\s+100', '[Ss]ix of the panel scored 100'], qualifiers: [], prohibited: [NOT_ENGINE] }),
  // ---- 2. separate reviewer-agreement sample ------------------------------------------------------------
  c({ text: 'Gwet\'s AC1 was 0.739 for invited experts (8 raters, 36 labels) and 0.623 for regular reviewers (14 raters, 68 labels) on 10 records; analytic lower bounds 0.402 and 0.252; the pre-registered two-part criterion (point estimate at least 0.61 and lower bound at least 0.41) was not met.',
    topic: 'RELIABILITY', type: 'NUMERICAL_RESULT', surface: 'PUBLIC_PAGE', evidence: 'EV-DETECTION-ARTICLE', at: 'Section 6.5, Table 3',
    population: '22 raters under the five-condition instrument (8 invited experts, 14 regular reviewers), 10 records with two or more raters, 104 labels after one label per rater per record (113 submitted)',
    quantities: { value: 'AC1 0.739 / 0.623', numerator: null, denominator: '10 records; 36 and 68 labels', denominator_required: true, unit: 'Gwet AC1' },
    date: 'data lock 2026-08-15',
    limitation: 'A separate, smaller sample from the detection panel. Interim: 10 records against a pooled target of about 26, wide intervals, and the pre-registered lower-bound criterion not met. Agreement is not correctness and not psychometric validation.',
    limitationKey: 'not met',
    permitted: 'In a separate reliability sample of 10 records, Gwet\'s AC1 was 0.739 for invited participants and 0.623 for open enrolment. Both exceed the 0.61 point floor, but neither analytic lower bound reaches 0.41, so the pre-registered criterion was not met.',
    prohibitedWording: ['reviewers reliably agree', 'substantial agreement', 'JRS is reliable', 'AC1 shows accuracy'],
    publicUse: 'MAY_STATE_HISTORIC_RESULT_WITH_LIMITATION', status: 'SUPPORTED_WITH_LIMITATION',
    figures: ['0\\.739', '0\\.74\\b', '0\\.623', '0\\.624', '0\\.63\\b', '0\\.61\\b', '0\\.41\\b', '0\\.402', '0\\.252', '0\\.427', '\\b22 raters\\b', '\\b104 (labels|determinations)\\b', '\\b113 (submitted )?(labels|determinations)\\b', '\\b10 (analysed |shared )?records\\b', '10-record', '\\b36 labels\\b', '\\b68 labels\\b'],
    signatures: ['0\\.739', '0\\.623', 'AC1'],
    qualifiers: [['ten-record sample', '\\b10 (analysed |shared )?records\\b|10-record|ten records|\\b10 records\\b'], ['criterion or interim status', 'not met|lower (confidence )?bound|\\b0\\.41\\b|[Ii]nterim|wide intervals']],
    prohibited: [['agreement labelled accuracy or validation', '(0\\.739|0\\.623|AC1)(?:[^.;()]|\\.(?=\\d)){0,40}\\b(accura\\w*|validat\\w*|substantial)\\b|\\b(accura\\w*|validat\\w*|substantial)\\b(?:[^.;()]|\\.(?=\\d)){0,40}(0\\.739|0\\.623)'], NOT_ENGINE] }),
  // ---- 3. cross-vendor model agreement --------------------------------------------------------------------
  c({ text: 'Across 61 recorded runs between 12 June and 21 August 2026, agreement across three vendor models ranged from 66.7 to 93.3 percent, mean 85.3 percent; the study closed on 21 August 2026.',
    topic: 'CROSS_MODEL', type: 'NUMERICAL_RESULT', surface: 'PUBLIC_PAGE', evidence: 'EV-STUDY001-RESOLUTION', at: '"What the authoritative tables say" and the 2026-09-20 corrected recommendation',
    population: 'three vendor models (Anthropic, OpenAI, Google), one model each; 61 recorded runs without a completeness filter (mixed denominators)',
    quantities: { value: '66.7 to 93.3 percent, mean 85.3 percent', numerator: null, denominator: '61 recorded runs (mixed record counts)', denominator_required: true, unit: 'raw pairwise agreement' },
    date: '2026-06-12 to 2026-08-21 (closed 2026-08-21)',
    limitation: 'Raw agreement among models, not accuracy, not human reliability and not independent validation. The pre-registered reproducibility criterion requires chance-corrected AC1, which was not computed, so it is not established. The 61 runs mix denominators. EV-FINAL-SWEEP reports the same series as 2026-06-13 to 2026-08-21, mean 0.849; the difference is not reconciled.',
    limitationKey: 'raw',
    permitted: 'Across 61 recorded runs between 12 June and 21 August 2026, raw agreement across three models ranged from 66.7 to 93.3 percent, mean 85.3 percent. This is consistency, not accuracy; the reproducibility criterion is not established because the required AC1 was not computed.',
    prohibitedWording: ['the AI is 85 percent accurate', 'models validate JRS', 'reproducibility established', 'independent validation by three AI vendors'],
    publicUse: 'MAY_STATE_HISTORIC_RESULT_WITH_LIMITATION', status: 'SOURCE_REPORTED_NOT_REPRODUCED',
    figures: ['66\\.7', '93\\.3', '85\\.3\\s?(%|percent)?', '\\b61 (recorded )?(mixed-denominator )?runs\\b', '\\b(three|3) (vendor )?models\\b'],
    signatures: ['66\\.7', '85\\.3'],
    qualifiers: [['61-run denominator', '\\b61 (recorded )?(mixed-denominator )?runs\\b'], ['raw agreement only', '\\braw\\b|not (accuracy|established)|consistenc|not computed']],
    prohibited: [['61-run range given a 15-record-window denominator', '(66\\.7|85\\.3)(?:(?!82\\.2)[^.]|\\.(?=\\d)){0,80}\\b(37|41) (dated |nightly )?runs\\b|\\b(37|41) (dated |nightly )?runs\\b(?:(?!82\\.2)[^.]|\\.(?=\\d)){0,80}(66\\.7|85\\.3)'], ['agreement labelled accuracy, reliability or validation', '(66\\.7|85\\.3)(?:[^.;()]|\\.(?=\\d)){0,60}\\b(accura\\w*|reliab\\w*|validat\\w*)\\b|\\b(accura\\w*|reliab\\w*|validat\\w*)\\b(?:[^.;()]|\\.(?=\\d)){0,40}(66\\.7|85\\.3)'], NOT_ENGINE] }),
  c({ text: 'Restricted to runs that returned every record, the range was 82.2 to 93.3 percent across 37 runs at the full 15-record set (series as read on 13 August 2026); at the 15 August 2026 data lock the same series held 41 nightly runs (29 June to 15 August), mean 87.2 percent.',
    topic: 'CROSS_MODEL', type: 'NUMERICAL_RESULT', surface: 'PUBLIC_PAGE', evidence: 'EV-DETECTION-ARTICLE', at: 'Appendix A (41 runs); EV-IP-AUDIT (37 runs, 2026-08-13); EV-STUDY001-RESOLUTION (correction of 2026-09-20)',
    population: 'three vendor models on a fixed 15-record constructed set',
    quantities: { value: '82.2 to 93.3 percent', numerator: null, denominator: '37 runs (as of 2026-08-13) or 41 runs (2026-06-29 to 2026-08-15); never 61', denominator_required: true, unit: 'raw pairwise agreement' },
    date: '37 runs: read 2026-08-13; 41 runs: data lock 2026-08-15',
    limitation: '37 and 41 runs are one series at two windows; 61 runs is that series without the completeness filter. None of the three counts is interchangeable with another, and neither window is the series at closure on 21 August 2026. Raw agreement only; not accuracy.',
    limitationKey: '15 records',
    permitted: 'Restricted to runs that returned all 15 records, raw agreement ranged from 82.2 to 93.3 percent across 37 runs (series as read on 13 August 2026).',
    prohibitedWording: ['82.2 to 93.3 percent across 61 runs', '82.2 to 93.3 percent at closure'],
    publicUse: 'MAY_STATE_HISTORIC_RESULT_WITH_LIMITATION', status: 'SOURCE_REPORTED_NOT_REPRODUCED',
    figures: ['82\\.2', '93\\.3', '87\\.2\\s?(%|percent)?', '\\b37 (dated )?(nightly )?runs\\b', '\\b41 (nightly )?runs\\b', '15-record', '\\b15 (constructed )?records\\b'],
    signatures: ['82\\.2'],
    qualifiers: [['37- or 41-run denominator', '\\b(37|41) (dated )?(nightly )?runs\\b', 'sentence'], ['15-record set', '15-record|15 records'], ['window date', '13 August|15 August|29 June', 'sentence']],
    prohibited: [['denominator swapped to 61 runs', '82\\.2(?:[^.]|\\.(?=\\d)){0,60}\\b61 (recorded )?runs'], ['agreement labelled accuracy or validation', '82\\.2(?:[^.;()]|\\.(?=\\d)){0,60}\\b(accura\\w*|validat\\w*)\\b|\\b(accura\\w*|validat\\w*)\\b(?:[^.;()]|\\.(?=\\d)){0,40}82\\.2'], NOT_ENGINE] }),
  c({ text: 'Earlier single-run cross-vendor figures (84 percent, 86.7 percent) were each published as the latest value.',
    topic: 'CROSS_MODEL', type: 'NUMERICAL_RESULT', surface: 'REPOSITORY_DOCUMENTATION', evidence: 'EV-STUDY001-RESOLUTION', at: '"The finding" and "Historical figures preserved"',
    population: 'single runs of the STUDY-001 series', quantities: { value: '84 / 86.7 percent', numerator: null, denominator: 'one run each (84 percent in 4 runs, 86.7 percent in 6 runs)', denominator_required: true, unit: 'raw agreement' },
    date: 'mid-study snapshots before 2026-08-21', limitation: 'Historical mid-study snapshots, superseded. Not current and not the series result.', limitationKey: 'historical',
    permitted: 'Historical: single runs earlier in the series read 84 percent and 86.7 percent; the series closed on 21 August 2026.',
    prohibitedWording: ['latest agreement 86.7 percent', 'cross-model agreement is 84 percent'],
    publicUse: 'HISTORICAL_CONTEXT_ONLY', status: 'HISTORICAL_ONLY',
    figures: ['\\b86\\.7\\s?(%|percent)', '\\b84\\s?(%|percent)'], signatures: ['\\b86\\.7\\s?(%|percent)', '\\b84\\s?(%|percent)'], qualifiers: [], prohibited: [] }),
  // ---- participation and geography ---------------------------------------------------------------------------
  c({ text: '58 distinct people took part across three studies (61 participations): a 16-member detection panel, a 25-rater reliability study and a 20-expert comparison study.',
    topic: 'PARTICIPATION', type: 'PARTICIPATION_COUNT', surface: 'PUBLIC_PAGE', evidence: 'EV-DETECTION-ARTICLE', at: 'Acknowledgments',
    population: 'detection panel (16), reliability study (25 raters), comparison study (20 experts); three people in two studies', quantities: { value: '58 people', numerator: null, denominator: 'three studies (61 participations)', denominator_required: false, unit: 'people' },
    date: 'manuscript 2026-08-29', limitation: 'Participation is acknowledgment, not a result. The detection finding rests on the 16 panel members only.', limitationKey: 'three studies',
    permitted: '58 international reviewers took part across three studies.', prohibitedWording: ['58 experts validated JRS', '58 reviewers confirmed the method'],
    publicUse: 'MAY_STATE_WITH_LIMITATION', status: 'SUPPORTED_WITH_LIMITATION',
    figures: ['\\b58 (international |distinct )?(reviewers|people|participants)\\b', '\\b61 participations\\b', '\\b25 raters\\b', '\\b20 (independent )?experts\\b'], signatures: ['\\b58 (international |distinct )?(reviewers|people)'],
    qualifiers: [['three studies', 'three studies']], prohibited: [['participation presented as validation', '\\b(validat\\w*|confirm\\w*|endors\\w*)\\b']] }),
  c({ text: '36 completers across both arms (16 detection-panel experts and 20 comparison-study experts) each completed the full 24-record set, spanning 16 countries on 5 continents.',
    topic: 'PARTICIPATION', type: 'PARTICIPATION_COUNT', surface: 'PUBLIC_PAGE', evidence: 'EV-TRACKER-COUNTRIES', at: 'tracker line "Combined: 16 countries across all 5 populated continents"; EV-DETECTION-ARTICLE Acknowledgments for the 16 and 20',
    population: '36 completers of the 24-record corpus across two arms', quantities: { value: '36 completers, 16 countries', numerator: null, denominator: 'two arms', denominator_required: false, unit: 'people' },
    date: 'completer geography as recorded in August 2026', limitation: 'A geography and participation count, not a result. The 16-country figure combines both arms; the detection panel alone spans 11 countries.', limitationKey: '24-record',
    permitted: '36 of them completed the full 24-record set, across 16 countries.', publicUse: 'MAY_STATE_WITH_LIMITATION', status: 'SUPPORTED_WITH_LIMITATION',
    figures: ['\\b36 (independent )?(experts|completers|reviewers|of them)\\b', '\\b16 countries\\b', '\\b5 continents\\b'], signatures: ['\\b36 (independent )?(experts|completers|of them)', '\\b16 countries\\b'],
    qualifiers: [['full 24-record set', '24-record|24 records']], prohibited: [['completers presented as validation', '\\b(validat\\w*|confirm\\w*)\\b']] }),
  c({ text: 'The detection panel was 16 reviewers in 11 countries on 5 continents.',
    topic: 'PARTICIPATION', type: 'PARTICIPATION_COUNT', surface: 'PUBLIC_PAGE', evidence: 'EV-DETECTION-ARTICLE', at: 'Section 4.5 (data lock 2026-08-15)',
    population: 'detection panel', quantities: { value: '16 reviewers, 11 countries', numerator: null, denominator: null, denominator_required: false, unit: 'people' },
    date: 'data lock 2026-08-15', limitation: 'Geography of the panel, not a result.', limitationKey: 'detection panel', permitted: 'The detection panel was 16 reviewers in 11 countries on 5 continents.', publicUse: 'MAY_STATE_WITH_LIMITATION', status: 'SUPPORTED_WITH_LIMITATION',
    figures: ['\\b11 countries\\b', '\\b5 continents\\b', '\\b16 (independent |detection-panel )?(experts|reviewers)\\b'], signatures: ['\\b11 countries\\b'], qualifiers: [], prohibited: [] }),
  // ---- condition behaviour, descriptive only -----------------------------------------------------------------
  c({ text: 'All five conditions separate a reconstructable record from an unreconstructable one, at p between 1.0e-08 and 1.5e-11 on 108 labels from 21 raters.',
    topic: 'CONDITION_BEHAVIOUR', type: 'NUMERICAL_RESULT', surface: 'PUBLIC_PAGE', evidence: 'EV-DETECTION-ARTICLE', at: 'Appendix B ("reported descriptively"); EV-FINAL-SWEEP DERIVATION TEST; EV-EMPLOYMENT-MANUSCRIPT',
    population: '108 labels from 21 raters', quantities: { value: 'p 1.0e-08 to 1.5e-11', numerator: null, denominator: '108 labels', denominator_required: true, unit: 'p-value' },
    date: 'data lock 2026-08-15',
    limitation: 'Circular: the overall determination is built from the five conditions, so their association with it is expected by construction and is not evidence that they discriminate. The 2026-08-29 manuscript moved this analysis to an appendix with inferential language removed; the sweep records the derivation as deterministic.',
    limitationKey: 'by construction',
    permitted: 'Because the overall determination is built from the five conditions, their association with it is expected by construction; the detection study reports it descriptively (Appendix B) and makes no discrimination claim from it.',
    prohibitedWording: ['the conditions discriminate at p < 1e-8', 'each condition independently predicts the outcome'],
    publicUse: 'MUST_NOT_STATE_AS_EVIDENCE', status: 'REQUIRES_WORDING_REPAIR',
    figures: ['1\\.0e-08', '1\\.5e-11', '\\b108 (labels|scored determinations|determinations)\\b', '\\b21 raters\\b'], signatures: ['1\\.0e-08', '1\\.5e-11'], qualifiers: [['circularity stated', 'by construction|circular|descriptiv']], prohibited: [] }),
  c({ text: 'Study 003 collected 108 scored determinations across 10 records, distributed Gap 69 percent, Needs work 18 percent, Ready 13 percent.',
    topic: 'CONDITION_BEHAVIOUR', type: 'NUMERICAL_RESULT', surface: 'PUBLIC_PAGE', evidence: 'EV-VALIDATION-REPORT', at: 'reliability section ("Across all determinations in this mode (108 labels)")',
    population: '108 labels on 10 constructed records', quantities: { value: 'Gap 69 / Needs work 18 / Ready 13 percent', numerator: null, denominator: '108 labels', denominator_required: true, unit: 'percent of labels' },
    date: 'undated report, earlier than 2026-08-29', limitation: 'A descriptive label distribution on a record set built to contain gaps; not a prevalence estimate.', limitationKey: '10 records',
    permitted: 'Study 003 recorded 108 determinations across 10 records: Gap 69 percent, Needs work 18 percent, Ready 13 percent.', publicUse: 'MAY_STATE_HISTORIC_RESULT_WITH_LIMITATION', status: 'SOURCE_REPORTED_NOT_REPRODUCED',
    figures: ['\\b69\\s?(%|percent)', '\\b18\\s?(%|percent)', '\\b13\\s?(%|percent)', '\\b108 (scored )?determinations\\b', '\\b10 records\\b'], signatures: ['Gap 69'], qualifiers: [['ten records', '10 records']], prohibited: [['distribution presented as prevalence', '\\b(prevalen\\w*|real[- ]world)\\b']] }),
  // ---- DRR study 014 -------------------------------------------------------------------------------------------
  c({ text: 'In Study 014, on 29 texts, a reader given only a summary answered 77 percent of masked factual questions correctly, against 97 percent from the original.',
    topic: 'DRR_STUDY', type: 'NUMERICAL_RESULT', surface: 'PUBLIC_PAGE', evidence: 'EV-CLAIM-RECONCILIATION', at: 'P-10 (verified against research/study-014-drr/RESULTS.md on branch claude/engine-eval-v8-2026-10-01)',
    population: '29 texts; the reader was a model (Sonnet 5.5), and only one model\'s concise summaries were tested', quantities: { value: '77 / 97 percent', numerator: null, denominator: '29 texts', denominator_required: true, unit: 'percent of masked questions answered correctly' },
    date: 'October 2026', limitation: 'The reader was an AI model, not a person, and only one model\'s summaries were tested. Research about AI drafting tools, not Engine output and not a DRR score.', limitationKey: 'AI reader',
    permitted: 'On 29 of those texts, an AI reader given only one model\'s concise summary answered 77 percent of masked factual questions correctly, against 97 percent from the original.',
    prohibitedWording: ['readers lose 20 percent of the facts', 'the Engine measures DRR at 77 percent'],
    publicUse: 'MAY_STATE_WITH_LIMITATION', status: 'REQUIRES_WORDING_REPAIR',
    figures: ['\\b29 (of those )?texts\\b', '\\b77\\s?(%|percent)', '\\b97\\s?(%|percent)'], signatures: ['\\b77\\s?(%|percent)'], qualifiers: [['the reader was a model', 'AI reader|model reader|a model|Sonnet']], prohibited: [NOT_ENGINE] }),
  // ---- 4 to 6. Engine development evidence ------------------------------------------------------------------------
  c({ text: 'Candidate quotations and anchors are checked to locate exact text in the source record; quotations the record does not contain are withheld.',
    topic: 'ENGINE_SOURCE_GROUNDING', type: 'CONTROL_STATEMENT', surface: 'REPOSITORY_DOCUMENTATION', evidence: 'EV-SOURCE-GROUNDING-TESTS', at: 'source-prep and packet anchor tests', reproduction: 'REPRODUCED_IN_REPOSITORY',
    population: 'constructed SYNTHETIC fixtures', date: '2026-10-06',
    limitation: 'Exact quotation presence is not semantic support: an anchor shows where text sits in the record, not that it supports the finding or that the finding is correct.', limitationKey: 'not semantic support',
    permitted: 'In local tests on constructed fixtures, each candidate quotation is checked to occur exactly in the record. This is not semantic support for the finding.',
    prohibitedWording: ['quotations prove the finding', 'source-grounded findings are correct', 'hallucination-free'], publicUse: 'INTERNAL_ONLY', status: 'SUPPORTED_WITH_LIMITATION', engine: 'ENGINE_DEVELOPMENT_ONLY',
    signatures: [], prohibited: [] }),
  c({ text: 'Each candidate result records the prompt version and hash, the adapter contract and the model identity, and every run in the repository uses a mock adapter.',
    topic: 'ENGINE_PROVENANCE', type: 'CONTROL_STATEMENT', surface: 'REPOSITORY_DOCUMENTATION', evidence: 'EV-PROMPT-PROVENANCE-TESTS', at: 'contract and candidate tests', reproduction: 'REPRODUCED_IN_REPOSITORY',
    population: 'mocked local runs', date: '2026-10-06', limitation: 'Provenance of a mocked local run. No provider was called; this says nothing about any real model\'s behaviour.', limitationKey: 'mock',
    permitted: 'In the repository, every candidate run uses a mock adapter, and each result records its prompt hash and adapter contract.', prohibitedWording: ['provider-verified', 'model behaviour tested'],
    publicUse: 'INTERNAL_ONLY', status: 'SUPPORTED_WITH_LIMITATION', engine: 'ENGINE_DEVELOPMENT_ONLY' }),
  c({ text: 'The local candidate was run with a mock adapter over a 15-record constructed development corpus (corpus 0.1.0).',
    topic: 'ENGINE_LOCAL_EVALUATION', type: 'DESCRIPTIVE', surface: 'REPOSITORY_DOCUMENTATION', evidence: 'EV-CANDIDATE-EVAL', at: 'label field', reproduction: 'REPRODUCED_IN_REPOSITORY',
    population: '15 constructed development records', quantities: { value: '15 records', numerator: null, denominator: '15 constructed records', denominator_required: true, unit: 'records' },
    date: 'candidate 0.5.0-local.1', limitation: 'Constructed-development evidence only, with a mock adapter: not a measure of accuracy, reliability or validity, and not evidence about any real model or real record.', limitationKey: 'mock',
    permitted: 'A local run with a mock adapter over 15 constructed development records; not a measure of accuracy, reliability or validity.',
    prohibitedWording: ['the Engine passed its evaluation', 'Engine accuracy on 15 records'], publicUse: 'INTERNAL_ONLY', status: 'SUPPORTED_WITH_LIMITATION', engine: 'ENGINE_DEVELOPMENT_ONLY' }),
  c({ text: '24 source-preparation regression cases were written before the first run, including hard cases where the heuristics are expected to be wrong.',
    topic: 'ENGINE_REGRESSION', type: 'DESCRIPTIVE', surface: 'REPOSITORY_DOCUMENTATION', evidence: 'EV-CANDIDATE-REGRESSION', at: 'status, material and cases fields', reproduction: 'REPRODUCED_IN_REPOSITORY',
    population: '24 constructed regression cases', quantities: { value: '24 cases', numerator: null, denominator: '24 cases', denominator_required: true, unit: 'cases' },
    date: 'set 0.1.0', limitation: 'Tests a deterministic checker on constructed text. Known divergences are recorded, not hidden. No model is involved.', limitationKey: 'constructed',
    permitted: '24 constructed regression cases test the deterministic source-preparation checker; known divergences are recorded.', publicUse: 'INTERNAL_ONLY', status: 'SUPPORTED_WITH_LIMITATION', engine: 'ENGINE_DEVELOPMENT_ONLY' }),
  // ---- 7. release-gate and route status ---------------------------------------------------------------------------------
  c({ text: 'Release gates: RG-1 BLOCKED, RG-2 BLOCKED, RG-3 NOT_ASSESSED, RG-4 BLOCKED, RG-5 BLOCKED; conclusion INCOMPLETE_GATES_OPEN.',
    topic: 'RELEASE_GATE', type: 'STATUS_STATEMENT', surface: 'REPOSITORY_DOCUMENTATION', evidence: 'EV-RELEASE-GATE-REPORT', at: 'gate summary table', reproduction: 'REPRODUCED_IN_REPOSITORY',
    date: '2026-10-06', limitation: 'No gate has passed; nothing is released.', limitationKey: 'BLOCKED',
    permitted: 'No release gate has passed: four are BLOCKED and one is NOT_ASSESSED.', prohibitedWording: ['the Engine passed its release gates', 'release-ready'],
    publicUse: 'MAY_STATE_WITH_LIMITATION', status: 'SUPPORTED_WITH_LIMITATION', engine: 'ENGINE_EVIDENCE_SEPARATE' }),
  c({ text: 'The public review routes refuse every submission with 503 and make no call to a model provider.',
    topic: 'ENGINE_ROUTE_STATUS', type: 'CONTROL_STATEMENT', surface: 'PUBLIC_PAGE', evidence: 'EV-ROUTE-TESTS', at: 'auth matrix and scripts/test_review_incomplete.mjs', reproduction: 'REPRODUCED_IN_REPOSITORY',
    date: '2026-10-06', limitation: 'The tests check repository code; that production serves the same bytes is verified separately by deploy-verify.', limitationKey: 'refuse',
    permitted: 'The review routes on this site refuse submissions and make no call to any model provider.', publicUse: 'MAY_STATE_WITH_LIMITATION', status: 'SUPPORTED_WITH_LIMITATION', engine: 'ENGINE_EVIDENCE_SEPARATE' }),
  // ---- 8. privacy, retention and security --------------------------------------------------------------------------------
  c({ text: 'Earlier implementations sent record text to a model provider, truncated it to 8,000 characters, used per-organisation tokens and kept stored model output for 90 days.',
    topic: 'PRIVACY_SECURITY', type: 'STATUS_STATEMENT', surface: 'PUBLIC_PAGE', evidence: 'EV-CLAIM-RECONCILIATION', at: 'P-1 and P-2, and the repaired history sections',
    date: 'before 2026-10-04', limitation: 'Historical: the data flow is no longer active. Whether stored output remains is NOT ESTABLISHED, and no deletion is asserted.', limitationKey: 'historical',
    permitted: 'Historical: an earlier implementation sent record text to a model provider; that data flow is no longer active.', prohibitedWording: ['record text is sent to Anthropic', 'kept for 90 days and then removed'],
    publicUse: 'HISTORICAL_CONTEXT_ONLY', status: 'HISTORICAL_ONLY', engine: 'ENGINE_EVIDENCE_SEPARATE',
    figures: ['\\b90 days\\b', '8,000 characters'], signatures: ['\\b90 days\\b', '8,000 characters'], qualifiers: [], prohibited: [] }),
  c({ text: 'Row-level security is enabled on these tables with no public read access.',
    topic: 'PRIVACY_SECURITY', type: 'CONTROL_STATEMENT', surface: 'PUBLIC_PAGE', evidence: 'EV-PRIVACY-PAGE', at: 'privacy.html section 4',
    date: 'page updated 2026-10-06', limitation: 'A website statement, not proof that a live control executes. B-013 records one table readable with the public key on 2026-09-15 (zero rows). No operator-control evidence exists (RG-2 BLOCKED).', limitationKey: 'operator',
    permitted: 'Not to be restated until operator-control evidence exists.', prohibitedWording: ['data is secure', 'no public access is possible'], publicUse: 'NOT_FOR_PUBLIC_RESTATEMENT', status: 'NOT_ASSESSED', engine: 'NOT_APPLICABLE',
    signatures: ['Row-level security is enabled'] }),
  // ---- 9. publication and editorial status ---------------------------------------------------------------------------------
  c({ text: 'CEP Magazine (SCCE) accepted "When the Record Cannot Speak for Itself" on 16 July 2026 for the November 2026 issue.',
    topic: 'PUBLICATION_STATUS', type: 'PUBLICATION_STATEMENT', surface: 'RESTRICTED_SURFACE', evidence: 'EV-CEP-FILE', at: 'file header',
    date: 'accepted 2026-07-16', limitation: 'The acceptance is stated in the author\'s file header; the editor\'s message is not in the repository. A practitioner magazine acceptance is not peer review of the research.', limitationKey: 'magazine',
    permitted: 'An article was accepted by CEP Magazine for its November 2026 issue (practitioner magazine).', prohibitedWording: ['peer-reviewed publication', 'published research validates JRS'],
    publicUse: 'INTERNAL_ONLY', status: 'SOURCE_REPORTED_NOT_REPRODUCED', engine: 'NOT_APPLICABLE' }),
  c({ text: '"PUBLICATION CONFIRMED = Journal of Business Ethics (2026-07-17)."',
    topic: 'PUBLICATION_STATUS', type: 'PUBLICATION_STATEMENT', surface: 'REPOSITORY_DOCUMENTATION', evidence: 'EV-TRACKER-JBE', at: 'tracker line of 2026-07-17',
    date: '2026-07-17', limitation: 'Historical tracker wording that names a target journal. It records no submission outcome and is not an acceptance.', limitationKey: 'target',
    permitted: 'Historical: the Journal of Business Ethics was chosen as the target venue on 17 July 2026.', prohibitedWording: ['published in the Journal of Business Ethics', 'accepted by the Journal of Business Ethics'],
    publicUse: 'INTERNAL_ONLY', status: 'HISTORICAL_ONLY', engine: 'NOT_APPLICABLE' }),
  c({ text: 'A submission to Corporate Compliance Insights received an editor reply on 28 August 2026 citing overlap and inviting a revised version with a different focus.',
    topic: 'PUBLICATION_STATUS', type: 'PUBLICATION_STATEMENT', surface: 'INTERNAL_ONLY', evidence: 'EV-CCI-RESPONSE', at: 'editor reply',
    date: '2026-08-28', limitation: 'An editor reply inviting a revision; not an acceptance.', limitationKey: 'not an acceptance',
    permitted: 'Internal: an editor reply invited a revised version; this is not an acceptance.', publicUse: 'INTERNAL_ONLY', status: 'SUPPORTED_WITH_LIMITATION', engine: 'NOT_APPLICABLE' }),
  // ---- 10. research and Engine status, and what must not be claimed -------------------------------------------------------------
  c({ text: 'Nothing on this page is presented as validated. The programme is in its operational validation phase.',
    topic: 'RESEARCH_STATUS', type: 'STATUS_STATEMENT', surface: 'PUBLIC_PAGE', evidence: 'EV-HANDOFF', at: 'research-summary.html; the handoff position that general-purpose validation is not established',
    date: '2026-10-06', limitation: '"Operational validation phase" names a research stage. It does not mean that any validation is complete, and it says nothing about the Engine.', limitationKey: 'nothing on this page is presented as validated',
    permitted: 'Nothing on this page is presented as validated; the research programme is ongoing.', publicUse: 'MAY_STATE_WITH_LIMITATION', status: 'NOT_ASSESSED',
    signatures: ['operational validation phase'] }),
  c({ text: 'The Review Engine is production-ready, independently validated, licensing-ready, sale-ready, compliant, defensible or enterprise-ready.',
    topic: 'ENGINE_STATUS', type: 'PROHIBITED_CLAIM', surface: 'PUBLIC_PAGE', evidence: 'EV-NONE', at: 'none',
    limitation: 'No evidence supports any of these. Every release gate is closed, and the handoff describes the Engine as a controlled local-development candidate.', limitationKey: 'not',
    permitted: 'The Review Engine is a controlled local-development candidate. It is not validated and not available for use.', prohibitedWording: ['production-ready', 'independently validated', 'licensing-ready', 'sale-ready', 'compliant', 'defensible', 'enterprise-ready'],
    publicUse: 'MUST_NOT_STATE', status: 'NOT_SUPPORTED', engine: 'ENGINE_EVIDENCE_SEPARATE' }),
  c({ text: 'JRS research findings validate the Review Engine.',
    topic: 'ENGINE_STATUS', type: 'PROHIBITED_CLAIM', surface: 'PUBLIC_PAGE', evidence: 'EV-NONE', at: 'none',
    limitation: 'The research measured human reviewers and model consistency on constructed records. It is not evidence about the Engine.', limitationKey: 'not',
    permitted: 'The research concerns the JRS methodology. It does not validate the Engine.', prohibitedWording: ['the Engine is backed by 83.9 percent accuracy', 'validated by our research'],
    publicUse: 'MUST_NOT_STATE', status: 'NOT_SUPPORTED', engine: 'ENGINE_EVIDENCE_SEPARATE' }),
  c({ text: 'The JRS methodology is validated (generally, independently or psychometrically).',
    topic: 'METHODOLOGY', type: 'PROHIBITED_CLAIM', surface: 'PUBLIC_PAGE', evidence: 'EV-NONE', at: 'none',
    limitation: 'Not established: the five conditions are not psychometrically validated, the reliability criterion was not met, and the detection result is on constructed records only.', limitationKey: 'not',
    permitted: 'The research reports specific results with their limitations; it does not establish general validation.', prohibitedWording: ['validated standard', 'scientifically validated', 'independently validated method'],
    publicUse: 'MUST_NOT_STATE', status: 'NOT_SUPPORTED' }),
  c({ text: 'JRS or the Review Engine is available for licensing, sale or acquisition.',
    topic: 'COMMERCIAL', type: 'PROHIBITED_CLAIM', surface: 'PUBLIC_PAGE', evidence: 'EV-HANDOFF', at: 'current operative position (no licensing, sale or acquisition pathway)',
    limitation: 'The handoff closes every licensing, integration and acquisition pathway; no offer exists. Rights and title are not established (CLAUDE.md Rules 4 to 8).', limitationKey: 'no licensing',
    permitted: 'No licensing, sale or acquisition pathway is offered.', prohibitedWording: ['licensing-ready', 'sale-ready', 'available for licensing'],
    publicUse: 'MUST_NOT_STATE', status: 'NOT_SUPPORTED', engine: 'NOT_APPLICABLE' }),
  c({ text: 'The Manifest schema and library have passed repository conformance and integrity tests.',
    topic: 'MANIFEST', type: 'CONTROL_STATEMENT', surface: 'PUBLIC_PAGE', evidence: 'EV-MANIFEST-TESTS', at: 'tests/manifest/run.mjs', reproduction: 'REPRODUCED_IN_REPOSITORY',
    date: '2026-10-06', limitation: 'Schema and integrity tests on fixtures. They do not validate the Engine, and a valid hash shows internal consistency, not authenticity.', limitationKey: 'Engine remains unvalidated',
    permitted: 'The Manifest schema and library have passed repository conformance and integrity tests. The Engine remains unvalidated.', publicUse: 'MAY_STATE_WITH_LIMITATION', status: 'SUPPORTED_WITH_LIMITATION', engine: 'ENGINE_EVIDENCE_SEPARATE' }),
  c({ text: 'Procedural quantities in implementation guidance (for example, a first pass on 3 to 5 records, groups of 1 to 5 reviewers, a minimum of 10 records per record type per quarter).',
    topic: 'PROCEDURAL_GUIDANCE', type: 'DESCRIPTIVE', surface: 'PUBLIC_PAGE', evidence: 'EV-NONE', at: 'implementation-scenarios.html, workflow-fit.html, jrsstandard.html',
    limitation: 'Guidance quantities, not research findings. No study in the repository measured them; "First gaps visible in 1-3 records" reads as an empirical claim and is not assessed.', limitationKey: 'guidance',
    permitted: 'Guidance: start with a small number of records before expanding.', publicUse: 'MAY_STATE_WITH_LIMITATION', status: 'NOT_ASSESSED', engine: 'NOT_APPLICABLE',
    figures: ['\\b\\d+-\\d+ (records|reviewers)\\b', '\\b\\d+ records per record type\\b', '\\b(3|5) records\\b', '\\b(1|5) reviewers\\b'], signatures: ['\\b\\d+-\\d+ (records|reviewers)\\b', 'records per record type'] }),
  c({ text: 'An exploratory crossed mixed-effects logistic model over all 384 graded reads places an average reviewer on an average record at 89.2 percent; reviewer SD 1.769 (profile interval 1.292 to 3.000); record SD 0.011 at the boundary (profile interval 0.001 to 0.556); latent-scale ICC 0.488 for reviewers and 0.0000 for records.',
    topic: 'DETECTION', type: 'NUMERICAL_RESULT', surface: 'PUBLIC_PAGE', evidence: 'EV-DETECTION-ARTICLE', at: 'Appendix C, "What this answers" and "The record component is estimated at the boundary"',
    population: '384 graded reads from 16 reviewers on 24 constructed records', quantities: { value: '89.2 percent intercept', numerator: null, denominator: '384 graded reads', denominator_required: true, unit: 'model-estimated accuracy' },
    date: 'data lock 2026-08-15', limitation: 'Exploratory, added after pre-registration. The record component is weakly identified and must not be read as zero. Constructed corpus only.', limitationKey: 'exploratory',
    permitted: 'An exploratory crossed model over the 384 graded reads on the constructed corpus places an average reviewer on an average record at 89.2 percent; the record component is weakly identified.',
    prohibitedWording: ['records do not differ in difficulty', 'JRS is 89 percent accurate'], publicUse: 'MAY_STATE_HISTORIC_RESULT_WITH_LIMITATION', status: 'SUPPORTED_WITH_LIMITATION',
    figures: ['89\\.2\\s?(%|percent)?', '\\b0\\.011\\b', '\\b0\\.001\\b', '\\b0\\.556\\b', '\\b0\\.488\\b', '\\b384 graded reads\\b'], signatures: ['89\\.2', '0\\.488', '1\\.769'],
    qualifiers: [['exploratory status', '[Ee]xploratory']], prohibited: [NOT_ENGINE] }),
  c({ text: 'The methods paper download states that independent reviewers reached substantial agreement (AC1 0.74 experts, 0.63 trained reviewers, 10 records), that cross-vendor AI agreement averaged 84 percent across 15 constructed records, and that the findings support reproducible application and substantial inter-rater reliability.',
    topic: 'RELIABILITY', type: 'NUMERICAL_RESULT', surface: 'PUBLIC_DOWNLOAD', evidence: 'EV-METHODS-PDF', at: 'Abstract, "Results and interpretation"; repeated in the results tables',
    population: '10 records (reliability); 15 constructed records (cross-vendor)', quantities: { value: 'AC1 0.74 / 0.63; 84 percent', numerator: null, denominator: '10 records; 15 constructed records', denominator_required: true, unit: 'AC1; raw agreement' },
    date: 'draft, cross-vendor figure as of 2026-07-06', limitation: 'Superseded. The 2026-08-29 manuscript reports the pre-registered two-part reliability criterion not met and drops "substantial"; the cross-vendor series closed with 61 runs and its reproducibility criterion is not established. "Reproducible application" is therefore not supported.', limitationKey: 'superseded',
    permitted: 'Historical draft, superseded: it reported AC1 0.74 and 0.63 on 10 records and cross-vendor agreement of 84 percent on 15 constructed records; the current results are in the 29 August 2026 manuscript.',
    prohibitedWording: ['substantial agreement', 'support reproducible application', 'substantial inter-rater reliability'], publicUse: 'HISTORICAL_CONTEXT_ONLY', status: 'REQUIRES_WORDING_REPAIR' }),
];

// ---- 2026-10-06: public wording repaired on the draft branch (owner repair authorization) ----------
// Each entry adds a review-history line naming the pages and repairs; the scanner confirms the old
// issue is absent before a repair is recorded as implemented (tools/claim-provenance/lib/repairs.js).
// Statuses change only where the claim itself changed standing; nothing is deleted.
const REPAIRED = {
  'CL-001': ['research.html, research-summary.html (body, meta, Open Graph, Twitter and structured data), engagement.html, reviewer/index.html', 'PR-01, PR-03, PR-06, PR-08, PR-09, PR-11, PR-14, PR-19 to PR-22, PR-28'],
  'CL-004': ['research.html, check.html, reviewer/index.html', 'PR-02, PR-06, PR-12, PR-25 (current population labels: invited / open enrolment)'],
  'CL-005': ['reviewer/index.html, research.html', 'PR-15, PR-18'],
  'CL-006': ['research.html, reviewer/index.html', 'PR-04, PR-06, PR-07, PR-16, PR-18 (the 37-run figure now carries its 13 August 2026 window)'],
  'CL-032': ['research-summary.html', 'PR-10, PR-17'],
  'CL-031': ['implementation-scenarios.html, workflow-fit.html', 'PR-26, PR-27 (guidance worded as guidance)'],
};
const STATUS_CHANGE = {
  'CL-011': ['RETIRED', 'Retired as a public claim: research.html no longer presents the circular condition-separation p-values (PR-05). The record stays so the scanner flags any reintroduction.'],
  'CL-013': ['SOURCE_REPORTED_NOT_REPRODUCED', 'Wording repaired on decision-reconstruction-risk.html (PR-13): the reader is named as an AI reader. The figures remain source-reported.'],
  'CL-025': ['RETIRED', 'Retired: research-summary.html no longer calls the programme an "operational validation phase" (PR-23, PR-24).'],
  'CL-033': ['HISTORICAL_ONLY', 'Supersession notice in place (PD-01): methods-paper-notice.html; research.html and research-summary.html link to the notice, and the PDF is unchanged.'],
};
export const CLAIMS = Object.freeze(BASE.map((c) => {
  const out = { ...c, review_history: [...c.review_history] };
  if (REPAIRED[c.claim_id]) out.review_history.push({ date: '2026-10-06', change: 'Public wording repaired on the draft branch: ' + REPAIRED[c.claim_id][0] + ' (' + REPAIRED[c.claim_id][1] + '). The scanner confirms the old issue is absent. Not published until the owner approves a merge.' });
  if (STATUS_CHANGE[c.claim_id]) { out.status = STATUS_CHANGE[c.claim_id][0]; out.review_history.push({ date: '2026-10-06', change: STATUS_CHANGE[c.claim_id][1] }); }
  return out;
}));
