// Claim provenance: Markdown renderers for the register, the limitation matrix and the claim cards.
// INTERNAL, LOCAL ONLY. Deterministic: the same register always renders the same text.
import { CATEGORIES } from './categories.js';

const cell = (s) => String(s === null || s === undefined ? '' : s).replace(/\|/g, '\\|').replace(/\n/g, ' ');
const table = (head, rows) => '| ' + head.join(' | ') + ' |\n|' + head.map(() => '---').join('|') + '|\n' + rows.map((r) => '| ' + r.map(cell).join(' | ') + ' |').join('\n') + '\n';
const shortHash = (h) => (h ? h.split(':')[0] + ':' + h.split(':')[1].slice(0, 12) : 'none');
export const ENGINE_SEPARATION = 'Research about JRS is not evidence about the Review Engine. Nothing in this card may be cited as Engine evidence, and no Engine claim may borrow its figures.';
const STANDING = '**Internal, generated, not deployed.** An internal claim-control system. It does not validate the research, the Engine, privacy controls, commercial readiness or production use.';

export function renderRegisterMd(reg) {
  const topics = [...new Set(reg.claims.map((c) => c.claim_topic))];
  return '# Claim-Evidence Register\n\n' + STANDING + ' Generated by `tools/claim-provenance/build.mjs` from `tools/claim-provenance/lib/claims.js` and `lib/evidence.js`. Machine form: `tools/claim-provenance/current-claim-evidence-register.json`. Record schema: `' + reg.record_schema + '`. Do not edit by hand.\n\n'
    + '## Status summary\n\n' + table(['Status', 'Claims'], Object.entries(reg.status_summary)) + '\nTotal: ' + reg.claim_count + ' claims. Claims digest `' + reg.claims_digest + '`.\n'
    + '\n## Evidence sources\n\n' + table(['ID', 'Path', 'Binding', 'Reviewed sha256', 'Class', 'Level', 'What it measures'], reg.evidence.map((e) => [e.id, e.path ? '`' + e.path + '`' : 'none', e.binding, e.reviewed_hash ? '`' + e.reviewed_hash.slice(0, 16) + '…`' : 'none', e.evidence_class, e.level, e.measures]))
    + topics.map((t) => '\n## ' + t + '\n\n' + reg.claims.filter((c) => c.claim_topic === t).map((c) => '### ' + c.claim_id + ' · ' + c.status + '\n\n'
      + '- **Claim:** ' + c.claim_text + '\n'
      + '- **Evidence:** ' + c.evidence_id + (c.source_path ? ' (`' + c.source_path + '`, ' + c.source_location + ', ' + shortHash(c.source_hash) + ')' : ' (none)') + '; class ' + c.evidence_class + '; ' + c.reproduction + '.\n'
      + (c.population ? '- **Measured population or corpus:** ' + c.population + '\n' : '')
      + (c.quantities ? '- **Quantities:** ' + c.quantities.value + '; denominator: ' + (c.quantities.denominator || 'none') + (c.quantities.denominator_required ? ' (required)' : '') + '\n' : '')
      + (c.date_or_data_lock ? '- **Date or data lock:** ' + c.date_or_data_lock + '\n' : '')
      + '- **Limitation:** ' + c.limitation + '\n'
      + '- **Permitted wording:** ' + c.permitted_wording + '\n'
      + (c.prohibited_overstatement.length ? '- **Prohibited overstatement:** ' + c.prohibited_overstatement.map((w) => '"' + w + '"').join('; ') + '\n' : '')
      + '- **Public use:** ' + c.public_use + ' · **Surface:** ' + c.surface + ' · **Engine relationship:** ' + c.engine_relationship + '\n').join('\n')).join('');
}

export function renderMatrix(reg) {
  return '# Public-Claim Limitation Matrix\n\n' + STANDING + ' Generated by `tools/claim-provenance/build.mjs` from `lib/categories.js`. Do not edit by hand.\n\n'
    + '**Two different permissions.** "May state a factual historic result" means a dated result may be reported with its sample, window and limitation. "May market a current capability" would mean presenting it as something JRS or the Engine does now. No research category below permits the second.\n\n'
    + table(['Claim category', 'What may be said', 'What must accompany it', 'What must not be said', 'Historic result or current capability'], CATEGORIES.map((c) => [c.title, c.may_say, c.must_accompany, c.must_not, c.market]))
    + '\nClaim cards for each category: `docs/architecture/claim-cards/`. Claims behind each category: `CLAIM_EVIDENCE_REGISTER.md`.\n';
}

export function renderCards(reg) {
  const out = {};
  for (const cat of CATEGORIES) {
    const claims = reg.claims.filter((c) => cat.topics.includes(c.claim_topic));
    const engine = claims.length && claims.every((c) => c.engine_relationship !== 'NO_ENGINE_INFERENCE') ? 'This card is about Engine development or status. It is not research evidence, and research evidence is not Engine evidence.' : ENGINE_SEPARATION;
    out[cat.id + '.md'] = '# Claim card: ' + cat.title + '\n\n**Internal drafting control, generated, not public copy.** Generated by `tools/claim-provenance/build.mjs`. Do not edit by hand.\n\n'
      + '- **Approved factual short form:** ' + cat.short_form + '\n'
      + '- **Required limitation:** ' + cat.must_accompany + '\n'
      + '- **Prohibited shorthand:** ' + cat.prohibited_shorthand.map((w) => '"' + w + '"').join('; ') + '\n'
      + '- **Historic result or current capability:** ' + cat.market + '\n'
      + '- **Engine separation:** ' + engine + '\n\n'
      + '## Evidence and status\n\n' + (claims.length ? table(['Claim', 'Status', 'Evidence', 'Last reviewed source hash'], claims.map((c) => [c.claim_id, c.status, c.evidence_id + (c.source_path ? ' (`' + c.source_path + '`)' : ''), shortHash(c.source_hash)])) : 'No register claim in this category yet.\n')
      + '\n' + claims.map((c) => '- **' + c.claim_id + ' permitted wording:** ' + c.permitted_wording).join('\n') + '\n';
  }
  return out;
}
