// JRS frozen synthetic demonstration: renders the committed outputs from one replay.
// LOCAL ONLY. Pure: the same replay, manifest and evidence record always give the same bytes.
//   generated/replay-output.json   the full replay: results, packets and the disposition examples
//   viewer/demo-data.js            the read-only data the local viewer shows (SYNTHETIC)
export const OUTPUT_PATHS = Object.freeze({ replay: 'tools/frozen-demo/generated/replay-output.json', viewer: 'tools/frozen-demo/viewer/demo-data.js' });

const NOTICE = 'SYNTHETIC DEMONSTRATION DATA. Fictional organisations, people, dates and facts. Pre-generated by the local candidate with a scripted mock adapter. No live model was run.';

function viewerCase(c, record) {
  const res = c.result, ctx = res.contextual_findings;
  return {
    record_id: c.record_id, record_version: c.record_version, record_ref: c.record_ref, demonstrates: c.demonstrates, summary: record.summary,
    source_sha256: c.source_sha256, text: record.text, fictional_entities: record.fictional_entities,
    source_preparation: { version: c.source_preparation.version, refusal: c.source_preparation.refusal,
      findings: c.source_preparation.findings.map((f) => ({ kind: f.kind, code: f.code, element: f.element || null, matched: f.matched || null, detail: f.detail || null, location: f.location || null })),
      quotations: c.source_preparation.quotations },
    candidate: { status: res.status, reason: res.reason, detail: res.detail, adapter_calls: c.adapter_calls, adapter_identity: c.adapter_identity,
      conditions: ctx ? ctx.conditions : null,
      findings: ctx ? ctx.findings.map((f) => ({ id: f.id, kind: f.kind, condition: f.condition || null, status: f.status || null, type: f.type || null, quotation: f.quotation || null,
        locations: f.locations || null, note: f.kind === 'flaw' ? f.model_note : f.note, uncertain: f.uncertain, explanation_label: f.explanation ? f.explanation.label : null })) : [],
      extraction_findings: res.extraction_findings.map((f) => ({ id: f.id, origin: f.origin, code: f.code, element: f.element || null })) },
    scope_probes: c.scope_probes,
    packet: c.packet,
    digests: c.digests,
    human_disposition_example: c.human_disposition_example,
    expected: record.expected,
    does_not_establish: record.limitations,
  };
}

export function renderOutputs(replay, manifest, evidence) {
  const data = {
    notice: NOTICE,
    package: { package_id: manifest.package_id, package_version: manifest.package_version, status: manifest.status, candidate_version: manifest.candidate_version,
               prompt_version: manifest.prompt_version, prompt_sha256: manifest.prompt_sha256, adapter: manifest.adapter, source_commit: manifest.source_commit, corpus_commit: manifest.corpus_commit },
    manifest_check: { status: manifest.status, records: manifest.records.map((m) => ({ record_id: m.record_id, record_version: m.record_version, source_sha256: m.source_sha256, expected_digests: m.expected_digests })) },
    scope_and_limitations: { scope: 'Completed, non-HR supplier-access exception drafts only. Employment, housing, lending, insurance, medical and legal-outcome content is excluded.',
                             limitations: manifest.known_limitations },
    evidence_statements: evidence.statements || null,
    cases: replay.cases.map((c) => viewerCase(c, c._record)),
  };
  const replayOut = { notice: NOTICE, ...replay };
  return {
    [OUTPUT_PATHS.replay]: JSON.stringify(replayOut, null, 1) + '\n',
    [OUTPUT_PATHS.viewer]: '// GENERATED by tools/frozen-demo/run-demo.mjs. Do not edit by hand.\n'
      + '// SYNTHETIC DEMONSTRATION DATA: fictional records, scripted mock-adapter output. No live model was run.\n'
      + 'export const FROZEN_DEMO = ' + JSON.stringify(data, null, 1) + ';\n',
  };
}
