// GENERATED by tools/methodology-integrity/build.mjs from tools/methodology-integrity/current-correspondence-register.json.
// Do not edit by hand. A mapped label renders only from an owner-approved record with its source
// hash and approval date; every other term renders the unmapped notice. Register records digest:
// e245e0a316aa62570bbd640d0b721148ef27b7695b79d5722b46bfd67d3ec6a9
export const NO_CORRESPONDENCE = 'No Codebook correspondence asserted.';
export const APPROVED_CORRESPONDENCE = Object.freeze([]);
export function resolveCodebookLabel(approved, category, term) {
  var NONE = 'No Codebook correspondence asserted.';
  var hits = (Array.isArray(approved) ? approved : []).filter(function (x) { return x && x.term_category === category && x.candidate_term === term; });
  if (hits.length !== 1) return { asserted: false, text: NONE };
  var r = hits[0];
  if (r.status !== 'APPROVED_CORRESPONDENCE' || !/^[0-9a-f]{64}$/.test(r.methodology_source_sha256 || '') || !/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(r.approval_date || '')
      || !r.authoritative_source_term || !r.methodology_source_id || !r.source_version) return { asserted: false, text: NONE };
  return { asserted: true, text: 'Owner-approved correspondence: ' + r.authoritative_source_term + ' (' + r.methodology_source_id + ', ' + r.source_version
    + ', source hash ' + r.methodology_source_sha256.slice(0, 12) + ', owner approval ' + r.approval_date + ').' };
}
export function codebookCorrespondenceText(category, term) { return resolveCodebookLabel(APPROVED_CORRESPONDENCE, category, term).text; }
