// GENERATED by tools/local-reviewer-workspace/make-demo-packet.mjs. Do not edit by hand.
// SYNTHETIC DEMONSTRATION PACKET: a constructed record of fictional people (tests/engine-candidate/fixtures/SYNTHETIC-SAE-03-GAPS.txt)
// reviewed by the candidate's mock adapter. Not a real record and not a real model output.
export const SYNTHETIC_DEMO_NOTICE = 'SYNTHETIC DEMONSTRATION PACKET. Constructed record, fictional people, mocked model output. Not a real record.';
export const SYNTHETIC_DEMO_PACKET = {
 "packet_version": "jrs-candidate-reviewer-packet/0.1.0",
 "status": {
  "human_review_required": true,
  "standing": "LOCAL CANDIDATE, NOT VALIDATED",
  "notice": "Produced by a local development candidate with a mocked model. It is not a decision, not a validation and not an approval. A person must read the record and every item below."
 },
 "review_identity": {
  "contract_version": "jrs-candidate-result/0.3.0",
  "candidate_version": "0.5.0-local.1",
  "source_prep_version": "source-prep/0.3.0",
  "explanation_set_version": "explanations/0.2.0",
  "prompt_sha256": "fabccb9760c06055c8415c76d12df1e38625bff08c610fdc0c14c0a839d8d8a7",
  "prompt_version": "candidate-prompt/0.4.0",
  "adapter_contract": "jrs-candidate-adapter-output/0.1.0",
  "model": "mock-demo@synthetic",
  "derived_from": "d2da83c:api/review-engine.js (0.1.0-validation)",
  "review_id": "db886454f21870f7a8f4ce7d"
 },
 "result_digest": "92af2fdbc92b45f3bd945aaf9fe17046b99d7b5165c62b642d2ebb9efaf3a5ef",
 "record_ref": "SYNTHETIC-DEMO-SAE-03",
 "source_preparation": {
  "version": "source-prep/0.3.0",
  "result_status": "examined",
  "reason": null,
  "detail": null,
  "refusal_codes": [],
  "source": {
   "sha256": "23d1fa4abeb26ba997b3ca7ca7ec720d796cd1f670766df0367392b8352a5236",
   "chars": 558,
   "lines": 8
  }
 },
 "deterministic_findings": [
  {
   "id": "X-001",
   "kind": "omission",
   "code": "placeholder",
   "element": null,
   "detail": null,
   "explanation": {
    "label": "Placeholder left in the record",
    "meaning": "The record contains a placeholder where content was meant to go.",
    "look_for": null,
    "reviewer_question": "Is the placeholder meant to be filled before the record is complete?",
    "category": null,
    "codebook_correspondence": "not_asserted"
   },
   "disposition": {
    "status": "pending",
    "history": []
   },
   "quotation": "[TBD]",
   "anchor": {
    "start": 551,
    "end": 556,
    "line": 7,
    "column": 109
   }
  },
  {
   "id": "X-002",
   "kind": "omission",
   "code": "referenced_material_not_in_record",
   "element": null,
   "detail": null,
   "explanation": {
    "label": "Referenced material not in the record",
    "meaning": "The record points to an attachment, exhibit or appendix that is not part of the text examined.",
    "look_for": null,
    "reviewer_question": "Is the referenced material part of the record a later reader will have?",
    "category": null,
    "codebook_correspondence": "not_asserted"
   },
   "disposition": {
    "status": "pending",
    "history": []
   },
   "quotation": "See attached",
   "anchor": {
    "start": 419,
    "end": 431,
    "line": 6,
    "column": 71
   }
  },
  {
   "id": "X-003",
   "kind": "omission",
   "code": "profile_element_not_found",
   "element": "exception_basis",
   "detail": "No stated basis for the exception was found. (Heuristic presence check: a missing match is not proof of omission.)",
   "explanation": {
    "label": "Expected element not found",
    "meaning": "A supplier-access exception record usually states this element, and no match was found. This is a pattern check, not proof of omission.",
    "look_for": null,
    "reviewer_question": "Does the record state this element in words the check did not recognise, or is it absent?",
    "category": null,
    "codebook_correspondence": "not_asserted"
   },
   "disposition": {
    "status": "pending",
    "history": []
   },
   "anchor_note": "This finding concerns something absent from the record, so there is no quotation to anchor."
  },
  {
   "id": "X-004",
   "kind": "unsupported_content",
   "code": "off_record_reference",
   "element": null,
   "detail": null,
   "explanation": {
    "label": "Reference to something off the record",
    "meaning": "The record relies on a conversation, call or agreement that is not itself recorded.",
    "look_for": null,
    "reviewer_question": "Is what was said or agreed written down anywhere a later reader can see?",
    "category": null,
    "codebook_correspondence": "not_asserted"
   },
   "disposition": {
    "status": "pending",
    "history": []
   },
   "quotation": "As discussed",
   "anchor": {
    "start": 296,
    "end": 308,
    "line": 5,
    "column": 147
   }
  },
  {
   "id": "X-005",
   "kind": "unsupported_content",
   "code": "assertion_without_basis",
   "element": null,
   "detail": null,
   "explanation": {
    "label": "Assertion presented as self-evident",
    "meaning": "The record uses wording that presents a point as obvious instead of showing its basis.",
    "look_for": null,
    "reviewer_question": "Is the basis for this point shown in the record?",
    "category": null,
    "codebook_correspondence": "not_asserted"
   },
   "disposition": {
    "status": "pending",
    "history": []
   },
   "quotation": "clearly",
   "anchor": {
    "start": 489,
    "end": 496,
    "line": 7,
    "column": 47
   }
  }
 ],
 "model_findings": {
  "origin": "mocked model (local candidate adapter)",
  "conditions": {
   "basis_identification": {
    "status": "review",
    "note": "The record states this only in part.",
    "uncertain": false
   },
   "reasoning_traceability": {
    "status": "review",
    "note": "The record states this only in part.",
    "uncertain": false
   },
   "temporal_reconstructability": {
    "status": "review",
    "note": "The record states this only in part.",
    "uncertain": false
   },
   "accountability_support": {
    "status": "review",
    "note": "The record states this only in part.",
    "uncertain": false
   },
   "cold_reviewer_clarity": {
    "status": "review",
    "note": null,
    "uncertain": false
   }
  },
  "findings": [
   {
    "id": "C-001",
    "kind": "condition",
    "explanation_id": "missing_identifiable_basis",
    "uncertain": false,
    "explanation": {
     "label": "Missing identifiable basis",
     "meaning": "A conclusion is stated, but the record does not identify what it rests on.",
     "look_for": "The document, observation, rule or fact the conclusion relies on, named in the record.",
     "reviewer_question": "Can the basis for this conclusion be pointed to in the record itself?",
     "category": "missing_identifiable_basis",
     "codebook_correspondence": "not_asserted"
    },
    "disposition": {
     "status": "pending",
     "history": []
    },
    "condition": "basis_identification",
    "condition_status": "review",
    "model_note": "The record states this only in part.",
    "anchor_note": "A candidate key concerns the record as a whole; quotations, if any, are on the flaw findings. A quotation shows presence in the record, not support."
   },
   {
    "id": "C-002",
    "kind": "condition",
    "explanation_id": "missing_logical_bridge",
    "uncertain": false,
    "explanation": {
     "label": "Missing logical bridge",
     "meaning": "The record states facts and a conclusion, but not the step that connects them.",
     "look_for": "A sentence that says why the stated facts lead to the conclusion reached.",
     "reviewer_question": "Could a later reader explain, from the record alone, how the facts led to the conclusion?",
     "category": "missing_logical_bridge",
     "codebook_correspondence": "not_asserted"
    },
    "disposition": {
     "status": "pending",
     "history": []
    },
    "condition": "reasoning_traceability",
    "condition_status": "review",
    "model_note": "The record states this only in part.",
    "anchor_note": "A candidate key concerns the record as a whole; quotations, if any, are on the flaw findings. A quotation shows presence in the record, not support."
   },
   {
    "id": "C-003",
    "kind": "condition",
    "explanation_id": "chronology_gap",
    "uncertain": false,
    "explanation": {
     "label": "Chronology gap",
     "meaning": "The order or timing of events cannot be rebuilt from the dates the record gives.",
     "look_for": "A date or interval for each step, and steps given in an order that matches those dates.",
     "reviewer_question": "Could a later reader put every step in order, with dates, from the record alone?",
     "category": "chronology_gap",
     "codebook_correspondence": "not_asserted"
    },
    "disposition": {
     "status": "pending",
     "history": []
    },
    "condition": "temporal_reconstructability",
    "condition_status": "review",
    "model_note": "The record states this only in part.",
    "anchor_note": "A candidate key concerns the record as a whole; quotations, if any, are on the flaw findings. A quotation shows presence in the record, not support."
   },
   {
    "id": "C-004",
    "kind": "condition",
    "explanation_id": "accountability_support",
    "uncertain": false,
    "explanation": {
     "label": "Recorded accountability (candidate-internal, unmapped)",
     "meaning": "The model judged that the record may not show who made, approved or is answerable for each step, or on what recorded material. This is a candidate key, not a JRS condition: it has no established Codebook correspondence.",
     "look_for": "Who made each decision, who approved it, and which recorded material each step relies on.",
     "reviewer_question": "Could a later reader tell, from the record alone, who was answerable for each step and on what recorded material?",
     "category": null,
     "codebook_correspondence": "not_asserted"
    },
    "disposition": {
     "status": "pending",
     "history": []
    },
    "condition": "accountability_support",
    "condition_status": "review",
    "model_note": "The record states this only in part.",
    "anchor_note": "A candidate key concerns the record as a whole; quotations, if any, are on the flaw findings. A quotation shows presence in the record, not support."
   },
   {
    "id": "C-005",
    "kind": "condition",
    "explanation_id": "cold_reviewer_clarity",
    "uncertain": false,
    "explanation": {
     "label": "Reviewer reconstruction (candidate-internal, unmapped)",
     "meaning": "The model judged that a reader with no prior knowledge might not be able to reconstruct the basis from the record alone. This is a candidate key, not a JRS condition: it has no established Codebook correspondence.",
     "look_for": "Terms, references or context the record assumes a reader already has.",
     "reviewer_question": "Would a reader new to this matter need anything not in the record to follow it?",
     "category": null,
     "codebook_correspondence": "not_asserted"
    },
    "disposition": {
     "status": "pending",
     "history": []
    },
    "condition": "cold_reviewer_clarity",
    "condition_status": "review",
    "model_note": null,
    "anchor_note": "A candidate key concerns the record as a whole; quotations, if any, are on the flaw findings. A quotation shows presence in the record, not support."
   },
   {
    "id": "C-006",
    "kind": "flaw",
    "explanation_id": "unsupported_conclusion",
    "uncertain": false,
    "explanation": {
     "label": "Unsupported conclusion",
     "meaning": "The record asserts something that goes beyond what its own content shows.",
     "look_for": "Material in the record that shows the asserted point, not only a statement that it is so.",
     "reviewer_question": "Does anything in the record show this point, or is it only asserted?",
     "category": "unsupported_conclusion",
     "codebook_correspondence": "not_asserted"
    },
    "disposition": {
     "status": "pending",
     "history": []
    },
    "type": "evidentiary_overreach",
    "quotation": "clearly a trusted partner",
    "model_note": "Trust is asserted, and no basis for it is recorded.",
    "anchors": [
     {
      "start": 489,
      "end": 514,
      "line": 7,
      "column": 47
     }
    ]
   },
   {
    "id": "C-007",
    "kind": "flaw",
    "explanation_id": "missing_logical_bridge",
    "uncertain": true,
    "explanation": {
     "label": "Missing logical bridge",
     "meaning": "The record states facts and a conclusion, but not the step that connects them.",
     "look_for": "A sentence that says why the stated facts lead to the conclusion reached.",
     "reviewer_question": "Could a later reader explain, from the record alone, how the facts led to the conclusion?",
     "category": "missing_logical_bridge",
     "codebook_correspondence": "not_asserted"
    },
    "disposition": {
     "status": "pending",
     "history": []
    },
    "type": "reasoning_elision",
    "quotation": "As discussed on the call, the agreement will follow.",
    "model_note": "The required agreement is deferred without saying why access proceeded first.",
    "anchors": [
     {
      "start": 296,
      "end": 348,
      "line": 5,
      "column": 147
     }
    ]
   }
  ],
  "model_revision_note": null
 },
 "model_output_checks": [
  {
   "id": "X-006",
   "code": "withheld_prohibited_inference",
   "field": "conditions.cold_reviewer_clarity",
   "groups": [
    "emotion"
   ],
   "rejection_codes": null,
   "rejection_details": null,
   "explanation": {
    "label": "Model text withheld",
    "meaning": "The model described a person rather than the record, so that text was withheld.",
    "look_for": null,
    "reviewer_question": "No action on the record. This is a check on the model output.",
    "category": null,
    "codebook_correspondence": "not_asserted"
   },
   "disposition": {
    "status": "not_required",
    "history": []
   }
  }
 ],
 "disposition": {
  "status": "pending",
  "pending": [
   "X-001",
   "X-002",
   "X-003",
   "X-004",
   "X-005",
   "C-001",
   "C-002",
   "C-003",
   "C-004",
   "C-005",
   "C-006",
   "C-007"
  ],
  "history": []
 },
 "sign_off": {
  "status": "not_signed",
  "reviewer": null,
  "signed_at": null,
  "statement": null,
  "meaning": "Sign-off records that a named person reviewed every finding in this result. It is not an access decision, not an approval of the record and not a validation of the candidate.",
  "permitted_now": false
 },
 "packet_id": "1750b76f6ca20bfcda0f69ef"
};
