// GENERATED by tools/frozen-demo/run-demo.mjs. Do not edit by hand.
// SYNTHETIC DEMONSTRATION DATA: fictional records, scripted mock-adapter output. No live model was run.
export const FROZEN_DEMO = {
 "notice": "SYNTHETIC DEMONSTRATION DATA. Fictional organisations, people, dates and facts. Pre-generated by the local candidate with a scripted mock adapter. No live model was run.",
 "package": {
  "package_id": "JRS-FROZEN-DEMO-20261007-PR39",
  "package_version": "0.1.0",
  "status": "DEMO_PREPARATION_COMPLETE_NOT_RELEASED",
  "candidate_version": "0.5.0-local.1",
  "prompt_version": "candidate-prompt/0.4.0",
  "prompt_sha256": "fabccb9760c06055c8415c76d12df1e38625bff08c610fdc0c14c0a839d8d8a7",
  "adapter": {
   "module": "lib/engine-candidate/mock-adapter.js",
   "factory": "createMockAdapter",
   "kind": "deterministic_mock",
   "model_id": "mock-frozen-demo",
   "model_version": "frozen-demo-0.1.0"
  },
  "source_commit": "7bfb13e7305bf9d789287ddd8578b421d77d36d3",
  "corpus_commit": "1717f1bc9725a2635397c66487eb29222f863cd4"
 },
 "manifest_check": {
  "status": "DEMO_PREPARATION_COMPLETE_NOT_RELEASED",
  "records": [
   {
    "record_id": "FD-01",
    "record_version": "1",
    "source_sha256": "5ea8842f5187c8c2d0002927c443a8fa9ae7a8958b8321f0ae5f85079b74799f",
    "expected_digests": {
     "review_id": "a3d3f98277959be19a2a86d7",
     "result_digest": "b8e4d46ad1028886fe94c345e48d25d2e19ea047326ca5ae92922de6088771ba",
     "packet_id": "85cd68cd7e381017e0cd2055",
     "packet_digest": "4a8fccaa4872bcb9a41a19055761bb0231737f9daa90b20ee67d1b8840aec6d9"
    }
   },
   {
    "record_id": "FD-02",
    "record_version": "1",
    "source_sha256": "b68f9da50fa2a1a33b894a286d9b73b3e43d3f7ed623ba7ba6e79a6f6dbf2c5d",
    "expected_digests": {
     "review_id": "a857fafa9664a3469ee24f0d",
     "result_digest": "eaa3489ff1ba04725a53c738c7678d28237d34ac25d1bfaecfd9409f92a9ff60",
     "packet_id": "801bc46344cc5b65ca64d409",
     "packet_digest": "33d045cf9d2946832ac4c659feae8f6d4d10c04f7898d565ff8c94cffbd02438"
    }
   },
   {
    "record_id": "FD-03",
    "record_version": "1",
    "source_sha256": "6896021cb0776c472ddf73e38d9926f8ba3e66945cdd8e824f49cd943f01f80a",
    "expected_digests": {
     "review_id": "9d36768ca85350dd6c1b3ac6",
     "result_digest": "f96ece1ec0102ca317872a08ae5bb0b3f72d1d9d26b34408d80cd55e76e0740c",
     "packet_id": "9f1489fed27b90d7037f0279",
     "packet_digest": "e3bf3463e302426279ecf3399aa9c7b58493182485435f8da2dca31cb0e69a57"
    }
   },
   {
    "record_id": "FD-04",
    "record_version": "1",
    "source_sha256": "80060a51a24a15f82bc22b3d577b557d2a8d46e4a618d4c9a365dcfabb675fb4",
    "expected_digests": {
     "review_id": "3750c52765983f035054d3d1",
     "result_digest": "b5d9068dafae86e3119e121b3a7a01bebda7e09854840cab02a9e34933077710",
     "packet_id": "8c29d9f4672fdd5fe4e7e079",
     "packet_digest": "8b629713cdbb21d55af5c40eea80b015ed51a3970a8eca9d0676cae9e01275b0"
    }
   },
   {
    "record_id": "FD-05",
    "record_version": "1",
    "source_sha256": "a55d03f238e12659ede7db177917647e4e2a7e8350e9dba1c44c4fcfffbeca65",
    "expected_digests": {
     "review_id": "59511768c7c06bb2e0d7ef18",
     "result_digest": "8b005a0785bc367691e95a9a16c0475a6004c8b67a8a705b1f316664e5b407a9",
     "packet_id": "0c606c6ad981e5a97b6f8276",
     "packet_digest": "8c883ff37cf8d2c2da724cf8acbbc33915819cef5ea4bb2e15303eaf7abd1e76"
    }
   }
  ]
 },
 "scope_and_limitations": {
  "scope": "Completed, non-HR supplier-access exception drafts only. Employment, housing, lending, insurance, medical and legal-outcome content is excluded.",
  "limitations": {
   "synthetic_only": "Every case is SYNTHETIC: fictional organisations, people, dates and facts written for this package. No real, public, participant, pilot or holdout record is used.",
   "mock_output_only": "Every candidate output comes from the deterministic mock adapter scripted with the response frozen in each record. No live model was run.",
   "no_semantic_correctness": "No semantic correctness: an exact quotation shows where text sits in the record, not that a finding is right.",
   "no_real_provider_behavior": "No real-provider behavior: the package says nothing about what any real model would return for these records.",
   "no_real_record_performance": "No real-record performance: five constructed records written by the package author show software behaviour, not accuracy, reliability or validity.",
   "no_independent_labeling": "No independent labeling: the records, the scripted responses, the expectations and the disposition examples share one author.",
   "not_a_holdout": "Not a sealed holdout. The five texts are registered as development material, so a future holdout builder refuses them.",
   "no_operational_control_verification": "No operational-control verification: nothing here examines a deployment, an operator control, retention, access or monitoring.",
   "no_production_or_commercial_readiness": "No production or commercial readiness of any kind is shown or implied, and no licensing, sale or pilot pathway is created.",
   "fixed_configuration_only": "Repeatable only within its fixed local configuration: the bound module hashes, versions, prompt, adapter, corpus and fixed time stamp. Any change is a new package version.",
   "no_release_gate_advanced": "No release gate is advanced. The independent holdout, operator-control, counsel, owner-authorization and independent production-QA gates remain open.",
   "fictional_names_not_exhaustively_checked": "Names were invented and are checked against a closed list in each record and a screen of common real names; the package cannot exclude a coincidental match with a real organisation or person."
  }
 },
 "evidence_statements": {
  "all_cases_synthetic": true,
  "all_output_mocked_or_local": true,
  "repeatable_only_within_fixed_local_configuration": true,
  "independent_evaluation": false,
  "sealed_holdout": false,
  "release_gates_advanced": [],
  "owner_release_decision_recorded": false,
  "public_or_customer_demonstration_occurred": false,
  "real_records_processed": false,
  "provider_calls_made": false
 },
 "cases": [
  {
   "record_id": "FD-01",
   "record_version": "1",
   "record_ref": "SYNTHETIC-FD-01",
   "demonstrates": "complete_reconstructable_record",
   "summary": "A complete, reconstructable record with no material gap.",
   "source_sha256": "5ea8842f5187c8c2d0002927c443a8fa9ae7a8958b8321f0ae5f85079b74799f",
   "text": "SYNTHETIC DEMONSTRATION RECORD FD-01. Fictional organisations, people, dates and facts. Not a real record.\nSupplier-access exception, completed draft. Reference SYN-FD-01.\nOn 3 February 2031 Tarnwick Coatings Ltd requested read-only access to the coatings-specification library of Halvenmoor Instruments for four weeks. The supplier-access policy requires a completed security questionnaire before any access is granted. Tarnwick submitted the questionnaire on 30 January 2031, and on 31 January 2031 the security office recorded that section 6 (incident contacts) was incomplete. On 4 February 2031 the procurement lead, Imra Tevalle, approved a read-only exception because the specification was needed for a coating trial scheduled for 12 February 2031, and recorded that the security office would confirm section 6 by 14 February 2031. Access was granted on 5 February 2031 and ends on 4 March 2031.",
   "fictional_entities": {
    "organisations": [
     "Tarnwick Coatings Ltd",
     "Halvenmoor Instruments"
    ],
    "people": [
     "Imra Tevalle"
    ]
   },
   "source_preparation": {
    "version": "source-prep/0.3.0",
    "refusal": null,
    "findings": [],
    "quotations": []
   },
   "candidate": {
    "status": "examined",
    "reason": null,
    "detail": null,
    "adapter_calls": 1,
    "adapter_identity": {
     "model_id": "mock-frozen-demo",
     "model_version": "frozen-demo-0.1.0",
     "prompt_version": "candidate-prompt/0.4.0"
    },
    "conditions": {
     "basis_identification": {
      "status": "pass",
      "note": "The record states this.",
      "uncertain": false
     },
     "reasoning_traceability": {
      "status": "pass",
      "note": "The record states this.",
      "uncertain": false
     },
     "temporal_reconstructability": {
      "status": "pass",
      "note": "The record states this.",
      "uncertain": false
     },
     "accountability_support": {
      "status": "pass",
      "note": "The record states this.",
      "uncertain": false
     },
     "cold_reviewer_clarity": {
      "status": "pass",
      "note": "The record states this.",
      "uncertain": false
     }
    },
    "findings": [],
    "extraction_findings": []
   },
   "scope_probes": [
    {
     "probe_id": "FD-01-P1",
     "profile_change": {
      "hr_related": true
     },
     "observed": {
      "result_status": "refused",
      "reason": "hr_status_not_declared_false",
      "adapter_called": false
     }
    },
    {
     "probe_id": "FD-01-P2",
     "profile_change": {
      "record_type": "vendor_contract_renewal"
     },
     "observed": {
      "result_status": "refused",
      "reason": "out_of_scope_record_type",
      "adapter_called": false
     }
    },
    {
     "probe_id": "FD-01-P3",
     "profile_change": {
      "completion_status": "in_progress"
     },
     "observed": {
      "result_status": "refused",
      "reason": "draft_not_completed",
      "adapter_called": false
     }
    }
   ],
   "packet": {
    "packet_version": "jrs-candidate-reviewer-packet/0.1.0",
    "status": {
     "human_review_required": true,
     "standing": "LOCAL CANDIDATE, NOT VALIDATED",
     "notice": "Produced by a local development candidate with a mocked model. It is not a decision, not a validation and not an approval. A person must read the record and every item below."
    },
    "review_identity": {
     "contract_version": "jrs-candidate-result/0.3.0",
     "candidate_version": "0.5.0-local.1",
     "source_prep_version": "source-prep/0.3.0",
     "explanation_set_version": "explanations/0.2.0",
     "prompt_sha256": "fabccb9760c06055c8415c76d12df1e38625bff08c610fdc0c14c0a839d8d8a7",
     "prompt_version": "candidate-prompt/0.4.0",
     "adapter_contract": "jrs-candidate-adapter-output/0.1.0",
     "model": "mock-frozen-demo@frozen-demo-0.1.0",
     "derived_from": "d2da83c:api/review-engine.js (0.1.0-validation)",
     "review_id": "a3d3f98277959be19a2a86d7"
    },
    "result_digest": "b8e4d46ad1028886fe94c345e48d25d2e19ea047326ca5ae92922de6088771ba",
    "record_ref": "SYNTHETIC-FD-01",
    "source_preparation": {
     "version": "source-prep/0.3.0",
     "result_status": "examined",
     "reason": null,
     "detail": null,
     "refusal_codes": [],
     "source": {
      "sha256": "5ea8842f5187c8c2d0002927c443a8fa9ae7a8958b8321f0ae5f85079b74799f",
      "chars": 902,
      "lines": 3
     }
    },
    "deterministic_findings": [],
    "model_findings": {
     "origin": "mocked model (local candidate adapter)",
     "conditions": {
      "basis_identification": {
       "status": "pass",
       "note": "The record states this.",
       "uncertain": false
      },
      "reasoning_traceability": {
       "status": "pass",
       "note": "The record states this.",
       "uncertain": false
      },
      "temporal_reconstructability": {
       "status": "pass",
       "note": "The record states this.",
       "uncertain": false
      },
      "accountability_support": {
       "status": "pass",
       "note": "The record states this.",
       "uncertain": false
      },
      "cold_reviewer_clarity": {
       "status": "pass",
       "note": "The record states this.",
       "uncertain": false
      }
     },
     "findings": [],
     "model_revision_note": null
    },
    "model_output_checks": [],
    "disposition": {
     "status": "nothing_to_dispose",
     "pending": [],
     "history": []
    },
    "sign_off": {
     "status": "not_signed",
     "reviewer": null,
     "signed_at": null,
     "statement": null,
     "meaning": "Sign-off records that a named person reviewed every finding in this result. It is not an access decision, not an approval of the record and not a validation of the candidate.",
     "permitted_now": true
    },
    "packet_id": "85cd68cd7e381017e0cd2055"
   },
   "digests": {
    "review_id": "a3d3f98277959be19a2a86d7",
    "result_digest": "b8e4d46ad1028886fe94c345e48d25d2e19ea047326ca5ae92922de6088771ba",
    "packet_id": "85cd68cd7e381017e0cd2055",
    "packet_digest": "4a8fccaa4872bcb9a41a19055761bb0231737f9daa90b20ee67d1b8840aec6d9"
   },
   "human_disposition_example": {
    "opened": true,
    "source_text_checked": true,
    "standing": "ILLUSTRATIVE EXAMPLE of the local disposition workflow, written by the package author. Not a correct answer, not an independent label, not a decision.",
    "export_record": {
     "export_format": "jrs-local-disposition-record/0.1.0",
     "workspace_version": "jrs-local-reviewer-workspace/0.1.0",
     "packet": {
      "packet_version": "jrs-candidate-reviewer-packet/0.1.0",
      "review_id": "a3d3f98277959be19a2a86d7",
      "result_digest": "b8e4d46ad1028886fe94c345e48d25d2e19ea047326ca5ae92922de6088771ba",
      "packet_id": "85cd68cd7e381017e0cd2055",
      "packet_digest": "4a8fccaa4872bcb9a41a19055761bb0231737f9daa90b20ee67d1b8840aec6d9",
      "candidate_version": "0.5.0-local.1",
      "source_sha256": "5ea8842f5187c8c2d0002927c443a8fa9ae7a8958b8321f0ae5f85079b74799f",
      "record_ref": "SYNTHETIC-FD-01"
     },
     "reviewer": {
      "reference": "SYNTHETIC-REVIEWER-EXAMPLE",
      "self_entered": true,
      "authenticated": false
     },
     "review_date": "2026-10-07",
     "dispositions": [],
     "sign_off": {
      "statement": "I reviewed every finding listed in this packet and recorded a disposition for each. This sign-off is not an approval of the record, not an access decision and not a validation of the candidate.",
      "signed": true,
      "date": "2026-10-07"
     },
     "limitation": "This is a reviewer-created local disposition record. It is bound to the identified packet and version. It does not authenticate the reviewer, establish legal validity, establish semantic correctness, or authorize production use.",
     "export_digest": "4e13a8b1c79564231f05b465f0c62869318e5cc4c76f84ded9179c4fa0cc8332"
    },
    "export_verification": {
     "ok": true,
     "problems": []
    }
   },
   "expected": {
    "input_preparation": {
     "refusal": null,
     "refusal_codes": [],
     "source_prep_codes": [],
     "elements_missing": []
    },
    "mock_response": {
     "adapter_contract": "jrs-candidate-adapter-output/0.1.0",
     "model_id": "mock-frozen-demo",
     "model_version": "frozen-demo-0.1.0",
     "prompt_version": "candidate-prompt/0.4.0",
     "completion": "complete",
     "conditions": {
      "basis_identification": {
       "status": "pass",
       "explanation_id": "missing_identifiable_basis",
       "note": "The record states this.",
       "uncertain": false
      },
      "reasoning_traceability": {
       "status": "pass",
       "explanation_id": "missing_logical_bridge",
       "note": "The record states this.",
       "uncertain": false
      },
      "cold_reviewer_clarity": {
       "status": "pass",
       "explanation_id": "cold_reviewer_clarity",
       "note": "The record states this.",
       "uncertain": false
      },
      "accountability_support": {
       "status": "pass",
       "explanation_id": "accountability_support",
       "note": "The record states this.",
       "uncertain": false
      },
      "temporal_reconstructability": {
       "status": "pass",
       "explanation_id": "chronology_gap",
       "note": "The record states this.",
       "uncertain": false
      }
     },
     "findings": [],
     "revision_needed": null
    },
    "candidate": {
     "adapter_called": true,
     "result_status": "examined",
     "flagged_keys": {},
     "finding_types": [],
     "finding_quotations": [],
     "withheld_groups": []
    },
    "scope_probes": [
     {
      "probe_id": "FD-01-P1",
      "profile_change": {
       "hr_related": true
      },
      "expected": {
       "result_status": "refused",
       "reason": "hr_status_not_declared_false",
       "adapter_called": false
      }
     },
     {
      "probe_id": "FD-01-P2",
      "profile_change": {
       "record_type": "vendor_contract_renewal"
      },
      "expected": {
       "result_status": "refused",
       "reason": "out_of_scope_record_type",
       "adapter_called": false
      }
     },
     {
      "probe_id": "FD-01-P3",
      "profile_change": {
       "completion_status": "in_progress"
      },
      "expected": {
       "result_status": "refused",
       "reason": "draft_not_completed",
       "adapter_called": false
      }
     }
    ]
   },
   "does_not_establish": [
    "SYNTHETIC. Written by Claude Code (an AI) on 2026-10-07 for a local demonstration package. No real supplier, person, organisation, date or record is described or was used.",
    "The names were invented for this package and checked against a closed list in the record; resemblance to a real organisation or person is not intended and cannot be excluded by the package itself.",
    "Expected candidate behaviour is the scripted output of a deterministic mock adapter. It shows what the software does with that output, not what any real model would return.",
    "Not a sealed holdout, not independent labeling, not real-record evidence and not evidence of accuracy, reliability or validity.",
    "No material gap is shown only in the sense that the scripted mock reports none and source preparation finds none. It does not show the record is correct, sufficient or acceptable, and it is not an approval of the exception."
   ]
  },
  {
   "record_id": "FD-02",
   "record_version": "1",
   "record_ref": "SYNTHETIC-FD-02",
   "demonstrates": "missing_identifiable_basis",
   "summary": "An exception approved with a conclusion and no stated basis.",
   "source_sha256": "b68f9da50fa2a1a33b894a286d9b73b3e43d3f7ed623ba7ba6e79a6f6dbf2c5d",
   "text": "SYNTHETIC DEMONSTRATION RECORD FD-02. Fictional organisations, people, dates and facts. Not a real record.\nSupplier-access exception, completed draft. Reference SYN-FD-02.\nOn 10 March 2031 Brisenfold Logistics Ltd requested access to the dock-scheduling system of Halvenmoor Instruments for six weeks. The supplier-access policy requires a signed data-handling agreement before access is granted, and no signed agreement was on file on 10 March 2031. On 11 March 2031 the procurement lead, Doran Velquist, approved an exception to the agreement requirement. The approval note reads: \"Exception approved; the supplier is low risk.\" Access was granted on 12 March 2031 and ends on 21 April 2031.",
   "fictional_entities": {
    "organisations": [
     "Brisenfold Logistics Ltd",
     "Halvenmoor Instruments"
    ],
    "people": [
     "Doran Velquist"
    ]
   },
   "source_preparation": {
    "version": "source-prep/0.3.0",
    "refusal": null,
    "findings": [
     {
      "kind": "omission",
      "code": "profile_element_not_found",
      "element": "exception_basis",
      "matched": null,
      "detail": "No stated basis for the exception was found. (Heuristic presence check: a missing match is not proof of omission.)",
      "location": null
     }
    ],
    "quotations": [
     {
      "text": "Exception approved; the supplier is low risk.",
      "start": 584,
      "end": 629,
      "line": 3,
      "column": 413
     }
    ]
   },
   "candidate": {
    "status": "examined",
    "reason": null,
    "detail": null,
    "adapter_calls": 1,
    "adapter_identity": {
     "model_id": "mock-frozen-demo",
     "model_version": "frozen-demo-0.1.0",
     "prompt_version": "candidate-prompt/0.4.0"
    },
    "conditions": {
     "basis_identification": {
      "status": "gap",
      "note": "The record states a low-risk conclusion and does not name what that conclusion rests on.",
      "uncertain": false
     },
     "reasoning_traceability": {
      "status": "pass",
      "note": "The record states this.",
      "uncertain": false
     },
     "temporal_reconstructability": {
      "status": "pass",
      "note": "The record states this.",
      "uncertain": false
     },
     "accountability_support": {
      "status": "pass",
      "note": "The record states this.",
      "uncertain": false
     },
     "cold_reviewer_clarity": {
      "status": "pass",
      "note": "The record states this.",
      "uncertain": false
     }
    },
    "findings": [
     {
      "id": "C-001",
      "kind": "condition",
      "condition": "basis_identification",
      "status": "gap",
      "type": null,
      "quotation": null,
      "locations": null,
      "note": "The record states a low-risk conclusion and does not name what that conclusion rests on.",
      "uncertain": false,
      "explanation_label": "Missing identifiable basis"
     },
     {
      "id": "C-002",
      "kind": "flaw",
      "condition": null,
      "status": null,
      "type": "evidentiary_overreach",
      "quotation": "the supplier is low risk",
      "locations": [
       {
        "start": 604,
        "end": 628,
        "line": 3,
        "column": 433
       }
      ],
      "note": "Low risk is asserted, and nothing in the record shows the basis for it.",
      "uncertain": false,
      "explanation_label": "Unsupported conclusion"
     }
    ],
    "extraction_findings": [
     {
      "id": "X-001",
      "origin": "source_prep",
      "code": "profile_element_not_found",
      "element": "exception_basis"
     }
    ]
   },
   "scope_probes": [],
   "packet": {
    "packet_version": "jrs-candidate-reviewer-packet/0.1.0",
    "status": {
     "human_review_required": true,
     "standing": "LOCAL CANDIDATE, NOT VALIDATED",
     "notice": "Produced by a local development candidate with a mocked model. It is not a decision, not a validation and not an approval. A person must read the record and every item below."
    },
    "review_identity": {
     "contract_version": "jrs-candidate-result/0.3.0",
     "candidate_version": "0.5.0-local.1",
     "source_prep_version": "source-prep/0.3.0",
     "explanation_set_version": "explanations/0.2.0",
     "prompt_sha256": "fabccb9760c06055c8415c76d12df1e38625bff08c610fdc0c14c0a839d8d8a7",
     "prompt_version": "candidate-prompt/0.4.0",
     "adapter_contract": "jrs-candidate-adapter-output/0.1.0",
     "model": "mock-frozen-demo@frozen-demo-0.1.0",
     "derived_from": "d2da83c:api/review-engine.js (0.1.0-validation)",
     "review_id": "a857fafa9664a3469ee24f0d"
    },
    "result_digest": "eaa3489ff1ba04725a53c738c7678d28237d34ac25d1bfaecfd9409f92a9ff60",
    "record_ref": "SYNTHETIC-FD-02",
    "source_preparation": {
     "version": "source-prep/0.3.0",
     "result_status": "examined",
     "reason": null,
     "detail": null,
     "refusal_codes": [],
     "source": {
      "sha256": "b68f9da50fa2a1a33b894a286d9b73b3e43d3f7ed623ba7ba6e79a6f6dbf2c5d",
      "chars": 693,
      "lines": 3
     }
    },
    "deterministic_findings": [
     {
      "id": "X-001",
      "kind": "omission",
      "code": "profile_element_not_found",
      "element": "exception_basis",
      "detail": "No stated basis for the exception was found. (Heuristic presence check: a missing match is not proof of omission.)",
      "explanation": {
       "label": "Expected element not found",
       "meaning": "A supplier-access exception record usually states this element, and no match was found. This is a pattern check, not proof of omission.",
       "look_for": null,
       "reviewer_question": "Does the record state this element in words the check did not recognise, or is it absent?",
       "category": null,
       "codebook_correspondence": "not_asserted"
      },
      "disposition": {
       "status": "pending",
       "history": []
      },
      "anchor_note": "This finding concerns something absent from the record, so there is no quotation to anchor."
     }
    ],
    "model_findings": {
     "origin": "mocked model (local candidate adapter)",
     "conditions": {
      "basis_identification": {
       "status": "gap",
       "note": "The record states a low-risk conclusion and does not name what that conclusion rests on.",
       "uncertain": false
      },
      "reasoning_traceability": {
       "status": "pass",
       "note": "The record states this.",
       "uncertain": false
      },
      "temporal_reconstructability": {
       "status": "pass",
       "note": "The record states this.",
       "uncertain": false
      },
      "accountability_support": {
       "status": "pass",
       "note": "The record states this.",
       "uncertain": false
      },
      "cold_reviewer_clarity": {
       "status": "pass",
       "note": "The record states this.",
       "uncertain": false
      }
     },
     "findings": [
      {
       "id": "C-001",
       "kind": "condition",
       "explanation_id": "missing_identifiable_basis",
       "uncertain": false,
       "explanation": {
        "label": "Missing identifiable basis",
        "meaning": "A conclusion is stated, but the record does not identify what it rests on.",
        "look_for": "The document, observation, rule or fact the conclusion relies on, named in the record.",
        "reviewer_question": "Can the basis for this conclusion be pointed to in the record itself?",
        "category": "missing_identifiable_basis",
        "codebook_correspondence": "not_asserted"
       },
       "disposition": {
        "status": "pending",
        "history": []
       },
       "condition": "basis_identification",
       "condition_status": "gap",
       "model_note": "The record states a low-risk conclusion and does not name what that conclusion rests on.",
       "anchor_note": "A candidate key concerns the record as a whole; quotations, if any, are on the flaw findings. A quotation shows presence in the record, not support."
      },
      {
       "id": "C-002",
       "kind": "flaw",
       "explanation_id": "unsupported_conclusion",
       "uncertain": false,
       "explanation": {
        "label": "Unsupported conclusion",
        "meaning": "The record asserts something that goes beyond what its own content shows.",
        "look_for": "Material in the record that shows the asserted point, not only a statement that it is so.",
        "reviewer_question": "Does anything in the record show this point, or is it only asserted?",
        "category": "unsupported_conclusion",
        "codebook_correspondence": "not_asserted"
       },
       "disposition": {
        "status": "pending",
        "history": []
       },
       "type": "evidentiary_overreach",
       "quotation": "the supplier is low risk",
       "model_note": "Low risk is asserted, and nothing in the record shows the basis for it.",
       "anchors": [
        {
         "start": 604,
         "end": 628,
         "line": 3,
         "column": 433
        }
       ]
      }
     ],
     "model_revision_note": null
    },
    "model_output_checks": [],
    "disposition": {
     "status": "pending",
     "pending": [
      "X-001",
      "C-001",
      "C-002"
     ],
     "history": []
    },
    "sign_off": {
     "status": "not_signed",
     "reviewer": null,
     "signed_at": null,
     "statement": null,
     "meaning": "Sign-off records that a named person reviewed every finding in this result. It is not an access decision, not an approval of the record and not a validation of the candidate.",
     "permitted_now": false
    },
    "packet_id": "801bc46344cc5b65ca64d409"
   },
   "digests": {
    "review_id": "a857fafa9664a3469ee24f0d",
    "result_digest": "eaa3489ff1ba04725a53c738c7678d28237d34ac25d1bfaecfd9409f92a9ff60",
    "packet_id": "801bc46344cc5b65ca64d409",
    "packet_digest": "33d045cf9d2946832ac4c659feae8f6d4d10c04f7898d565ff8c94cffbd02438"
   },
   "human_disposition_example": {
    "opened": true,
    "source_text_checked": true,
    "standing": "ILLUSTRATIVE EXAMPLE of the local disposition workflow, written by the package author. Not a correct answer, not an independent label, not a decision.",
    "export_record": {
     "export_format": "jrs-local-disposition-record/0.1.0",
     "workspace_version": "jrs-local-reviewer-workspace/0.1.0",
     "packet": {
      "packet_version": "jrs-candidate-reviewer-packet/0.1.0",
      "review_id": "a857fafa9664a3469ee24f0d",
      "result_digest": "eaa3489ff1ba04725a53c738c7678d28237d34ac25d1bfaecfd9409f92a9ff60",
      "packet_id": "801bc46344cc5b65ca64d409",
      "packet_digest": "33d045cf9d2946832ac4c659feae8f6d4d10c04f7898d565ff8c94cffbd02438",
      "candidate_version": "0.5.0-local.1",
      "source_sha256": "b68f9da50fa2a1a33b894a286d9b73b3e43d3f7ed623ba7ba6e79a6f6dbf2c5d",
      "record_ref": "SYNTHETIC-FD-02"
     },
     "reviewer": {
      "reference": "SYNTHETIC-REVIEWER-EXAMPLE",
      "self_entered": true,
      "authenticated": false
     },
     "review_date": "2026-10-07",
     "dispositions": [
      {
       "finding_id": "X-001",
       "section": "source_preparation",
       "review_id": "a857fafa9664a3469ee24f0d",
       "packet_digest": "33d045cf9d2946832ac4c659feae8f6d4d10c04f7898d565ff8c94cffbd02438",
       "disposition": "CONFIRMED_FOR_FURTHER_REVIEW",
       "note": "Example: the quoted text is present; whether the finding holds is for the reviewer.",
       "applies_only_to_this_packet": true
      },
      {
       "finding_id": "C-001",
       "section": "candidate_prompts",
       "review_id": "a857fafa9664a3469ee24f0d",
       "packet_digest": "33d045cf9d2946832ac4c659feae8f6d4d10c04f7898d565ff8c94cffbd02438",
       "disposition": "CONFIRMED_FOR_FURTHER_REVIEW",
       "note": "Example: the quoted text is present; whether the finding holds is for the reviewer.",
       "applies_only_to_this_packet": true
      },
      {
       "finding_id": "C-002",
       "section": "candidate_prompts",
       "review_id": "a857fafa9664a3469ee24f0d",
       "packet_digest": "33d045cf9d2946832ac4c659feae8f6d4d10c04f7898d565ff8c94cffbd02438",
       "disposition": "CONFIRMED_FOR_FURTHER_REVIEW",
       "note": "Example: the quoted text is present; whether the finding holds is for the reviewer.",
       "applies_only_to_this_packet": true
      }
     ],
     "sign_off": {
      "statement": "I reviewed every finding listed in this packet and recorded a disposition for each. This sign-off is not an approval of the record, not an access decision and not a validation of the candidate.",
      "signed": true,
      "date": "2026-10-07"
     },
     "limitation": "This is a reviewer-created local disposition record. It is bound to the identified packet and version. It does not authenticate the reviewer, establish legal validity, establish semantic correctness, or authorize production use.",
     "export_digest": "99f795383d582b9f3e4d43a703357506ca1535d2f4586ad27a55ef680074c3d2"
    },
    "export_verification": {
     "ok": true,
     "problems": []
    }
   },
   "expected": {
    "input_preparation": {
     "refusal": null,
     "refusal_codes": [],
     "source_prep_codes": [
      "profile_element_not_found"
     ],
     "elements_missing": [
      "exception_basis"
     ]
    },
    "mock_response": {
     "adapter_contract": "jrs-candidate-adapter-output/0.1.0",
     "model_id": "mock-frozen-demo",
     "model_version": "frozen-demo-0.1.0",
     "prompt_version": "candidate-prompt/0.4.0",
     "completion": "complete",
     "conditions": {
      "basis_identification": {
       "status": "gap",
       "explanation_id": "missing_identifiable_basis",
       "note": "The record states a low-risk conclusion and does not name what that conclusion rests on.",
       "uncertain": false
      },
      "reasoning_traceability": {
       "status": "pass",
       "explanation_id": "missing_logical_bridge",
       "note": "The record states this.",
       "uncertain": false
      },
      "cold_reviewer_clarity": {
       "status": "pass",
       "explanation_id": "cold_reviewer_clarity",
       "note": "The record states this.",
       "uncertain": false
      },
      "accountability_support": {
       "status": "pass",
       "explanation_id": "accountability_support",
       "note": "The record states this.",
       "uncertain": false
      },
      "temporal_reconstructability": {
       "status": "pass",
       "explanation_id": "chronology_gap",
       "note": "The record states this.",
       "uncertain": false
      }
     },
     "findings": [
      {
       "type": "evidentiary_overreach",
       "quotation": "the supplier is low risk",
       "explanation_id": "unsupported_conclusion",
       "note": "Low risk is asserted, and nothing in the record shows the basis for it.",
       "uncertain": false
      }
     ],
     "revision_needed": null
    },
    "candidate": {
     "adapter_called": true,
     "result_status": "examined",
     "flagged_keys": {
      "basis_identification": "gap"
     },
     "finding_types": [
      "evidentiary_overreach"
     ],
     "finding_quotations": [
      "the supplier is low risk"
     ],
     "withheld_groups": []
    }
   },
   "does_not_establish": [
    "SYNTHETIC. Written by Claude Code (an AI) on 2026-10-07 for a local demonstration package. No real supplier, person, organisation, date or record is described or was used.",
    "The names were invented for this package and checked against a closed list in the record; resemblance to a real organisation or person is not intended and cannot be excluded by the package itself.",
    "Expected candidate behaviour is the scripted output of a deterministic mock adapter. It shows what the software does with that output, not what any real model would return.",
    "Not a sealed holdout, not independent labeling, not real-record evidence and not evidence of accuracy, reliability or validity.",
    "The deterministic finding is a presence check for basis wording; its absence of a match is not proof of omission. The candidate finding is scripted."
   ]
  },
  {
   "record_id": "FD-03",
   "record_version": "1",
   "record_ref": "SYNTHETIC-FD-03",
   "demonstrates": "chronology_gap",
   "summary": "Steps given out of order and without dates, so the sequence cannot be rebuilt.",
   "source_sha256": "6896021cb0776c472ddf73e38d9926f8ba3e66945cdd8e824f49cd943f01f80a",
   "text": "SYNTHETIC DEMONSTRATION RECORD FD-03. Fictional organisations, people, dates and facts. Not a real record.\nSupplier-access exception, completed draft. Reference SYN-FD-03.\nOn 2 May 2031 Corvane Plastics Ltd requested access to the mould-maintenance portal of Halvenmoor Instruments for three weeks. The supplier-access policy requires a security-office review before access is granted. The procurement lead, Sabine Orlecht, approved the exception on 6 May 2031 because a mould repair could not wait for the next review cycle. Access was granted earlier that week, before the approval, and the security office completed its review some days later. Access ends on 23 May 2031.",
   "fictional_entities": {
    "organisations": [
     "Corvane Plastics Ltd",
     "Halvenmoor Instruments"
    ],
    "people": [
     "Sabine Orlecht"
    ]
   },
   "source_preparation": {
    "version": "source-prep/0.3.0",
    "refusal": null,
    "findings": [],
    "quotations": []
   },
   "candidate": {
    "status": "examined",
    "reason": null,
    "detail": null,
    "adapter_calls": 1,
    "adapter_identity": {
     "model_id": "mock-frozen-demo",
     "model_version": "frozen-demo-0.1.0",
     "prompt_version": "candidate-prompt/0.4.0"
    },
    "conditions": {
     "basis_identification": {
      "status": "pass",
      "note": "The record states this.",
      "uncertain": false
     },
     "reasoning_traceability": {
      "status": "pass",
      "note": "The record states this.",
      "uncertain": false
     },
     "temporal_reconstructability": {
      "status": "gap",
      "note": "The record gives no date for the grant of access or for the security-office review, so the order of steps cannot be rebuilt.",
      "uncertain": false
     },
     "accountability_support": {
      "status": "pass",
      "note": "The record states this.",
      "uncertain": false
     },
     "cold_reviewer_clarity": {
      "status": "pass",
      "note": "The record states this.",
      "uncertain": false
     }
    },
    "findings": [
     {
      "id": "C-001",
      "kind": "condition",
      "condition": "temporal_reconstructability",
      "status": "gap",
      "type": null,
      "quotation": null,
      "locations": null,
      "note": "The record gives no date for the grant of access or for the security-office review, so the order of steps cannot be rebuilt.",
      "uncertain": false,
      "explanation_label": "Chronology gap"
     },
     {
      "id": "C-002",
      "kind": "flaw",
      "condition": null,
      "status": null,
      "type": "chronology_collapse",
      "quotation": "Access was granted earlier that week, before the approval",
      "locations": [
       {
        "start": 526,
        "end": 583,
        "line": 3,
        "column": 355
       }
      ],
      "note": "The grant of access is placed before the approval with no date.",
      "uncertain": false,
      "explanation_label": "Chronology gap"
     },
     {
      "id": "C-003",
      "kind": "flaw",
      "condition": null,
      "status": null,
      "type": "chronology_collapse",
      "quotation": "the security office completed its review some days later",
      "locations": [
       {
        "start": 589,
        "end": 645,
        "line": 3,
        "column": 418
       }
      ],
      "note": "The review is given no date, so its place in the sequence is unclear.",
      "uncertain": true,
      "explanation_label": "Chronology gap"
     }
    ],
    "extraction_findings": []
   },
   "scope_probes": [],
   "packet": {
    "packet_version": "jrs-candidate-reviewer-packet/0.1.0",
    "status": {
     "human_review_required": true,
     "standing": "LOCAL CANDIDATE, NOT VALIDATED",
     "notice": "Produced by a local development candidate with a mocked model. It is not a decision, not a validation and not an approval. A person must read the record and every item below."
    },
    "review_identity": {
     "contract_version": "jrs-candidate-result/0.3.0",
     "candidate_version": "0.5.0-local.1",
     "source_prep_version": "source-prep/0.3.0",
     "explanation_set_version": "explanations/0.2.0",
     "prompt_sha256": "fabccb9760c06055c8415c76d12df1e38625bff08c610fdc0c14c0a839d8d8a7",
     "prompt_version": "candidate-prompt/0.4.0",
     "adapter_contract": "jrs-candidate-adapter-output/0.1.0",
     "model": "mock-frozen-demo@frozen-demo-0.1.0",
     "derived_from": "d2da83c:api/review-engine.js (0.1.0-validation)",
     "review_id": "9d36768ca85350dd6c1b3ac6"
    },
    "result_digest": "f96ece1ec0102ca317872a08ae5bb0b3f72d1d9d26b34408d80cd55e76e0740c",
    "record_ref": "SYNTHETIC-FD-03",
    "source_preparation": {
     "version": "source-prep/0.3.0",
     "result_status": "examined",
     "reason": null,
     "detail": null,
     "refusal_codes": [],
     "source": {
      "sha256": "6896021cb0776c472ddf73e38d9926f8ba3e66945cdd8e824f49cd943f01f80a",
      "chars": 674,
      "lines": 3
     }
    },
    "deterministic_findings": [],
    "model_findings": {
     "origin": "mocked model (local candidate adapter)",
     "conditions": {
      "basis_identification": {
       "status": "pass",
       "note": "The record states this.",
       "uncertain": false
      },
      "reasoning_traceability": {
       "status": "pass",
       "note": "The record states this.",
       "uncertain": false
      },
      "temporal_reconstructability": {
       "status": "gap",
       "note": "The record gives no date for the grant of access or for the security-office review, so the order of steps cannot be rebuilt.",
       "uncertain": false
      },
      "accountability_support": {
       "status": "pass",
       "note": "The record states this.",
       "uncertain": false
      },
      "cold_reviewer_clarity": {
       "status": "pass",
       "note": "The record states this.",
       "uncertain": false
      }
     },
     "findings": [
      {
       "id": "C-001",
       "kind": "condition",
       "explanation_id": "chronology_gap",
       "uncertain": false,
       "explanation": {
        "label": "Chronology gap",
        "meaning": "The order or timing of events cannot be rebuilt from the dates the record gives.",
        "look_for": "A date or interval for each step, and steps given in an order that matches those dates.",
        "reviewer_question": "Could a later reader put every step in order, with dates, from the record alone?",
        "category": "chronology_gap",
        "codebook_correspondence": "not_asserted"
       },
       "disposition": {
        "status": "pending",
        "history": []
       },
       "condition": "temporal_reconstructability",
       "condition_status": "gap",
       "model_note": "The record gives no date for the grant of access or for the security-office review, so the order of steps cannot be rebuilt.",
       "anchor_note": "A candidate key concerns the record as a whole; quotations, if any, are on the flaw findings. A quotation shows presence in the record, not support."
      },
      {
       "id": "C-002",
       "kind": "flaw",
       "explanation_id": "chronology_gap",
       "uncertain": false,
       "explanation": {
        "label": "Chronology gap",
        "meaning": "The order or timing of events cannot be rebuilt from the dates the record gives.",
        "look_for": "A date or interval for each step, and steps given in an order that matches those dates.",
        "reviewer_question": "Could a later reader put every step in order, with dates, from the record alone?",
        "category": "chronology_gap",
        "codebook_correspondence": "not_asserted"
       },
       "disposition": {
        "status": "pending",
        "history": []
       },
       "type": "chronology_collapse",
       "quotation": "Access was granted earlier that week, before the approval",
       "model_note": "The grant of access is placed before the approval with no date.",
       "anchors": [
        {
         "start": 526,
         "end": 583,
         "line": 3,
         "column": 355
        }
       ]
      },
      {
       "id": "C-003",
       "kind": "flaw",
       "explanation_id": "chronology_gap",
       "uncertain": true,
       "explanation": {
        "label": "Chronology gap",
        "meaning": "The order or timing of events cannot be rebuilt from the dates the record gives.",
        "look_for": "A date or interval for each step, and steps given in an order that matches those dates.",
        "reviewer_question": "Could a later reader put every step in order, with dates, from the record alone?",
        "category": "chronology_gap",
        "codebook_correspondence": "not_asserted"
       },
       "disposition": {
        "status": "pending",
        "history": []
       },
       "type": "chronology_collapse",
       "quotation": "the security office completed its review some days later",
       "model_note": "The review is given no date, so its place in the sequence is unclear.",
       "anchors": [
        {
         "start": 589,
         "end": 645,
         "line": 3,
         "column": 418
        }
       ]
      }
     ],
     "model_revision_note": null
    },
    "model_output_checks": [],
    "disposition": {
     "status": "pending",
     "pending": [
      "C-001",
      "C-002",
      "C-003"
     ],
     "history": []
    },
    "sign_off": {
     "status": "not_signed",
     "reviewer": null,
     "signed_at": null,
     "statement": null,
     "meaning": "Sign-off records that a named person reviewed every finding in this result. It is not an access decision, not an approval of the record and not a validation of the candidate.",
     "permitted_now": false
    },
    "packet_id": "9f1489fed27b90d7037f0279"
   },
   "digests": {
    "review_id": "9d36768ca85350dd6c1b3ac6",
    "result_digest": "f96ece1ec0102ca317872a08ae5bb0b3f72d1d9d26b34408d80cd55e76e0740c",
    "packet_id": "9f1489fed27b90d7037f0279",
    "packet_digest": "e3bf3463e302426279ecf3399aa9c7b58493182485435f8da2dca31cb0e69a57"
   },
   "human_disposition_example": {
    "opened": true,
    "source_text_checked": true,
    "standing": "ILLUSTRATIVE EXAMPLE of the local disposition workflow, written by the package author. Not a correct answer, not an independent label, not a decision.",
    "export_record": {
     "export_format": "jrs-local-disposition-record/0.1.0",
     "workspace_version": "jrs-local-reviewer-workspace/0.1.0",
     "packet": {
      "packet_version": "jrs-candidate-reviewer-packet/0.1.0",
      "review_id": "9d36768ca85350dd6c1b3ac6",
      "result_digest": "f96ece1ec0102ca317872a08ae5bb0b3f72d1d9d26b34408d80cd55e76e0740c",
      "packet_id": "9f1489fed27b90d7037f0279",
      "packet_digest": "e3bf3463e302426279ecf3399aa9c7b58493182485435f8da2dca31cb0e69a57",
      "candidate_version": "0.5.0-local.1",
      "source_sha256": "6896021cb0776c472ddf73e38d9926f8ba3e66945cdd8e824f49cd943f01f80a",
      "record_ref": "SYNTHETIC-FD-03"
     },
     "reviewer": {
      "reference": "SYNTHETIC-REVIEWER-EXAMPLE",
      "self_entered": true,
      "authenticated": false
     },
     "review_date": "2026-10-07",
     "dispositions": [
      {
       "finding_id": "C-001",
       "section": "candidate_prompts",
       "review_id": "9d36768ca85350dd6c1b3ac6",
       "packet_digest": "e3bf3463e302426279ecf3399aa9c7b58493182485435f8da2dca31cb0e69a57",
       "disposition": "CONFIRMED_FOR_FURTHER_REVIEW",
       "note": "Example: the quoted text is present; whether the finding holds is for the reviewer.",
       "applies_only_to_this_packet": true
      },
      {
       "finding_id": "C-002",
       "section": "candidate_prompts",
       "review_id": "9d36768ca85350dd6c1b3ac6",
       "packet_digest": "e3bf3463e302426279ecf3399aa9c7b58493182485435f8da2dca31cb0e69a57",
       "disposition": "CONFIRMED_FOR_FURTHER_REVIEW",
       "note": "Example: the quoted text is present; whether the finding holds is for the reviewer.",
       "applies_only_to_this_packet": true
      },
      {
       "finding_id": "C-003",
       "section": "candidate_prompts",
       "review_id": "9d36768ca85350dd6c1b3ac6",
       "packet_digest": "e3bf3463e302426279ecf3399aa9c7b58493182485435f8da2dca31cb0e69a57",
       "disposition": "NEEDS_CLARIFICATION",
       "note": "Example: the scripted finding is marked uncertain; ask for the missing detail.",
       "applies_only_to_this_packet": true
      }
     ],
     "sign_off": {
      "statement": "I reviewed every finding listed in this packet and recorded a disposition for each. This sign-off is not an approval of the record, not an access decision and not a validation of the candidate.",
      "signed": true,
      "date": "2026-10-07"
     },
     "limitation": "This is a reviewer-created local disposition record. It is bound to the identified packet and version. It does not authenticate the reviewer, establish legal validity, establish semantic correctness, or authorize production use.",
     "export_digest": "1ba41630ca4dfa5afb1e011ee591dd1a6aab86df2975a499f805b7a13feafefc"
    },
    "export_verification": {
     "ok": true,
     "problems": []
    }
   },
   "expected": {
    "input_preparation": {
     "refusal": null,
     "refusal_codes": [],
     "source_prep_codes": [],
     "elements_missing": []
    },
    "mock_response": {
     "adapter_contract": "jrs-candidate-adapter-output/0.1.0",
     "model_id": "mock-frozen-demo",
     "model_version": "frozen-demo-0.1.0",
     "prompt_version": "candidate-prompt/0.4.0",
     "completion": "complete",
     "conditions": {
      "basis_identification": {
       "status": "pass",
       "explanation_id": "missing_identifiable_basis",
       "note": "The record states this.",
       "uncertain": false
      },
      "reasoning_traceability": {
       "status": "pass",
       "explanation_id": "missing_logical_bridge",
       "note": "The record states this.",
       "uncertain": false
      },
      "cold_reviewer_clarity": {
       "status": "pass",
       "explanation_id": "cold_reviewer_clarity",
       "note": "The record states this.",
       "uncertain": false
      },
      "accountability_support": {
       "status": "pass",
       "explanation_id": "accountability_support",
       "note": "The record states this.",
       "uncertain": false
      },
      "temporal_reconstructability": {
       "status": "gap",
       "explanation_id": "chronology_gap",
       "note": "The record gives no date for the grant of access or for the security-office review, so the order of steps cannot be rebuilt.",
       "uncertain": false
      }
     },
     "findings": [
      {
       "type": "chronology_collapse",
       "quotation": "Access was granted earlier that week, before the approval",
       "explanation_id": "chronology_gap",
       "note": "The grant of access is placed before the approval with no date.",
       "uncertain": false
      },
      {
       "type": "chronology_collapse",
       "quotation": "the security office completed its review some days later",
       "explanation_id": "chronology_gap",
       "note": "The review is given no date, so its place in the sequence is unclear.",
       "uncertain": true
      }
     ],
     "revision_needed": null
    },
    "candidate": {
     "adapter_called": true,
     "result_status": "examined",
     "flagged_keys": {
      "temporal_reconstructability": "gap"
     },
     "finding_types": [
      "chronology_collapse",
      "chronology_collapse"
     ],
     "finding_quotations": [
      "Access was granted earlier that week, before the approval",
      "the security office completed its review some days later"
     ],
     "withheld_groups": []
    }
   },
   "does_not_establish": [
    "SYNTHETIC. Written by Claude Code (an AI) on 2026-10-07 for a local demonstration package. No real supplier, person, organisation, date or record is described or was used.",
    "The names were invented for this package and checked against a closed list in the record; resemblance to a real organisation or person is not intended and cannot be excluded by the package itself.",
    "Expected candidate behaviour is the scripted output of a deterministic mock adapter. It shows what the software does with that output, not what any real model would return.",
    "Not a sealed holdout, not independent labeling, not real-record evidence and not evidence of accuracy, reliability or validity.",
    "Source preparation finds nothing here: it checks that a full date exists, not that every step is dated. The chronology finding comes only from the scripted mock."
   ]
  },
  {
   "record_id": "FD-04",
   "record_version": "1",
   "record_ref": "SYNTHETIC-FD-04",
   "demonstrates": "missing_logical_bridge",
   "summary": "A conclusion much wider than the facts stated, with no step connecting them.",
   "source_sha256": "80060a51a24a15f82bc22b3d577b557d2a8d46e4a618d4c9a365dcfabb675fb4",
   "text": "SYNTHETIC DEMONSTRATION RECORD FD-04. Fictional organisations, people, dates and facts. Not a real record.\nSupplier-access exception, completed draft. Reference SYN-FD-04.\nOn 9 June 2031 Elmshade Calibration Ltd requested remote access to the test-bench calibration logs of Halvenmoor Instruments for two weeks. The supplier-access policy requires that remote access be limited to named devices. Elmshade listed two devices, and on 10 June 2031 the security office confirmed that both were registered. On 11 June 2031 the procurement lead, Ferro Kalvane, approved unrestricted remote access to all engineering systems because the devices were registered. Access was granted on 12 June 2031 and ends on 26 June 2031.",
   "fictional_entities": {
    "organisations": [
     "Elmshade Calibration Ltd",
     "Halvenmoor Instruments"
    ],
    "people": [
     "Ferro Kalvane"
    ]
   },
   "source_preparation": {
    "version": "source-prep/0.3.0",
    "refusal": null,
    "findings": [],
    "quotations": []
   },
   "candidate": {
    "status": "examined",
    "reason": null,
    "detail": null,
    "adapter_calls": 1,
    "adapter_identity": {
     "model_id": "mock-frozen-demo",
     "model_version": "frozen-demo-0.1.0",
     "prompt_version": "candidate-prompt/0.4.0"
    },
    "conditions": {
     "basis_identification": {
      "status": "pass",
      "note": "The record states this.",
      "uncertain": false
     },
     "reasoning_traceability": {
      "status": "gap",
      "note": "The record does not state how registration of two devices for the calibration logs leads to access to all engineering systems.",
      "uncertain": false
     },
     "temporal_reconstructability": {
      "status": "pass",
      "note": "The record states this.",
      "uncertain": false
     },
     "accountability_support": {
      "status": "pass",
      "note": "The record states this.",
      "uncertain": false
     },
     "cold_reviewer_clarity": {
      "status": "pass",
      "note": "The record states this.",
      "uncertain": false
     }
    },
    "findings": [
     {
      "id": "C-001",
      "kind": "condition",
      "condition": "reasoning_traceability",
      "status": "gap",
      "type": null,
      "quotation": null,
      "locations": null,
      "note": "The record does not state how registration of two devices for the calibration logs leads to access to all engineering systems.",
      "uncertain": false,
      "explanation_label": "Missing logical bridge"
     },
     {
      "id": "C-002",
      "kind": "flaw",
      "condition": null,
      "status": null,
      "type": "reasoning_elision",
      "quotation": "approved unrestricted remote access to all engineering systems because the devices were registered",
      "locations": [
       {
        "start": 555,
        "end": 653,
        "line": 3,
        "column": 384
       }
      ],
      "note": "The stated reason covers the two devices and the logs requested, not the wider access recorded.",
      "uncertain": false,
      "explanation_label": "Missing logical bridge"
     }
    ],
    "extraction_findings": []
   },
   "scope_probes": [],
   "packet": {
    "packet_version": "jrs-candidate-reviewer-packet/0.1.0",
    "status": {
     "human_review_required": true,
     "standing": "LOCAL CANDIDATE, NOT VALIDATED",
     "notice": "Produced by a local development candidate with a mocked model. It is not a decision, not a validation and not an approval. A person must read the record and every item below."
    },
    "review_identity": {
     "contract_version": "jrs-candidate-result/0.3.0",
     "candidate_version": "0.5.0-local.1",
     "source_prep_version": "source-prep/0.3.0",
     "explanation_set_version": "explanations/0.2.0",
     "prompt_sha256": "fabccb9760c06055c8415c76d12df1e38625bff08c610fdc0c14c0a839d8d8a7",
     "prompt_version": "candidate-prompt/0.4.0",
     "adapter_contract": "jrs-candidate-adapter-output/0.1.0",
     "model": "mock-frozen-demo@frozen-demo-0.1.0",
     "derived_from": "d2da83c:api/review-engine.js (0.1.0-validation)",
     "review_id": "3750c52765983f035054d3d1"
    },
    "result_digest": "b5d9068dafae86e3119e121b3a7a01bebda7e09854840cab02a9e34933077710",
    "record_ref": "SYNTHETIC-FD-04",
    "source_preparation": {
     "version": "source-prep/0.3.0",
     "result_status": "examined",
     "reason": null,
     "detail": null,
     "refusal_codes": [],
     "source": {
      "sha256": "80060a51a24a15f82bc22b3d577b557d2a8d46e4a618d4c9a365dcfabb675fb4",
      "chars": 715,
      "lines": 3
     }
    },
    "deterministic_findings": [],
    "model_findings": {
     "origin": "mocked model (local candidate adapter)",
     "conditions": {
      "basis_identification": {
       "status": "pass",
       "note": "The record states this.",
       "uncertain": false
      },
      "reasoning_traceability": {
       "status": "gap",
       "note": "The record does not state how registration of two devices for the calibration logs leads to access to all engineering systems.",
       "uncertain": false
      },
      "temporal_reconstructability": {
       "status": "pass",
       "note": "The record states this.",
       "uncertain": false
      },
      "accountability_support": {
       "status": "pass",
       "note": "The record states this.",
       "uncertain": false
      },
      "cold_reviewer_clarity": {
       "status": "pass",
       "note": "The record states this.",
       "uncertain": false
      }
     },
     "findings": [
      {
       "id": "C-001",
       "kind": "condition",
       "explanation_id": "missing_logical_bridge",
       "uncertain": false,
       "explanation": {
        "label": "Missing logical bridge",
        "meaning": "The record states facts and a conclusion, but not the step that connects them.",
        "look_for": "A sentence that says why the stated facts lead to the conclusion reached.",
        "reviewer_question": "Could a later reader explain, from the record alone, how the facts led to the conclusion?",
        "category": "missing_logical_bridge",
        "codebook_correspondence": "not_asserted"
       },
       "disposition": {
        "status": "pending",
        "history": []
       },
       "condition": "reasoning_traceability",
       "condition_status": "gap",
       "model_note": "The record does not state how registration of two devices for the calibration logs leads to access to all engineering systems.",
       "anchor_note": "A candidate key concerns the record as a whole; quotations, if any, are on the flaw findings. A quotation shows presence in the record, not support."
      },
      {
       "id": "C-002",
       "kind": "flaw",
       "explanation_id": "missing_logical_bridge",
       "uncertain": false,
       "explanation": {
        "label": "Missing logical bridge",
        "meaning": "The record states facts and a conclusion, but not the step that connects them.",
        "look_for": "A sentence that says why the stated facts lead to the conclusion reached.",
        "reviewer_question": "Could a later reader explain, from the record alone, how the facts led to the conclusion?",
        "category": "missing_logical_bridge",
        "codebook_correspondence": "not_asserted"
       },
       "disposition": {
        "status": "pending",
        "history": []
       },
       "type": "reasoning_elision",
       "quotation": "approved unrestricted remote access to all engineering systems because the devices were registered",
       "model_note": "The stated reason covers the two devices and the logs requested, not the wider access recorded.",
       "anchors": [
        {
         "start": 555,
         "end": 653,
         "line": 3,
         "column": 384
        }
       ]
      }
     ],
     "model_revision_note": null
    },
    "model_output_checks": [],
    "disposition": {
     "status": "pending",
     "pending": [
      "C-001",
      "C-002"
     ],
     "history": []
    },
    "sign_off": {
     "status": "not_signed",
     "reviewer": null,
     "signed_at": null,
     "statement": null,
     "meaning": "Sign-off records that a named person reviewed every finding in this result. It is not an access decision, not an approval of the record and not a validation of the candidate.",
     "permitted_now": false
    },
    "packet_id": "8c29d9f4672fdd5fe4e7e079"
   },
   "digests": {
    "review_id": "3750c52765983f035054d3d1",
    "result_digest": "b5d9068dafae86e3119e121b3a7a01bebda7e09854840cab02a9e34933077710",
    "packet_id": "8c29d9f4672fdd5fe4e7e079",
    "packet_digest": "8b629713cdbb21d55af5c40eea80b015ed51a3970a8eca9d0676cae9e01275b0"
   },
   "human_disposition_example": {
    "opened": true,
    "source_text_checked": true,
    "standing": "ILLUSTRATIVE EXAMPLE of the local disposition workflow, written by the package author. Not a correct answer, not an independent label, not a decision.",
    "export_record": {
     "export_format": "jrs-local-disposition-record/0.1.0",
     "workspace_version": "jrs-local-reviewer-workspace/0.1.0",
     "packet": {
      "packet_version": "jrs-candidate-reviewer-packet/0.1.0",
      "review_id": "3750c52765983f035054d3d1",
      "result_digest": "b5d9068dafae86e3119e121b3a7a01bebda7e09854840cab02a9e34933077710",
      "packet_id": "8c29d9f4672fdd5fe4e7e079",
      "packet_digest": "8b629713cdbb21d55af5c40eea80b015ed51a3970a8eca9d0676cae9e01275b0",
      "candidate_version": "0.5.0-local.1",
      "source_sha256": "80060a51a24a15f82bc22b3d577b557d2a8d46e4a618d4c9a365dcfabb675fb4",
      "record_ref": "SYNTHETIC-FD-04"
     },
     "reviewer": {
      "reference": "SYNTHETIC-REVIEWER-EXAMPLE",
      "self_entered": true,
      "authenticated": false
     },
     "review_date": "2026-10-07",
     "dispositions": [
      {
       "finding_id": "C-001",
       "section": "candidate_prompts",
       "review_id": "3750c52765983f035054d3d1",
       "packet_digest": "8b629713cdbb21d55af5c40eea80b015ed51a3970a8eca9d0676cae9e01275b0",
       "disposition": "CONFIRMED_FOR_FURTHER_REVIEW",
       "note": "Example: the quoted text is present; whether the finding holds is for the reviewer.",
       "applies_only_to_this_packet": true
      },
      {
       "finding_id": "C-002",
       "section": "candidate_prompts",
       "review_id": "3750c52765983f035054d3d1",
       "packet_digest": "8b629713cdbb21d55af5c40eea80b015ed51a3970a8eca9d0676cae9e01275b0",
       "disposition": "CONFIRMED_FOR_FURTHER_REVIEW",
       "note": "Example: the quoted text is present; whether the finding holds is for the reviewer.",
       "applies_only_to_this_packet": true
      }
     ],
     "sign_off": {
      "statement": "I reviewed every finding listed in this packet and recorded a disposition for each. This sign-off is not an approval of the record, not an access decision and not a validation of the candidate.",
      "signed": true,
      "date": "2026-10-07"
     },
     "limitation": "This is a reviewer-created local disposition record. It is bound to the identified packet and version. It does not authenticate the reviewer, establish legal validity, establish semantic correctness, or authorize production use.",
     "export_digest": "e33f54be7cbc8fbfa31afffd14a3384cab24fd8bcea9a1cdd341844cefdc903e"
    },
    "export_verification": {
     "ok": true,
     "problems": []
    }
   },
   "expected": {
    "input_preparation": {
     "refusal": null,
     "refusal_codes": [],
     "source_prep_codes": [],
     "elements_missing": []
    },
    "mock_response": {
     "adapter_contract": "jrs-candidate-adapter-output/0.1.0",
     "model_id": "mock-frozen-demo",
     "model_version": "frozen-demo-0.1.0",
     "prompt_version": "candidate-prompt/0.4.0",
     "completion": "complete",
     "conditions": {
      "basis_identification": {
       "status": "pass",
       "explanation_id": "missing_identifiable_basis",
       "note": "The record states this.",
       "uncertain": false
      },
      "reasoning_traceability": {
       "status": "gap",
       "explanation_id": "missing_logical_bridge",
       "note": "The record does not state how registration of two devices for the calibration logs leads to access to all engineering systems.",
       "uncertain": false
      },
      "cold_reviewer_clarity": {
       "status": "pass",
       "explanation_id": "cold_reviewer_clarity",
       "note": "The record states this.",
       "uncertain": false
      },
      "accountability_support": {
       "status": "pass",
       "explanation_id": "accountability_support",
       "note": "The record states this.",
       "uncertain": false
      },
      "temporal_reconstructability": {
       "status": "pass",
       "explanation_id": "chronology_gap",
       "note": "The record states this.",
       "uncertain": false
      }
     },
     "findings": [
      {
       "type": "reasoning_elision",
       "quotation": "approved unrestricted remote access to all engineering systems because the devices were registered",
       "explanation_id": "missing_logical_bridge",
       "note": "The stated reason covers the two devices and the logs requested, not the wider access recorded.",
       "uncertain": false
      }
     ],
     "revision_needed": null
    },
    "candidate": {
     "adapter_called": true,
     "result_status": "examined",
     "flagged_keys": {
      "reasoning_traceability": "gap"
     },
     "finding_types": [
      "reasoning_elision"
     ],
     "finding_quotations": [
      "approved unrestricted remote access to all engineering systems because the devices were registered"
     ],
     "withheld_groups": []
    }
   },
   "does_not_establish": [
    "SYNTHETIC. Written by Claude Code (an AI) on 2026-10-07 for a local demonstration package. No real supplier, person, organisation, date or record is described or was used.",
    "The names were invented for this package and checked against a closed list in the record; resemblance to a real organisation or person is not intended and cannot be excluded by the package itself.",
    "Expected candidate behaviour is the scripted output of a deterministic mock adapter. It shows what the software does with that output, not what any real model would return.",
    "Not a sealed holdout, not independent labeling, not real-record evidence and not evidence of accuracy, reliability or validity.",
    "The candidate does not judge whether the wider access was appropriate. It reports, through a scripted mock, that the record does not show the connecting step."
   ]
  },
  {
   "record_id": "FD-05",
   "record_version": "1",
   "record_ref": "SYNTHETIC-FD-05",
   "demonstrates": "partial_record_refused_before_model_review",
   "summary": "A partial record (page 1 of 2, ending mid-sentence) that is refused before any model review.",
   "source_sha256": "a55d03f238e12659ede7db177917647e4e2a7e8350e9dba1c44c4fcfffbeca65",
   "text": "SYNTHETIC DEMONSTRATION RECORD FD-05. Fictional organisations, people, dates and facts. Not a real record.\nSupplier-access exception, completed draft. Reference SYN-FD-05. Page 1 of 2.\nOn 7 July 2031 Wyndrel Fasteners Ltd requested access to the inventory-forecast dashboard of Halvenmoor Instruments for five weeks. The supplier-access policy requires a completed security questionnaire. The security office reviewed the questionnaire and found that section 3 was",
   "fictional_entities": {
    "organisations": [
     "Wyndrel Fasteners Ltd",
     "Halvenmoor Instruments"
    ],
    "people": []
   },
   "source_preparation": {
    "version": "source-prep/0.3.0",
    "refusal": {
     "reason": "partial_input",
     "codes": [
      "pages_missing",
      "ends_mid_sentence"
     ],
     "detail": "The input appears to be incomplete (pages_missing, ends_mid_sentence). A partial record is not examined."
    },
    "findings": [
     {
      "kind": "truncation",
      "code": "pages_missing",
      "element": null,
      "matched": "Page 1 of 2",
      "detail": "Page 1 of 2 is the last page present.",
      "location": {
       "start": 172,
       "end": 183,
       "line": 2,
       "column": 66
      }
     },
     {
      "kind": "truncation",
      "code": "ends_mid_sentence",
      "element": null,
      "matched": null,
      "detail": null,
      "location": {
       "start": 463,
       "end": 464,
       "line": 3,
       "column": 279
      }
     }
    ],
    "quotations": []
   },
   "candidate": {
    "status": "refused",
    "reason": "partial_input",
    "detail": "The input appears to be incomplete (pages_missing, ends_mid_sentence). A partial record is not examined.",
    "adapter_calls": 0,
    "adapter_identity": {
     "model_id": "mock-frozen-demo",
     "model_version": "frozen-demo-0.1.0",
     "prompt_version": "candidate-prompt/0.4.0"
    },
    "conditions": null,
    "findings": [],
    "extraction_findings": [
     {
      "id": "X-001",
      "origin": "source_prep",
      "code": "pages_missing",
      "element": null
     },
     {
      "id": "X-002",
      "origin": "source_prep",
      "code": "ends_mid_sentence",
      "element": null
     }
    ]
   },
   "scope_probes": [],
   "packet": {
    "packet_version": "jrs-candidate-reviewer-packet/0.1.0",
    "status": {
     "human_review_required": true,
     "standing": "LOCAL CANDIDATE, NOT VALIDATED",
     "notice": "Produced by a local development candidate with a mocked model. It is not a decision, not a validation and not an approval. A person must read the record and every item below."
    },
    "review_identity": {
     "contract_version": "jrs-candidate-result/0.3.0",
     "candidate_version": "0.5.0-local.1",
     "source_prep_version": "source-prep/0.3.0",
     "explanation_set_version": "explanations/0.2.0",
     "prompt_sha256": "fabccb9760c06055c8415c76d12df1e38625bff08c610fdc0c14c0a839d8d8a7",
     "prompt_version": "candidate-prompt/0.4.0",
     "adapter_contract": "jrs-candidate-adapter-output/0.1.0",
     "model": "mock-frozen-demo@frozen-demo-0.1.0",
     "derived_from": "d2da83c:api/review-engine.js (0.1.0-validation)",
     "review_id": "59511768c7c06bb2e0d7ef18"
    },
    "result_digest": "8b005a0785bc367691e95a9a16c0475a6004c8b67a8a705b1f316664e5b407a9",
    "record_ref": "SYNTHETIC-FD-05",
    "source_preparation": {
     "version": "source-prep/0.3.0",
     "result_status": "refused",
     "reason": "partial_input",
     "detail": "The input appears to be incomplete (pages_missing, ends_mid_sentence). A partial record is not examined.",
     "refusal_codes": [
      "pages_missing",
      "ends_mid_sentence"
     ],
     "source": {
      "sha256": "a55d03f238e12659ede7db177917647e4e2a7e8350e9dba1c44c4fcfffbeca65",
      "chars": 464,
      "lines": 3
     }
    },
    "deterministic_findings": [
     {
      "id": "X-001",
      "kind": "truncation",
      "code": "pages_missing",
      "element": null,
      "detail": "Page 1 of 2 is the last page present.",
      "explanation": {
       "label": "Pages missing",
       "meaning": "The record numbers its pages and the last page present is not the last page.",
       "look_for": null,
       "reviewer_question": "Where are the remaining pages?",
       "category": null,
       "codebook_correspondence": "not_asserted"
      },
      "disposition": {
       "status": "pending",
       "history": []
      },
      "quotation": "Page 1 of 2",
      "anchor": {
       "start": 172,
       "end": 183,
       "line": 2,
       "column": 66
      }
     },
     {
      "id": "X-002",
      "kind": "truncation",
      "code": "ends_mid_sentence",
      "element": null,
      "detail": null,
      "explanation": {
       "label": "Record ends mid-sentence",
       "meaning": "The text stops without closing its last sentence.",
       "look_for": null,
       "reviewer_question": "Is this the complete record?",
       "category": null,
       "codebook_correspondence": "not_asserted"
      },
      "disposition": {
       "status": "pending",
       "history": []
      },
      "anchor_note": "This finding concerns something absent from the record, so there is no quotation to anchor."
     }
    ],
    "model_findings": {
     "origin": "mocked model (local candidate adapter)",
     "conditions": null,
     "findings": [],
     "model_revision_note": null
    },
    "model_output_checks": [],
    "disposition": {
     "status": "pending",
     "pending": [
      "X-001",
      "X-002"
     ],
     "history": []
    },
    "sign_off": {
     "status": "not_signed",
     "reviewer": null,
     "signed_at": null,
     "statement": null,
     "meaning": "Sign-off records that a named person reviewed every finding in this result. It is not an access decision, not an approval of the record and not a validation of the candidate.",
     "permitted_now": false
    },
    "packet_id": "0c606c6ad981e5a97b6f8276"
   },
   "digests": {
    "review_id": "59511768c7c06bb2e0d7ef18",
    "result_digest": "8b005a0785bc367691e95a9a16c0475a6004c8b67a8a705b1f316664e5b407a9",
    "packet_id": "0c606c6ad981e5a97b6f8276",
    "packet_digest": "8c883ff37cf8d2c2da724cf8acbbc33915819cef5ea4bb2e15303eaf7abd1e76"
   },
   "human_disposition_example": {
    "opened": true,
    "source_text_checked": true,
    "standing": "ILLUSTRATIVE EXAMPLE of the local disposition workflow, written by the package author. Not a correct answer, not an independent label, not a decision.",
    "export_record": {
     "export_format": "jrs-local-disposition-record/0.1.0",
     "workspace_version": "jrs-local-reviewer-workspace/0.1.0",
     "packet": {
      "packet_version": "jrs-candidate-reviewer-packet/0.1.0",
      "review_id": "59511768c7c06bb2e0d7ef18",
      "result_digest": "8b005a0785bc367691e95a9a16c0475a6004c8b67a8a705b1f316664e5b407a9",
      "packet_id": "0c606c6ad981e5a97b6f8276",
      "packet_digest": "8c883ff37cf8d2c2da724cf8acbbc33915819cef5ea4bb2e15303eaf7abd1e76",
      "candidate_version": "0.5.0-local.1",
      "source_sha256": "a55d03f238e12659ede7db177917647e4e2a7e8350e9dba1c44c4fcfffbeca65",
      "record_ref": "SYNTHETIC-FD-05"
     },
     "reviewer": {
      "reference": "SYNTHETIC-REVIEWER-EXAMPLE",
      "self_entered": true,
      "authenticated": false
     },
     "review_date": "2026-10-07",
     "dispositions": [
      {
       "finding_id": "X-001",
       "section": "source_preparation",
       "review_id": "59511768c7c06bb2e0d7ef18",
       "packet_digest": "8c883ff37cf8d2c2da724cf8acbbc33915819cef5ea4bb2e15303eaf7abd1e76",
       "disposition": "NEEDS_CLARIFICATION",
       "note": "Example: obtain the complete record. Nothing was examined.",
       "applies_only_to_this_packet": true
      },
      {
       "finding_id": "X-002",
       "section": "source_preparation",
       "review_id": "59511768c7c06bb2e0d7ef18",
       "packet_digest": "8c883ff37cf8d2c2da724cf8acbbc33915819cef5ea4bb2e15303eaf7abd1e76",
       "disposition": "NEEDS_CLARIFICATION",
       "note": "Example: obtain the complete record. Nothing was examined.",
       "applies_only_to_this_packet": true
      }
     ],
     "sign_off": {
      "statement": "I reviewed every finding listed in this packet and recorded a disposition for each. This sign-off is not an approval of the record, not an access decision and not a validation of the candidate.",
      "signed": true,
      "date": "2026-10-07"
     },
     "limitation": "This is a reviewer-created local disposition record. It is bound to the identified packet and version. It does not authenticate the reviewer, establish legal validity, establish semantic correctness, or authorize production use.",
     "export_digest": "238a720b0f7e72dede8888e3bd546e0a501d59938b490ed500097ea49a1abbf4"
    },
    "export_verification": {
     "ok": true,
     "problems": []
    }
   },
   "expected": {
    "input_preparation": {
     "refusal": "partial_input",
     "refusal_codes": [
      "ends_mid_sentence",
      "pages_missing"
     ],
     "source_prep_codes": [
      "ends_mid_sentence",
      "pages_missing"
     ],
     "elements_missing": []
    },
    "mock_response": null,
    "candidate": {
     "adapter_called": false,
     "result_status": "refused",
     "flagged_keys": {},
     "finding_types": [],
     "finding_quotations": [],
     "withheld_groups": []
    }
   },
   "does_not_establish": [
    "SYNTHETIC. Written by Claude Code (an AI) on 2026-10-07 for a local demonstration package. No real supplier, person, organisation, date or record is described or was used.",
    "The names were invented for this package and checked against a closed list in the record; resemblance to a real organisation or person is not intended and cannot be excluded by the package itself.",
    "Expected candidate behaviour is the scripted output of a deterministic mock adapter. It shows what the software does with that output, not what any real model would return.",
    "Not a sealed holdout, not independent labeling, not real-record evidence and not evidence of accuracy, reliability or validity.",
    "The refusal rests on two text heuristics (a page count and a mid-sentence ending). A partial record without those signs might not be detected."
   ]
  }
 ]
};
