// JRS frozen synthetic demonstration viewer. LOCAL, OFFLINE AND READ-ONLY. SYNTHETIC CASES ONLY.
//
// It displays data pre-generated by tools/frozen-demo/run-demo.mjs (./demo-data.js) and checks it
// against the frozen manifest with the reviewer workspace's own core (./core.js). It submits
// nothing, keeps nothing, loads nothing from outside its own origin and makes no decision about
// any record. Every value is written with textContent; nothing is parsed as HTML.
import { FROZEN_DEMO } from './demo-data.js';
import { sha256, packetDigest, verifyPacket, verifyExport, NO_CORRESPONDENCE, QUOTATION_NOTICE } from './core.js';

const D = FROZEN_DEMO;
const $ = (id) => document.getElementById(id);
function el(tag, attrs, kids) {
  const n = document.createElement(tag);
  for (const [k, v] of Object.entries(attrs || {})) if (v !== null && v !== undefined) n.setAttribute(k, v);
  for (const c of [].concat(kids === undefined ? [] : kids)) n.append(c instanceof Node ? c : document.createTextNode(String(c)));
  return n;
}
function dl(pairs) { const d = el('dl', { class: 'meta' }); for (const [k, v] of pairs) { d.append(el('dt', {}, k), el('dd', {}, v === null || v === undefined ? 'none' : String(v))); } return d; }
function clear(n) { while (n.firstChild) n.removeChild(n.firstChild); return n; }
const KEY_STATUS = { pass: 'no gap reported in the scripted output (pass)', review: 'review suggested in the scripted output', gap: 'gap reported in the scripted output' };

function renderIdentity() {
  const p = D.package;
  $('package-status').textContent = p.status;
  clear($('identity-list')).append(...Array.from(dl([
    ['Package', p.package_id + ' version ' + p.package_version], ['Package status', p.status], ['Candidate version', p.candidate_version],
    ['Prompt', p.prompt_version + ' (sha256 ' + p.prompt_sha256.slice(0, 16) + '...)'], ['Adapter', p.adapter.kind + ': ' + p.adapter.model_id + '@' + p.adapter.model_version + ' (' + p.adapter.module + ')'],
    ['Candidate source commit', p.source_commit], ['Corpus commit', p.corpus_commit],
  ]).childNodes));
}

function renderScope() {
  $('scope-text').textContent = D.scope_and_limitations.scope;
  const ul = clear($('limitations-list'));
  for (const v of Object.values(D.scope_and_limitations.limitations)) ul.append(el('li', {}, v));
}

function sourcePanel(c) {
  const p = clear($('panel-source')), sp = c.source_preparation;
  p.append(el('h3', {}, 'Deterministic source preparation (' + sp.version + ')'),
    el('p', { class: 'desc' }, 'Pattern checks of the text itself, run before any model call. A finding means a pattern was seen; no finding is not proof that nothing is missing.'));
  if (sp.refusal) p.append(el('p', { class: 'refusal' }, 'Refused before model review: ' + sp.refusal.reason + ' (' + sp.refusal.codes.join(', ') + '). ' + sp.refusal.detail));
  if (!sp.findings.length) p.append(el('p', {}, 'No source-preparation finding.'));
  for (const f of sp.findings) p.append(el('article', { class: 'item' }, [el('p', { class: 'label' }, f.kind + ' · ' + f.code + (f.element ? ' · ' + f.element : '')),
    f.matched ? el('blockquote', {}, f.matched) : '', f.location ? el('p', { class: 'note' }, 'Line ' + f.location.line + ', column ' + f.location.column + ', characters ' + f.location.start + ' to ' + f.location.end) : '',
    f.detail ? el('p', { class: 'note' }, f.detail) : '']));
  p.append(el('h3', {}, 'Exact quotation anchors in the record'));
  if (!sp.quotations.length) p.append(el('p', {}, 'No double-quoted span in the record.'));
  for (const q of sp.quotations) p.append(el('p', {}, '"' + q.text + '" at line ' + q.line + ', column ' + q.column + ' (characters ' + q.start + ' to ' + q.end + ')'));
  p.append(el('h3', {}, 'The synthetic record'), el('pre', { 'aria-label': 'Synthetic record text' }, c.text));
}

function candidatePanel(c) {
  const p = clear($('panel-candidate')), k = c.candidate;
  p.append(el('p', { class: 'desc' }, 'Output of the local candidate given the scripted mock response frozen in this case. Candidate review keys are internal prompts of the local candidate, not JRS conditions and not Codebook conditions. ' + NO_CORRESPONDENCE));
  p.append(dl([['Result status', k.status], ['Adapter calls', k.adapter_calls], ['Adapter', k.adapter_identity.model_id + '@' + k.adapter_identity.model_version + ' (scripted mock, not a live model)']]));
  if (k.status === 'refused') {
    p.append(el('p', { class: 'refusal' }, 'Not reviewed. The record was refused before model review (' + k.reason + '), and the mock adapter was called ' + k.adapter_calls + ' times. A partial record is never sent for review.'));
  }
  if (k.conditions) {
    const t = el('table', {}, el('caption', { class: 'note' }, 'Candidate-internal review keys (scripted output)'));
    t.append(el('tr', {}, [el('th', { scope: 'col' }, 'Key'), el('th', { scope: 'col' }, 'Status'), el('th', { scope: 'col' }, 'Note'), el('th', { scope: 'col' }, 'Codebook')]));
    for (const [key, v] of Object.entries(k.conditions)) t.append(el('tr', {}, [el('td', {}, key), el('td', {}, KEY_STATUS[v.status] || v.status), el('td', {}, v.note === null ? 'withheld' : v.note), el('td', {}, NO_CORRESPONDENCE)]));
    p.append(t);
  }
  p.append(el('h3', {}, 'Candidate findings, kept apart from the deterministic findings'));
  if (!k.findings.length) p.append(el('p', {}, k.status === 'refused' ? 'None: nothing was reviewed.' : 'No candidate finding in the scripted output.'));
  for (const f of k.findings) {
    const parts = [el('p', { class: 'label' }, f.id + ' · ' + (f.kind === 'flaw' ? 'flaw · ' + f.type : 'key · ' + f.condition + ' · ' + f.status) + (f.uncertain ? ' · marked uncertain' : ''))];
    if (f.quotation) { parts.push(el('blockquote', {}, f.quotation)); for (const l of f.locations) parts.push(el('p', { class: 'note' }, 'Anchor: line ' + l.line + ', column ' + l.column + ', characters ' + l.start + ' to ' + l.end)); parts.push(el('p', { class: 'note' }, QUOTATION_NOTICE)); }
    if (f.note) parts.push(el('p', {}, f.note));
    if (f.explanation_label) parts.push(el('p', { class: 'note' }, 'Explanation category (candidate-internal): ' + f.explanation_label));
    p.append(el('article', { class: 'item' }, parts));
  }
}

function packetPanel(c) {
  const p = clear($('panel-packet')), k = c.packet;
  p.append(el('p', { class: 'desc' }, 'The machine-readable packet a reviewer would receive, generated by lib/engine-candidate/reviewer-packet.js. It carries no score, no verdict and no recommendation.'));
  p.append(dl([['Packet version', k.packet_version], ['Standing', k.status.standing], ['Record reference', k.record_ref], ['Review ID', k.review_identity.review_id],
    ['Packet ID', k.packet_id], ['Result digest', k.result_digest], ['Source sha256', k.source_preparation.source ? k.source_preparation.source.sha256 : 'none'],
    ['Deterministic findings', k.deterministic_findings.length], ['Candidate findings', k.model_findings.findings.length], ['Model-output checks', k.model_output_checks.length],
    ['Pending dispositions in the packet', k.disposition.pending.join(', ') || 'none'], ['Human review required', String(k.status.human_review_required)]]));
  p.append(el('details', {}, [el('summary', {}, 'Show the full packet (JSON)'), el('pre', {}, JSON.stringify(k, null, 1))]));
}

function humanPanel(c) {
  const p = clear($('panel-human')), h = c.human_disposition_example, x = h.export_record;
  p.append(el('p', { class: 'synthetic' }, h.standing));
  p.append(el('p', { class: 'desc' }, 'Run through the local reviewer workspace core: the packet was opened with its source text, each finding given a disposition, the session signed off and the record exported. The example reviewer is fictional and self-entered; nothing is authenticated.'));
  p.append(dl([['Reviewer reference', x.reviewer.reference + ' (self-entered, not authenticated)'], ['Review date', x.review_date], ['Export format', x.export_format], ['Export digest', x.export_digest],
    ['Export check when generated', h.export_verification.ok ? 'matches its packet' : 'does not match its packet']]));
  if (!x.dispositions.length) p.append(el('p', {}, 'This packet has no finding to dispose of. The example records only the sign-off statement.'));
  else {
    const t = el('table', {}, el('caption', { class: 'note' }, 'Example dispositions'));
    t.append(el('tr', {}, [el('th', { scope: 'col' }, 'Finding'), el('th', { scope: 'col' }, 'Section'), el('th', { scope: 'col' }, 'Disposition'), el('th', { scope: 'col' }, 'Note')]));
    for (const d of x.dispositions) t.append(el('tr', {}, [el('td', {}, d.finding_id), el('td', {}, d.section), el('td', {}, d.disposition), el('td', {}, d.note)]));
    p.append(t);
  }
  p.append(el('h3', {}, 'Sign-off statement'), el('p', {}, x.sign_off.statement), el('p', { class: 'note' }, x.limitation));
}

function limitsPanel(c) {
  const p = clear($('panel-limits'));
  p.append(el('p', { class: 'desc' }, 'What the replay of this case does not establish.'));
  p.append(el('ul', { class: 'limits' }, c.does_not_establish.map((s) => el('li', {}, s))));
}

function showCase(i) {
  const c = D.cases[i];
  $('case-summary').textContent = c.record_id + ' (' + c.record_ref + ', version ' + c.record_version + ', source sha256 ' + c.source_sha256.slice(0, 16) + '...): ' + c.summary;
  const rb = $('refusal-banner');
  if (c.candidate.status === 'refused') { rb.hidden = false; rb.textContent = 'Refusal case: this record is partial and was refused before any model review (' + c.candidate.reason + '). The adapter was not called.'; }
  else { rb.hidden = true; rb.textContent = ''; }
  sourcePanel(c); candidatePanel(c); packetPanel(c); humanPanel(c); limitsPanel(c);
}

function selectTab(tab) {
  for (const t of document.querySelectorAll('[role="tab"]')) {
    const on = t === tab;
    t.setAttribute('aria-selected', on ? 'true' : 'false'); t.tabIndex = on ? 0 : -1;
    $(t.getAttribute('aria-controls')).hidden = !on;
  }
}

function checkManifest() {
  const list = clear($('check-list')), out = [];
  const add = (ok, text) => { out.push(ok); list.append(el('li', { class: ok ? 'ok' : 'bad' }, (ok ? 'Matches: ' : 'Does not match: ') + text)); };
  add(D.package.status === D.manifest_check.status && D.package.status === 'DEMO_PREPARATION_COMPLETE_NOT_RELEASED', 'package status ' + D.package.status);
  add(D.cases.length === D.manifest_check.records.length, D.cases.length + ' synthetic cases listed in the manifest');
  for (const c of D.cases) {
    const m = D.manifest_check.records.find((r) => r.record_id === c.record_id);
    if (!m) { add(false, c.record_id + ' is not in the manifest'); continue; }
    add(sha256(c.text) === m.source_sha256 && c.source_sha256 === m.source_sha256, c.record_id + ' record text hash');
    add(packetDigest(c.packet) === m.expected_digests.packet_digest && c.packet.result_digest === m.expected_digests.result_digest && c.packet.review_identity.review_id === m.expected_digests.review_id, c.record_id + ' packet and result digests');
    add(verifyPacket(c.packet, { sourceText: c.text }).ok, c.record_id + ' packet opens under the workspace rules, anchors checked against the text');
    add(verifyExport(c.human_disposition_example.export_record, c.packet).ok, c.record_id + ' example export is bound to its packet');
    add(/^SYNTHETIC-/.test(c.packet.record_ref), c.record_id + ' packet carries its synthetic label');
  }
  const all = out.every(Boolean);
  $('check-status').textContent = all ? 'The data on this page matches the frozen manifest (' + out.length + ' checks). This shows exact replay of the fixed package, nothing more.' : 'The data on this page does not match the frozen manifest. Do not use it.';
}

renderIdentity(); renderScope();
const sel = $('case-select');
D.cases.forEach((c, i) => sel.append(el('option', { value: String(i) }, c.record_id + ': ' + c.demonstrates.replace(/_/g, ' '))));
sel.addEventListener('change', () => showCase(Number(sel.value)));
const tabs = [...document.querySelectorAll('[role="tab"]')];
tabs.forEach((t, i) => {
  t.addEventListener('click', () => selectTab(t));
  t.addEventListener('keydown', (e) => {
    const n = e.key === 'ArrowRight' ? (i + 1) % tabs.length : e.key === 'ArrowLeft' ? (i + tabs.length - 1) % tabs.length : e.key === 'Home' ? 0 : e.key === 'End' ? tabs.length - 1 : -1;
    if (n >= 0) { e.preventDefault(); selectTab(tabs[n]); tabs[n].focus(); }
  });
});
$('check-btn').addEventListener('click', checkManifest);
showCase(0);
