// JRS internal release-gate package: non-public Markdown report.
// INTERNAL ONLY. Deterministic: the report is a pure function of the record, with no clock,
// so it can be regenerated and byte-compared. It refuses to render an invalid record.
import { validateRecord } from './validator.js';
import { GATES, NOT_A_CLEARANCE, REPORT_VERSION, VALIDATOR_VERSION, EVIDENCE_CLASSES } from './vocabulary.js';

const cell = (s) => String(s === null || s === undefined ? '' : s).replace(/\|/g, '\\|').replace(/\n/g, ' ');

export function renderReport(record) {
  const v = validateRecord(record);
  if (!v.valid) throw new Error('refusing to render an invalid record:\n' + v.errors.join('\n'));
  const ev = new Map(record.evidence.map((e) => [e.evidence_id, e]));
  const L = [];
  L.push('# Current release-gate report (internal)');
  L.push('');
  L.push('**Internal and non-public.** Generated by `lib/release-gate/cli.mjs` from `' + 'lib/release-gate/records/' + recordFileName(record) + '`. Do not edit by hand: regenerate it, and the release-gate tests fail if the two differ.');
  L.push('');
  L.push(NOT_A_CLEARANCE);
  L.push('');
  L.push('## Identity');
  L.push('| Field | Value |');
  L.push('|---|---|');
  L.push('| Record schema | `' + record.schema_version + '` |');
  L.push('| Release package | `' + record.release_package.package_id + '` version ' + record.release_package.package_version + ' (' + record.release_package.record_kind + ', not the public Manifest) |');
  L.push('| Record date | ' + record.as_of + ' |');
  L.push('| Record author | ' + cell(record.record_author) + ' |');
  L.push('| Engine version | `' + record.engine.engine_version + '` |');
  L.push('| Candidate source commit | `' + record.engine.candidate_source_commit + '` |');
  L.push('| Prompt | `' + record.engine.prompt_version + '`, sha256 `' + record.engine.prompt_sha256 + '` |');
  L.push('| Configuration | ' + cell(record.engine.configuration_identity) + ' |');
  L.push('| Validator / report | `' + VALIDATOR_VERSION + '` / `' + REPORT_VERSION + '` |');
  L.push('');
  L.push('## Conclusion');
  L.push(v.conclusion === 'INCOMPLETE_GATES_OPEN'
    ? '**INCOMPLETE_GATES_OPEN.** The release package is incomplete. ' + passedSentence(record) + ' The Engine named above is a controlled development candidate; an open gate records absent evidence, not a defect in the candidate.'
    : '**ALL_GATES_RECORDED_PASS.** Every gate records PASS with evidence that met the validator rules. This report is still not an authorization: authorization is the owner decision recorded on RG-4, within the limitations below.');
  L.push('');
  L.push('| Gate | Name | Status | Basis |');
  L.push('|---|---|---|---|');
  for (const def of GATES) { const g = record.gates.find((x) => x.gate_id === def.id); L.push('| ' + def.id + ' | ' + cell(def.name) + ' | **' + g.status + '** | ' + cell(g.status_basis) + ' |'); }
  L.push('');
  L.push('Authorizations created by this record: production **no**, licensing **no**, sale **no**, evaluation **no**, real-record use **no**.');
  L.push('');
  for (const def of GATES) {
    const g = record.gates.find((x) => x.gate_id === def.id);
    L.push('## ' + def.id + '. ' + def.name);
    L.push('- **Status:** ' + g.status + '. ' + g.status_basis);
    L.push('- **Acceptance criterion:** ' + g.acceptance_criterion);
    L.push('- **Actual result:** ' + (g.actual_result === null ? 'none recorded' : g.actual_result));
    L.push('- **Evidence date:** ' + (g.evidence_date === null ? 'none' : g.evidence_date));
    if (def.prerequisites.length) L.push('- **Prerequisites:** ' + def.prerequisites.join(', ') + ' must pass with valid evidence first.');
    L.push('- **Owner decision:** ' + (g.owner_decision ? g.owner_decision.decision + ' by ' + g.owner_decision.decided_by + ' on ' + g.owner_decision.decision_date + ' (' + g.owner_decision.evidence_id + ')' : 'none recorded'));
    L.push('- **Independent reviewer:** ' + (g.independent_reviewer ? g.independent_reviewer.identity + ', ' + g.independent_reviewer.role + ', ' + g.independent_reviewer.organisation : (def.independent_reviewer_required ? 'none recorded (required for PASS)' : 'not required')));
    L.push('- **Limitation:** ' + g.limitation_statement);
    L.push('');
    L.push('| Sub-control | Status | Evidence | Missing |');
    L.push('|---|---|---|---|');
    for (const s of g.sub_controls) L.push('| ' + s.control_id + ' ' + cell(s.name) + ' | ' + s.status + ' | ' + (s.evidence_refs.join(', ') || 'none') + ' | ' + cell(s.missing_dependencies.join('; ') || (s.not_applicable_reason || '')) + ' |');
    L.push('');
    if (g.missing_dependencies.length) { L.push('**Missing at gate level:**'); for (const d of g.missing_dependencies) L.push('- ' + d); L.push(''); }
    if (g.evidence_refs.length) L.push('Evidence considered: ' + g.evidence_refs.map((r) => r + ' (' + ev.get(r).evidence_class + ')').join(', ') + '.');
    else L.push('Evidence considered: none.');
    L.push('');
  }
  L.push('## Evidence register');
  L.push('A class marked "never passes a gate" can describe context but cannot satisfy any release requirement.');
  L.push('');
  L.push('| ID | Class | Provenance | Kind | Reference | sha256 | Date | Limitation |');
  L.push('|---|---|---|---|---|---|---|---|');
  for (const e of record.evidence) L.push('| ' + e.evidence_id + ' | ' + e.evidence_class + (EVIDENCE_CLASSES[e.evidence_class].production_evidence ? '' : ' (never passes a gate)') + ' | ' + e.provenance + ' | ' + e.artifact_kind + ' | `' + cell(e.reference) + '` | `' + e.sha256.slice(0, 16) + '…` | ' + e.evidence_date + ' | ' + cell(e.limitation) + ' |');
  L.push('');
  L.push('## Limitations');
  for (const l of record.package_limitations) L.push('- ' + l);
  L.push('');
  return L.join('\n');
}

function passedSentence(record) {
  const passed = GATES.filter((d) => record.gates.find((g) => g.gate_id === d.id).status === 'PASS').map((d) => d.id);
  if (!passed.length) return 'No release gate has passed, and every gate below remains open.';
  return passed.length + ' of ' + GATES.length + ' gates record PASS (' + passed.join(', ') + '); the others remain open.';
}

export function recordFileName(record) {
  return 'RG-RECORD_engine-' + record.engine.engine_version + '.json';
}

// A report is acceptable only if it carries the fixed statement, every package limitation,
// every gate limitation, and the conclusion the record actually supports.
export function reportProblems(markdown, record) {
  const v = validateRecord(record);
  if (!v.valid) return ['record is invalid'];
  const p = [];
  if (!markdown.includes(NOT_A_CLEARANCE)) p.push('report omits the not-a-clearance statement');
  if (!/^## Limitations$/m.test(markdown)) p.push('report has no Limitations section');
  for (const l of record.package_limitations) if (!markdown.includes(l)) p.push('report omits package limitation: ' + l.slice(0, 60));
  for (const g of record.gates) if (!markdown.includes(g.limitation_statement)) p.push('report omits the ' + g.gate_id + ' limitation');
  if (!markdown.includes('**' + v.conclusion + '.**')) p.push('report does not state the conclusion ' + v.conclusion);
  if (v.conclusion === 'INCOMPLETE_GATES_OPEN' && markdown.includes('ALL_GATES_RECORDED_PASS')) p.push('report claims every gate passed');
  return p;
}
