#!/usr/bin/env node
// JRS methodology integrity: register builder. INTERNAL, LOCAL ONLY.
//   node tools/methodology-integrity/build.mjs           validate and print a summary
//   node tools/methodology-integrity/build.mjs --write   also write the registers, their Markdown and the workspace snapshot
//   node tools/methodology-integrity/build.mjs --check   fail unless every committed output equals a fresh build
//
// Reads the working tree only (no git, no network). Refuses to build when a methodology source no
// longer has the hash it was reviewed at, or when any record breaks a register rule.
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { createHash } from 'node:crypto';
import { SOURCES, DECISION_RECORDS, CONDITION_NAMES } from './lib/sources.js';
import { RECORDS } from './lib/records.js';
import { validateRegister, statusSummary, NOTICE } from './lib/validate.js';
import { resolveCodebookLabel, approvedSnapshot } from './lib/resolve.js';

export const ROOT = new URL('../../', import.meta.url).pathname;
export const REGISTER_VERSION = 'jrs-methodology-correspondence-register/0.1.0';
export const OUTPUTS = Object.freeze({
  sources: 'tools/methodology-integrity/source-register.json',
  register: 'tools/methodology-integrity/current-correspondence-register.json',
  sourcesMd: 'docs/architecture/METHODOLOGY_SOURCE_REGISTER.md',
  registerMd: 'docs/architecture/METHODOLOGY_CORRESPONDENCE_REGISTER.md',
  snapshot: 'tools/local-reviewer-workspace/app/correspondence.js',
});
const sha = (b) => createHash('sha256').update(b).digest('hex');
export const canon = (v) => Array.isArray(v) ? '[' + v.map(canon).join(',') + ']' : v && typeof v === 'object' ? '{' + Object.keys(v).sort().map((k) => JSON.stringify(k) + ':' + canon(v[k])).join(',') + '}' : JSON.stringify(v === undefined ? null : v);
export const SCHEMA = JSON.parse(readFileSync(new URL('./schema/correspondence-record.schema.json', import.meta.url), 'utf8'));

export function buildSourceRegister(root = ROOT) {
  const problems = [];
  const hashFile = (path, reviewed, id) => {
    if (!existsSync(join(root, path))) { problems.push(id + ': ' + path + ' not found'); return null; }
    const buf = readFileSync(join(root, path)), h = sha(buf);
    if (h !== reviewed) problems.push(id + ': ' + path + ' has changed since it was reviewed (now ' + h.slice(0, 12) + ', reviewed ' + reviewed.slice(0, 12) + '); review the source before re-binding');
    return { sha256: reviewed, bytes: buf.length };
  };
  const sources = SOURCES.map((s) => ({ ...s, ...hashFile(s.path, s.reviewed_sha256, s.id) })).map(({ reviewed_sha256, ...s }) => s);
  const decisions = DECISION_RECORDS.map((d) => ({ ...d, ...hashFile(d.path, d.reviewed_sha256, d.id) })).map(({ reviewed_sha256, ...d }) => d);
  const canonical = sources.filter((s) => s.status === 'CANONICAL').map((s) => s.id);
  return { problems, register: { register_version: 'jrs-methodology-source-register/0.1.0', hash_basis: 'sha256 of the file bytes as reviewed; the builder refuses to run if the working-tree file differs',
    condition_names: CONDITION_NAMES, canonical_sources: canonical,
    canonical_codebook: canonical.includes('SRC-CODEBOOK') ? 'SRC-CODEBOOK (codebook.html v1.0), on the page\'s own statement and owner decision D-3' : 'NOT ESTABLISHED',
    sources, correspondence_decision_records: decisions } };
}

export function buildRegister(sourceRegister) {
  const records = RECORDS.map((r) => {
    const s = sourceRegister.sources.find((x) => x.id === r.methodology_source_id);
    return { ...r, methodology_source_sha256: s ? s.sha256 : null };
  });
  return { register_version: REGISTER_VERSION, record_schema: 'tools/methodology-integrity/schema/correspondence-record.schema.json',
    governing_rule: 'A shared word, a similar concept or a plausible interpretation does not establish a formal mapping. Without an owner-approved record, the status is UNMAPPED, PROPOSED_NOT_APPROVED, HISTORICAL_REFERENCE_ONLY, NOT_ASSESSED or RETIRED, and the display is "' + NOTICE + '"',
    source_register_digest: sha(canon(sourceRegister)), record_count: records.length, status_summary: statusSummary(records), records_digest: sha(canon(records)), records };
}

// ---- Markdown ---------------------------------------------------------------------------------
const cell = (s) => String(s === null || s === undefined ? '' : s).replace(/\|/g, '\\|').replace(/\n/g, ' ');
const table = (head, rows) => '| ' + head.join(' | ') + ' |\n|' + head.map(() => '---').join('|') + '|\n' + rows.map((r) => '| ' + r.map(cell).join(' | ') + ' |').join('\n') + '\n';

export function renderSourcesMd(sr) {
  return '# Methodology Source Register\n\n'
    + '**Internal, generated, not deployed.** Generated by `tools/methodology-integrity/build.mjs` from `tools/methodology-integrity/lib/sources.js`. Machine form: `' + OUTPUTS.sources + '`. Do not edit by hand.\n\n'
    + 'A source is CANONICAL only where repository evidence names it as authoritative. A filename is not evidence. Each hash is the sha256 of the file as reviewed for this register; the builder refuses to run when a file no longer has that hash.\n\n'
    + '**Canonical Codebook:** ' + sr.canonical_codebook + '.\n\n'
    + '## Sources\n\n' + table(['ID', 'Name', 'Path', 'Version or date', 'sha256', 'Classification', 'Status'], sr.sources.map((s) => [s.id, s.name, '`' + s.path + '`', s.version, '`' + s.sha256 + '`', s.classification, s.status]))
    + '\n## Evidence and limitations\n\n' + sr.sources.map((s) => '### ' + s.id + ' (' + s.status + ')\n\n' + s.evidence + '\n\n' + s.limitations.map((l) => '- ' + l).join('\n') + '\n'
      + (s.condition_locations ? '\nCondition locations: ' + Object.entries(s.condition_locations).map(([k, v]) => k + ' (' + v + ')').join('; ') + '.\n' : '')).join('\n')
    + '\n## Correspondence decision records\n\nThese are evidence about correspondence. They are not methodology sources.\n\n'
    + table(['ID', 'Path', 'sha256', 'Summary'], sr.correspondence_decision_records.map((d) => [d.id, '`' + d.path + '`', '`' + d.sha256.slice(0, 16) + '…`', d.summary]));
}

export function renderRegisterMd(reg) {
  const row = (r) => [r.correspondence_id, r.term_category, '`' + r.candidate_term + '`', r.status, r.mapping_type,
    r.methodology_source_id ? r.methodology_source_id + ' `' + r.methodology_source_sha256.slice(0, 12) + '`' : 'none',
    r.authoritative_source_term || (r.proposal ? 'proposed, not approved: ' + r.proposal.proposed_source_term : 'none'),
    r.owner_approval.approved ? r.owner_approval.approval_date : 'none', r.limitation];
  const cats = [...new Set(reg.records.map((r) => r.term_category))];
  return '# Methodology Correspondence Register\n\n'
    + '**Internal, generated, not deployed.** Generated by `tools/methodology-integrity/build.mjs` from `tools/methodology-integrity/lib/records.js`. Machine form: `' + OUTPUTS.register + '`. Record schema: `' + reg.record_schema + '`. Do not edit by hand.\n\n'
    + '**Governing rule.** ' + reg.governing_rule + '\n\n'
    + 'An approved record needs the authoritative source version, the exact source location, the exact candidate term, the mapping type, the evidence basis, the status, and an owner-approved interpretation date. **No record in this register is approved.** Where a row names a proposal, the proposal is recorded and not approved, and no correspondence is asserted.\n\n'
    + '## Status summary\n\n' + table(['Status', 'Records'], Object.entries(reg.status_summary).map(([k, v]) => [k, v])) + '\nTotal: ' + reg.record_count + ' records. Records digest `' + reg.records_digest + '`.\n'
    + cats.map((c) => '\n## ' + c + '\n\n' + table(['ID', 'Category', 'Term', 'Status', 'Mapping type', 'Source', 'Source term', 'Owner approval', 'Limitation'], reg.records.filter((r) => r.term_category === c).map(row))).join('')
    + '\n## Evidence basis by record\n\n' + reg.records.map((r) => '- **' + r.correspondence_id + '** `' + r.candidate_term + '` (' + r.term_location.path + ', ' + r.term_location.reference + '): ' + r.evidence_basis
      + (r.proposal ? ' Proposal reference: ' + r.proposal.reference + '. ' + r.proposal.note : '') + (r.source_reference ? ' Source location: ' + r.source_reference + '.' : '')
      + (r.status !== 'APPROVED_CORRESPONDENCE' && r.term_category !== 'JRS_CONDITION' ? ' ' + NOTICE : '')).join('\n') + '\n';
}

export function renderSnapshot(reg, sr) {
  const approved = approvedSnapshot(reg, sr.sources);
  return '// GENERATED by tools/methodology-integrity/build.mjs from tools/methodology-integrity/current-correspondence-register.json.\n'
    + '// Do not edit by hand. A mapped label renders only from an owner-approved record with its source\n'
    + '// hash and approval date; every other term renders the unmapped notice. Register records digest:\n'
    + '// ' + reg.records_digest + '\n'
    + "export const NO_CORRESPONDENCE = '" + NOTICE + "';\n"
    + 'export const APPROVED_CORRESPONDENCE = Object.freeze(' + JSON.stringify(approved) + ');\n'
    + 'export ' + resolveCodebookLabel.toString() + '\n'
    + 'export function codebookCorrespondenceText(category, term) { return resolveCodebookLabel(APPROVED_CORRESPONDENCE, category, term).text; }\n';
}

export function buildAll(root = ROOT) {
  const s = buildSourceRegister(root);
  const reg = buildRegister(s.register);
  const problems = s.problems.concat(validateRegister(reg, { schema: SCHEMA, sources: s.register.sources, exists: (p) => existsSync(join(root, p)) }));
  for (const r of reg.records) if (!existsSync(join(root, r.term_location.path))) problems.push(r.correspondence_id + ': term location ' + r.term_location.path + ' not found');
  const out = {
    [OUTPUTS.sources]: JSON.stringify(s.register, null, 1) + '\n',
    [OUTPUTS.register]: JSON.stringify(reg, null, 1) + '\n',
    [OUTPUTS.sourcesMd]: renderSourcesMd(s.register),
    [OUTPUTS.registerMd]: renderRegisterMd(reg),
    [OUTPUTS.snapshot]: renderSnapshot(reg, s.register),
  };
  for (const [p, t] of Object.entries(out)) if (/—/.test(t)) problems.push(p + ': contains an em dash');
  return { problems, out, sourceRegister: s.register, register: reg };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const args = process.argv.slice(2);
  const { problems, out, register } = buildAll(ROOT);
  if (problems.length) { for (const p of problems) console.error('REFUSED  ' + p); process.exit(1); }
  console.log(register.record_count + ' records  ' + Object.entries(register.status_summary).map(([k, v]) => k + '=' + v).join(' '));
  if (args.includes('--check')) {
    const stale = Object.entries(out).filter(([p, t]) => !existsSync(join(ROOT, p)) || readFileSync(join(ROOT, p), 'utf8') !== t).map(([p]) => p);
    if (stale.length) { for (const p of stale) console.log('STALE  ' + p); process.exit(1); }
    console.log('PASS  committed registers, Markdown and workspace snapshot equal a fresh build');
  }
  if (args.includes('--write')) for (const [p, t] of Object.entries(out)) { mkdirSync(dirname(join(ROOT, p)), { recursive: true }); writeFileSync(join(ROOT, p), t); console.log('wrote ' + p); }
}
