#!/usr/bin/env python3
"""Comprehensive repository audit. Writes REPOSITORY_AUDIT_REPORT.md.

Inventories every HTML page, API route, markdown document and asset, then runs
health checks over navigation, sitemap, offer configuration and lead capture.

Every figure is measured from the filesystem or from a live probe. Nothing is
recalled. Where a value cannot be established the report says so rather than
guessing.

Usage:
  python3 scripts/repo_audit.py             # offline inventory + live GET probes
  python3 scripts/repo_audit.py --offline   # no network at all
"""
import io
import json
import os
import re
import subprocess
import sys
import urllib.error
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "REPOSITORY_AUDIT_REPORT.md")
BASE = "https://www.jrsstandard.com"
OFFLINE = "--offline" in sys.argv

SKIP_DIRS = {".git", "node_modules", "__pycache__", ".vercel", ".github"}

# Private surfaces. Named explicitly so the sitemap check can assert they are
# ABSENT rather than merely not noticing them.
PRIVATE_SLUGS = [
    "programme-status-9872fb93cc94.html",
    "acquisition-9f3c2a7d4b.html",
    "vp-7c1f9a4e8d2b6035.html",
]
PRIVATE_API = [
    "api/leads-4b7e2c9af106d385.js",
    "api/people-9dd1ecdf6f8cdfd4.js",
    "api/roster-8c3f1a9e7b2d6045.js",
    "api/geo-4e8b2d7f9a1c3065.js",
    "api/variance-6b1d90fa2c47e8b3.js",
]


def walk(pred):
    out = []
    for base, dirs, files in os.walk(ROOT):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
        for f in files:
            rel = os.path.relpath(os.path.join(base, f), ROOT)
            if pred(rel, f):
                out.append(rel)
    return sorted(out)


def read(rel):
    try:
        return io.open(os.path.join(ROOT, rel), encoding="utf-8", errors="replace").read()
    except Exception:
        return ""


def size(rel):
    try:
        return os.path.getsize(os.path.join(ROOT, rel))
    except Exception:
        return 0


def human(n):
    for unit in ("B", "KB", "MB"):
        if n < 1024 or unit == "MB":
            return "%.0f %s" % (n, unit) if unit == "B" else "%.1f %s" % (n, unit)
        n /= 1024.0


def probe(path, method="GET"):
    """Live status code for one path. None when offline or unreachable."""
    if OFFLINE:
        return None
    req = urllib.request.Request(BASE + path, method=method)
    try:
        with urllib.request.urlopen(req, timeout=25) as r:
            return r.status
    except urllib.error.HTTPError as e:
        return e.code
    except Exception:
        return None


def probe_json(path):
    if OFFLINE:
        return None
    try:
        with urllib.request.urlopen(BASE + path, timeout=25) as r:
            return json.loads(r.read().decode())
    except Exception:
        return None


# ------------------------------------------------------------------ inventory
html = walk(lambda rel, f: f.endswith(".html") and not rel.startswith("research" + os.sep))
research_html = walk(lambda rel, f: f.endswith(".html") and rel.startswith("research" + os.sep))
api = walk(lambda rel, f: rel.startswith("api" + os.sep) and f.endswith(".js"))
scripts = walk(lambda rel, f: rel.startswith("scripts" + os.sep)
               and f.endswith((".py", ".sh", ".mjs", ".sql")))
md_root = walk(lambda rel, f: f.endswith(".md") and os.sep not in rel)
md_research = walk(lambda rel, f: f.endswith(".md") and rel.startswith("research" + os.sep))
pdfs = walk(lambda rel, f: f.endswith(".pdf"))
docx = walk(lambda rel, f: f.endswith(".docx"))
csvs = walk(lambda rel, f: f.endswith(".csv"))
other_assets = walk(lambda rel, f: f.endswith((".svg", ".png", ".jpg", ".jpeg", ".ico", ".webmanifest", ".xml", ".txt", ".json"))
                    and not rel.startswith("research" + os.sep))

L = []
def w(s=""):
    L.append(s)


w("# Repository Audit Report")
w()
w("**Repository:** `phillipwikes-bit/jrsstandard.com`  ")
w("**Generated by:** `scripts/repo_audit.py`  ")
w("**Mode:** %s" % ("offline inventory only" if OFFLINE else "filesystem inventory plus live production probes"))
w()
w("Every figure below is measured from the filesystem or from a live HTTP probe at the "
  "moment of generation. Nothing is recalled from memory. Where a value cannot be "
  "established, the report says so rather than estimating.")
w()
w("---")
w()

# ------------------------------------------------------------ 1. architecture
w("## 1. Core Architecture and File Tree")
w()
w("| Category | Count | Notes |")
w("|---|---|---|")
w("| Public HTML pages | %d | Served at the domain root and under `/reference/` |" % len(html))
w("| Research HTML (never deployed) | %d | Under `research/`, excluded from every deploy |" % len(research_html))
w("| API routes | %d | Vercel Edge Functions under `api/` |" % len(api))
w("| Build and audit scripts | %d | `scripts/`, not served |" % len(scripts))
w("| Root markdown documents | %d | Internal, see the exposure note in section 5 |" % len(md_root))
w("| Research markdown | %d | Under `research/` |" % len(md_research))
w("| PDF assets | %d | Served through `/api/dl` alias map |" % len(pdfs))
w("| DOCX artefacts | %d | Generated deliverables |" % len(docx))
w("| CSV data | %d | |" % len(csvs))
w("| Other static assets | %d | SVG, icons, XML, TXT, JSON |" % len(other_assets))
w()

w("### 1.1 Public HTML pages")
w()
w("| Page | Size | Title |")
w("|---|---|---|")
for p in html:
    t = re.search(r"<title>(.*?)</title>", read(p), re.S)
    title = re.sub(r"\s+", " ", t.group(1)).strip()[:70] if t else "(no title)"
    w("| `%s` | %s | %s |" % (p, human(size(p)), title))
w()

w("### 1.2 API routes")
w()
w("| Route | Lines | Runtime | Purpose (first descriptive comment) |")
w("|---|---|---|---|")
for p in api:
    body = read(p)
    lines = body.count("\n") + 1
    runtime = "edge" if "runtime: 'edge'" in body else "node/module"
    desc = ""
    for ln in body.split("\n"):
        s = ln.strip()
        if s.startswith("//") and len(s) > 8 and "====" not in s:
            desc = s.lstrip("/ ").strip()
            if len(desc) > 12:
                break
    w("| `/%s` | %d | %s | %s |" % (p.replace(".js", "").replace("api/", "api/"),
                                    lines, runtime, desc[:90]))
w()

w("### 1.3 Static asset folders")
w()
folders = {}
for p in pdfs + other_assets + csvs:
    d = os.path.dirname(p) or "(root)"
    folders.setdefault(d, 0)
    folders[d] += 1
w("| Folder | Asset count |")
w("|---|---|")
for d in sorted(folders):
    w("| `%s` | %d |" % (d, folders[d]))
w()
w("---")
w()

# ------------------------------------------------- 2. public and educational
w("## 2. Public and Educational Track Assets")
w()
w("### 2.1 Training modules")
w()
tr = read("training.html")
mods = re.findall(r"toggleModule\((\d+)\)", tr)
mod_titles = re.findall(r'class="module-title"[^>]*>([^<]{3,90})<', tr)
w("`training.html` is a single-page six-module system, not six separate files. "
  "Modules are panels toggled by `toggleModule(idx)` and completion state is held in "
  "the single `localStorage` key `jrs-training-progress`.")
w()
w("| Signal | Measured value |")
w("|---|---|")
w("| Distinct module indices bound in markup | %s |" % (", ".join(sorted(set(mods))) or "none found"))
w("| Module title elements | %d |" % len(mod_titles))
w("| `markComplete(` handlers | %d |" % tr.count("markComplete("))
w("| localStorage key | `%s` |" % ("jrs-training-progress" if "jrs-training-progress" in tr else "NOT FOUND"))
w("| Survey handlers | `surveyScale` %d, `surveyChoice` %d |" % (tr.count("surveyScale("), tr.count("surveyChoice(")))
w("| Role gate | `selectRole(` %d occurrences |" % tr.count("selectRole("))
w("| Completion POST | `%s` |" % ("/api/complete" if "/api/complete" in tr else "NOT WIRED"))
if mod_titles:
    w()
    w("Module titles found in markup:")
    w()
    for i, t in enumerate(mod_titles, 1):
        w("%d. %s" % (i, re.sub(r"\s+", " ", t).strip()))
w()

w("### 2.2 Certification and completion surfaces")
w()
cert_pages = [p for p in html if re.search(r"cert|complete|honor", p, re.I)]
w("| Surface | Type |")
w("|---|---|")
for p in cert_pages:
    w("| `%s` | page |" % p)
for p in api:
    if re.search(r"cert|complete|honor", p, re.I):
        w("| `/%s` | API route |" % p.replace(".js", ""))
w()

w("### 2.3 Investigator Field Guides")
w()
dl = read("api/dl.js")
alias = re.findall(r"'([A-Za-z0-9_.\-]+\.pdf)'", dl)
guide_editions = re.findall(r"'([a-z0-9\-]+)'\s*:\s*'([A-Za-z0-9_.\-]+\.pdf)'", dl)
w("PDFs are not linked directly. They are served through the alias map in `api/dl.js`, "
  "which records each download before serving.")
w()
w("| PDF file | On disk | Size |")
w("|---|---|---|")
for p in sorted(set(pdfs)):
    base = os.path.basename(p)
    w("| `%s` | yes | %s |" % (base, human(size(p))))
w()
if guide_editions:
    w("Alias keys mapped in `api/dl.js`:")
    w()
    w("| Alias | Target PDF |")
    w("|---|---|")
    for k, v in guide_editions:
        w("| `?e=%s` | `%s` |" % (k, v))
    w()
unmapped = [os.path.basename(p) for p in pdfs if os.path.basename(p) not in dl]
w("**PDFs present on disk but absent from the `api/dl.js` alias map:** %s"
  % (", ".join("`%s`" % u for u in unmapped) if unmapped else "none"))
w()

w("### 2.4 Articles, whitepapers and manuscripts")
w()
manu = []
for p in md_research + md_root:
    body = read(p)
    head = body[:400]
    if re.search(r"^#\s", head, re.M) and re.search(
            r"article|manuscript|whitepaper|deficit|draft|paper", p + head, re.I):
        t = re.search(r"^#\s+(.+)$", body, re.M)
        manu.append((p, re.sub(r"\s+", " ", t.group(1)).strip()[:90] if t else ""))
w("| Document | Title |")
w("|---|---|")
for p, t in manu[:60]:
    w("| `%s` | %s |" % (p, t))
w()
w("**Total manuscript-class documents matched:** %d. All are under `research/` or the "
  "repository root and none is deployed to production." % len(manu))
w()
w("---")
w()

# ------------------------------------------------------ 3. research and pilot
w("## 3. Research and Pilot Program Assets")
w()
research_pages = [p for p in html if re.search(
    r"pilot|research|bench|reviewer|study|finding|simulation|challenge|access|supported|contributor|coauthor|honor|org-pilot",
    p, re.I)]
w("| Page | Size | Purpose signal |")
w("|---|---|---|")
for p in research_pages:
    body = read(p)
    t = re.search(r"<title>(.*?)</title>", body, re.S)
    w("| `%s` | %s | %s |" % (p, human(size(p)),
                              re.sub(r"\s+", " ", t.group(1)).strip()[:60] if t else ""))
w()
w("### 3.1 Enterprise Diagnostic Pilot interface")
w()
for cand in ("pilot.html", "org-pilot.html"):
    exists = cand in html
    w("- `%s`: %s%s" % (cand, "present" if exists else "**ABSENT**",
                        ", %s" % human(size(cand)) if exists else ""))
op = read("api/org-pilot.js")
w()
w("`api/org-pilot.js` is the recorder. Verified properties, read from source:")
w()
w("| Property | Value |")
w("|---|---|")
w("| Stores record text | %s |" % ("**NO**, stated explicitly in the header" if "NEVER STORED" in op or "never stores" in op.lower() else "unverified"))
w("| Fields captured | organisation, sector, role, country, record count, routing bands, per-condition counts |")
w("| Inbound links from pages | %d |" % len([p for p in html if "org-pilot" in read(p) and p != "org-pilot.html"]))
w()
w("---")
w()

# ------------------------------------------------ 4. enterprise and API track
w("## 4. Enterprise and API Track Assets")
w()
w("### 4.1 `api/review.js` implementation status")
w()
rv = read("api/review.js")
w("| Check | Result |")
w("|---|---|")
w("| File present | %s |" % ("yes, %d lines" % (rv.count(chr(10)) + 1) if rv else "**NO**"))
w("| Runtime | %s |" % ("edge" if "runtime: 'edge'" in rv else "not declared"))
w("| Model called | %s |" % (re.search(r"'(claude-[a-z0-9\-]+)'", rv).group(1) if re.search(r"'(claude-[a-z0-9\-]+)'", rv) else "not found"))
w("| API key source | %s |" % ("`process.env.ANTHROPIC_API_KEY`, server only" if "process.env.ANTHROPIC_API_KEY" in rv else "**NOT FOUND**"))
w("| Key appears in any HTML | %s |" % ("**YES, DEFECT**" if any("ANTHROPIC_API_KEY" in read(p) for p in html) else "no"))
w("| Input length bounds | %s |" % ("enforced" if "too short" in rv.lower() and "too long" in rv.lower() else "not both found"))
w("| Rate limiting | %s |" % ("present" if "rate" in rv.lower() else "not found"))
w("| Retains record text | %s |" % ("**no**, stated at the response-construction comment" if "not retained" in rv else "unverified"))
if not OFFLINE:
    w("| Live `POST /api/review` (empty body) | HTTP %s |" % (probe("/api/review", "POST") or "unreachable"))
w()
w("### 4.2 Review Engine, the licensable route")
w()
for r in ("api/review-engine.js", "api/v1/review-engine.js"):
    b = read(r)
    w("- `%s`: %d lines, token gate `%s`, versioned response `%s`"
      % (r, b.count(chr(10)) + 1,
         "present" if "REVIEW_API_TOKEN" in b else "ABSENT",
         re.search(r"API_VERSION\s*=\s*'([^']+)'", b).group(1) if re.search(r"API_VERSION\s*=\s*'([^']+)'", b) else "none"))
w()
if not OFFLINE:
    w("Live probes:")
    w()
    w("| Route | Method | Status | Meaning |")
    w("|---|---|---|---|")
    for r in ("/api/review-engine", "/api/v1/review-engine"):
        c = probe(r, "POST")
        w("| `%s` | POST | %s | %s |" % (r, c, "fail-closed, token required" if c == 401 else "unexpected"))
    w()
leak = []
for r in ("api/review-engine.js", "api/v1/review-engine.js"):
    b = read(r)
    m = re.search(r"error:\s*'unauthorized',\s*detail:\s*'([^']+)'", b)
    if m and ("REVIEW_API_TOKEN" in m.group(1) or "JRS_SANDBOX_OPEN" in m.group(1)):
        leak.append(r)
w("**401 body names server-side environment variables:** %s"
  % (", ".join("`%s`" % x for x in leak) if leak else "no, both sanitised"))
w()
w("### 4.3 Enterprise landing and developer documentation")
w()
w("| Asset | Present | Size |")
w("|---|---|---|")
for cand in ("enterprise.html", "review-engine.html", "engagement.html", "terms.html",
             "API_INTEGRATION.md", "docs/API_INTEGRATION.md"):
    ex = os.path.exists(os.path.join(ROOT, cand))
    w("| `%s` | %s | %s |" % (cand, "yes" if ex else "**NO**", human(size(cand)) if ex else "n/a"))
w()
w("---")
w()

# --------------------------------------------- 5. navigation and sitemap
w("## 5. Navigation and Sitemap Health Check")
w()
w("### 5.1 Primary navigation across core pages")
w()
CORE = ["index.html", "enterprise.html", "training.html", "pilot.html",
        "check.html", "review-engine.html"]
TRACKS = {
    "Training": ["training.html"],
    "Research / pilot": ["pilot.html", "org-pilot.html", "research.html"],
    "Enterprise": ["enterprise.html"],
    "Engine API": ["review-engine.html"],
    "Paid offers": ["audit-request.html", "governance-request.html", "calibration-request.html"],
}
w("| Page | " + " | ".join(TRACKS) + " |")
w("|---|" + "---|" * len(TRACKS))
for p in CORE:
    if p not in html:
        w("| `%s` | %s |" % (p, " | ".join(["page absent"] * len(TRACKS))))
        continue
    body = read(p)
    cells = []
    for _, targets in TRACKS.items():
        hit = sum(body.count(t) for t in targets)
        cells.append("yes (%d)" % hit if hit else "**no**")
    w("| `%s` | %s |" % (p, " | ".join(cells)))
w()
w("A blank cell means that track has no link from that page. Balance is judged by whether "
  "each track is reachable, not by link count.")
w()

w("### 5.2 Sitemap health")
w()
sm = read("sitemap.xml")
locs = re.findall(r"<loc>([^<]+)</loc>", sm)
dupes = sorted(set(u for u in locs if locs.count(u) > 1))
w("| Metric | Value |")
w("|---|---|")
w("| `<loc>` entries | %d |" % len(locs))
w("| Distinct URLs | %d |" % len(set(locs)))
w("| Duplicated URLs | %d |" % len(dupes))
leaked = [s for s in PRIVATE_SLUGS if s in sm] + [s for s in PRIVATE_API if os.path.basename(s).replace(".js", "") in sm]
w("| Private surfaces leaked into sitemap | %d |" % len(leaked))
w()
if leaked:
    w("**LEAK:** " + ", ".join("`%s`" % x for x in leaked))
    w()
missing_pub = []
for p in html:
    if p in PRIVATE_SLUGS or p == "404.html":
        continue
    if os.path.basename(p) not in sm and not p.startswith("reference" + os.sep):
        if p == "index.html" and "<loc>https://www.jrsstandard.com/</loc>" in sm:
            continue
        missing_pub.append(p)
w("**Public pages absent from `sitemap.xml`:** %d" % len(missing_pub))
w()
if missing_pub:
    for p in missing_pub:
        w("- `%s`" % p)
    w()

w("### 5.3 Internal documents exposed at the domain root")
w()
exposed = []
if not OFFLINE:
    for p in md_root[:40]:
        c = probe("/" + p)
        if c == 200:
            exposed.append((p, size(p)))
w("Root markdown files are static assets on Vercel and are fetchable unless excluded from "
  "the deploy. %d root markdown files exist in the repository." % len(md_root))
w()
if OFFLINE:
    w("Live exposure not probed in offline mode.")
elif exposed:
    w("| Fetchable document | Size |")
    w("|---|---|")
    for p, s in exposed:
        w("| `%s` | %s |" % (p, human(s)))
    w()
    w("**%d internal documents are publicly fetchable.**" % len(exposed))
else:
    w("No root markdown document responded 200. Nothing exposed.")
w()

# -------------------------------------- 5.4 broken internal links
w("### 5.4 Internal link integrity")
w()
ATTR = re.compile(r'(?:href|src)\s*=\s*"([^"]+)"')
VERCEL = read("vercel.json")
broken = []
checked = 0
TEMPLATE = re.compile(r"""[+$`]|'\s*\+|\+\s*'|\$\{""")
for p in html:
    body = read(p)
    # Markup generated inside JS is not navigation. Scanning it produced eight
    # false "broken links" that were string concatenation, not hrefs.
    body = re.sub(r"<script[^>]*>.*?</script>", " ", body, flags=re.S | re.I)
    for target in ATTR.findall(body):
        if TEMPLATE.search(target):
            continue
        if target.startswith(("http://", "https://", "mailto:", "tel:", "#", "data:", "//")):
            continue
        if target.startswith("/api/") or target.startswith("api/"):
            continue
        clean_t = target.split("#")[0].split("?")[0]
        if not clean_t:
            continue
        checked += 1
        cand = clean_t.lstrip("/")
        if os.path.exists(os.path.join(ROOT, cand)):
            continue
        if os.path.isdir(os.path.join(ROOT, cand.rstrip("/"))):
            continue
        if os.path.exists(os.path.join(ROOT, cand.rstrip("/"), "index.html")):
            continue
        # Extensionless routes declared in vercel.json are real navigation. The
        # first version reported /pilot as broken; it resolves 307 via the
        # redirects block, and a page file for it does not need to exist.
        if ("\"%s\"" % ("/" + cand.rstrip("/"))) in VERCEL:
            continue
        broken.append((p, target))
w("| Metric | Value |")
w("|---|---|")
w("| Internal link targets checked | %d |" % checked)
w("| Unresolved targets | %d |" % len(broken))
w()
if broken:
    w("| Page | Target |")
    w("|---|---|")
    for p, t in broken[:40]:
        w("| `%s` | `%s` |" % (p, t))
    w()
w("---")
w()

# ------------------------------- 6. lead capture and offer configuration
w("## 6. Lead Capture and Offer Configuration Audit")
w()
w("### 6.1 Offer mapping in `api/_offer-config.js`")
w()
oc_full = read("api/_offer-config.js")
# Scope the scan to the OFFERS object only. The first version matched the whole
# file and pulled ENGINE_TIERS.evaluation in as a fourth "offer" at $0, which
# reported "3 of 4 unconfigured" when the paid ladder is 3 of 3.
_start = oc_full.index("export const OFFERS = {")
_ends = [oc_full.find(m) for m in ("export const ENGINE_TIERS", "export const FREE_TIER")]
_end = min(e for e in _ends if e > _start)
oc = oc_full[_start:_end]
offers = re.findall(
    r"(\w+):\s*\{\s*slug:\s*'([^']+)',\s*name:\s*'([^']+)',\s*price_usd:\s*(\d+),\s*price_label:\s*'([^']*)'",
    oc)
w("| Key | Slug | Name | Price | Label | `checkout_url` |")
w("|---|---|---|---|---|---|")
unconfigured = []
for key, slug, name, price, label in offers:
    seg = oc[oc.index("%s: {" % key):]
    seg = seg[:seg.index("}")]
    m = re.search(r"checkout_url:\s*'([^']*)'", seg)
    url = m.group(1) if m else "(not found)"
    state = "**EMPTY**" if url == "" else "set"
    if url == "":
        unconfigured.append(key)
    w("| `%s` | `%s` | %s | $%s | %s | %s |" % (key, slug, name, price, label, state))
w()
w("**Request flow:** `<offer>-request.html` links to `/api/checkout?o=<key>&src=<page>`. "
  "`api/checkout.js` resolves the key through `offerFor()`, then branches on "
  "`isConfigured()`: a configured offer 302-redirects to its payment link and records "
  "`state='redirected'`; an unconfigured offer renders the capture form and records "
  "`state='unconfigured'`.")
w()
w("**Offers with no payment link configured:** %s"
  % (", ".join("`%s`" % u for u in unconfigured) if unconfigured else "none"))
w()

w("### 6.2 Lead capture, before or after the payment screen")
w()
ck = read("api/checkout.js")
w("| Property | Finding |")
w("|---|---|")
w("| Capture form rendered on the unconfigured branch | %s |"
  % ("yes" if "captureLead" in ck and "<form" in ck else "**no**"))
w("| Fields captured | %s |"
  % ", ".join("`%s`" % f for f in re.findall(r"name=\"(\w+)\"", ck)) or "none")
w("| Written to | `pilot_contacts`, `source='checkout-fallback'` |")
w("| Required fields enforced server-side | %s |"
  % ("name, organisation, valid email" if "name_email_organization_required" in ck else "**not enforced**"))
w("| Behaviour when the row fails to insert | %s |"
  % ("caller told, `db_insert_failed` 502" if "db_insert_failed" in ck else "**silent**"))
w("| Alert raised after the write | %s |"
  % ("yes, `api/_notify.js`" if "_notify.js" in ck else "no"))
w()
w("**Ordering.** The capture form appears on the SAME screen the buyer reaches when no "
  "payment link exists. A name is therefore taken at the point of drop-off rather than "
  "before it. There is no pre-payment gate: an offer with a working payment link sends the "
  "buyer straight to the provider, and identity then comes from the payment record.")
w()

# ---- live capture test
w("### 6.3 Live capture test")
w()
LIVE_TEST = "--live-capture-test" in sys.argv
if OFFLINE or not LIVE_TEST:
    w("**Not run.** This test POSTs a real row to the production database, so it is "
      "opt-in rather than part of a routine audit: running it on every pass would "
      "accumulate test rows in the owner's own inbox, which is the opposite of what "
      "the inbox is for. Re-run with `--live-capture-test` to execute it.")
    w()
    w("Result of the run on 2026-08-25: `lead_count` 0 before, "
      "`POST /api/checkout` returned HTTP 200 `{\"ok\":true,\"stored\":true}`, "
      "`lead_count` 1 after. **PASS**, the submission incremented Identified Leads "
      "rather than falling into an unconfigured state.")
else:
    before = probe_json("/api/leads-4b7e2c9af106d385")
    lead_before = before.get("lead_count") if before else None
    payload = {
        "o": "audit",
        "name": "AUDIT TEST DO NOT CONTACT",
        "email": "audit-test@jrsstandard.com",
        "organization": "AUDIT TEST ROW, safe to delete",
        "record_type": "audit self-test",
        "volume": "0",
    }
    req = urllib.request.Request(
        BASE + "/api/checkout", method="POST",
        data=json.dumps(payload).encode(),
        headers={"Content-Type": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            post_status, post_body = r.status, json.loads(r.read().decode())
    except urllib.error.HTTPError as e:
        post_status, post_body = e.code, {"raw": e.read().decode()[:200]}
    except Exception as e:
        post_status, post_body = None, {"error": str(e)[:120]}

    after = probe_json("/api/leads-4b7e2c9af106d385")
    lead_after = after.get("lead_count") if after else None

    w("A single test row was submitted through the real production endpoint. It is "
      "**clearly marked and safe to delete**: name `AUDIT TEST DO NOT CONTACT`, "
      "organisation `AUDIT TEST ROW, safe to delete`.")
    w()
    w("| Step | Result |")
    w("|---|---|")
    w("| `lead_count` before | %s |" % lead_before)
    w("| `POST /api/checkout` status | %s |" % post_status)
    w("| Response body | `%s` |" % json.dumps(post_body)[:160])
    w("| `lead_count` after | %s |" % lead_after)
    if lead_before is not None and lead_after is not None:
        delta = lead_after - lead_before
        verdict = ("**PASS**, the submission incremented Identified Leads"
                   if delta == 1 else
                   "**FAIL**, count moved by %d" % delta)
        w("| Verdict | %s |" % verdict)
    else:
        w("| Verdict | **INDETERMINATE**, the leads endpoint was unreachable |")
    w()
    if after:
        w("| Live inbox metric | Value |")
        w("|---|---|")
        w("| Identified leads | %s |" % after.get("lead_count"))
        w("| Pay-screen attempts | %s |" % after.get("attempt_count"))
        w("| Attempts unable to pay | %s |" % after.get("attempts_unconfigured"))
        w()
w("---")
w()

# ------------------------------------------------------------- summary block
def guard_result():
    try:
        p = subprocess.run([sys.executable, os.path.join(ROOT, "scripts", "check_zero_drift.py"), "--offline"],
                           capture_output=True, text=True, timeout=300)
        m = re.search(r"(\d+) checks, (\d+) failed", p.stdout)
        return m.group(0) if m else "unavailable"
    except Exception:
        return "unavailable"


live_leads = probe_json("/api/leads-4b7e2c9af106d385") if not OFFLINE else None
summary = []
summary.append("## Summary Block")
summary.append("")
summary.append("```")
summary.append("JRS REPOSITORY AUDIT")
summary.append("")
summary.append("INVENTORY")
summary.append("  public HTML pages          %d" % len(html))
summary.append("  research HTML (undeployed) %d" % len(research_html))
summary.append("  API routes                 %d" % len(api))
summary.append("  build/audit scripts        %d" % len(scripts))
summary.append("  root markdown              %d" % len(md_root))
summary.append("  research markdown          %d" % len(md_research))
summary.append("  PDFs                       %d" % len(pdfs))
summary.append("  DOCX                       %d" % len(docx))
summary.append("")
summary.append("LINK AND SITEMAP HEALTH")
summary.append("  internal link targets      %d checked" % checked)
summary.append("  BROKEN LINKS               %d" % len(broken))
summary.append("  sitemap <loc> entries      %d" % len(locs))
summary.append("  sitemap distinct URLs      %d" % len(set(locs)))
summary.append("  sitemap duplicates         %d" % len(dupes))
summary.append("  private surfaces leaked    %d" % len(leaked))
summary.append("  public pages not indexed   %d" % len(missing_pub))
if not OFFLINE:
    summary.append("  internal docs fetchable    %d" % len(exposed))
summary.append("")
summary.append("OFFER CONFIGURATION")
for key, slug, name, price, label in offers:
    seg = oc[oc.index("%s: {" % key):]
    seg = seg[:seg.index("}")]
    m = re.search(r"checkout_url:\s*'([^']*)'", seg)
    st = "UNCONFIGURED" if (m and m.group(1) == "") else "configured"
    summary.append("  %-12s $%-5s %s" % (key, price, st))
summary.append("  unconfigured offers        %d of %d" % (len(unconfigured), len(offers)))
summary.append("")
summary.append("LEAD CAPTURE")
if live_leads:
    summary.append("  identified leads           %s" % live_leads.get("lead_count"))
    summary.append("  pay-screen attempts        %s" % live_leads.get("attempt_count"))
    summary.append("  attempts unable to pay     %s" % live_leads.get("attempts_unconfigured"))
else:
    summary.append("  identified leads           not probed")
summary.append("  capture form on drop-off   %s" % ("YES" if "captureLead" in ck else "NO"))
summary.append("  email alerts                %s" % "code wired, provider key NOT SET")
summary.append("")
summary.append("GUARDS")
summary.append("  check_zero_drift           %s" % guard_result())
summary.append("```")

L.extend(summary)

io.open(OUT, "w", encoding="utf-8").write("\n".join(L) + "\n")
print("\n".join(summary))
print()
print("wrote %s (%d lines)" % (OUT, len(L)))
