// JRS source alignment: controls extracted from the controlling sources. INTERNAL.
//
// Each control cites a source and a line range, paraphrases the requirement minimally (the owner
// directed on 2026-10-07 that no source text be committed; the line hashes the builder adds make
// the locator reproducible instead), and classifies the repository's position against it.
//   ALIGNED              the repository does what the control requires, shown by named evidence
//   PARTIALLY_ALIGNED    some of it, with the gap named
//   CONFLICT             a repository record or a later instruction says something incompatible
//   NOT_IMPLEMENTED      nothing in the repository yet does it
//   NOT_ASSESSED         outside what this package can examine
//   REQUIRES_HUMAN_ACTION  only a named person's act can satisfy it
// Evidence classes say what an evidence item is, and none is independent evidence: a test proves
// only the tested local control, a fixture only behaviour on that constructed set, a citation only
// that the source says it.
//
// Tiers: SUPPLEMENT (the controlling 3 October supplement), HISTORICAL_CONTEXT (retained historical
// text, design context only), REPOSITORY_SOURCE (the 5 October handoff or a preserved owner decision,
// used where no 3 October control was located).

const E = (path, contains, cls) => ({ path, contains, class: cls });
const RG = 'lib/release-gate/records/RG-RECORD_engine-0.5.0-local.1.json';
const RGR = 'docs/architecture/CURRENT_RELEASE_GATE_REPORT.md';
const H = (role, action) => ({ role, action, completed: false, evidence_ref: null });

export const CONTROLS = [
  { id: 'SAC-01', topic: 'scope', source_id: 'S01', lines: [5, 5], also_at: [['S02', 5, 5], ['S03', 5, 5]], tier: 'SUPPLEMENT', control_type: 'SCOPE',
    requirement: 'Only completed internal compliance records that are not HR records are in scope, starting with exceptions to supplier access; the named consequential decision areas are out of scope; a person always reviews.',
    interpretation: 'Applies to the Engine candidate and to any evaluation intake.', status: 'ALIGNED',
    repository_status: 'The candidate refuses any other record type, an undeclared HR status and excluded-domain text; the readiness intake refuses the same categories; every result requires human review.',
    evidence: [E('lib/engine-candidate/review-candidate.js', 'export const EXCLUDED_DOMAINS', 'SOURCE_CODE'), E('lib/engine-candidate/review-candidate.js', "export const SCOPE_PROFILE = 'supplier_access_exception.completed.non_hr'", 'SOURCE_CODE'), E('tools/evaluation-readiness/lib/intake.js', 'REFUSED_DOMAINS', 'SOURCE_CODE')],
    limitation: 'The excluded-domain screen is a heuristic that can only refuse; passing it does not prove a record is in scope.' },
  { id: 'SAC-02', topic: 'production_status', source_id: 'S01', lines: [5, 5], also_at: [['S02', 5, 5], ['S03', 5, 5]], tier: 'SUPPLEMENT', control_type: 'STATUS',
    requirement: 'Production is no-go and not verified; general-purpose validation, workplace readiness, licensing readiness and sale readiness are not established.',
    interpretation: 'No repository record may state or imply any of these statuses.', status: 'ALIGNED',
    repository_status: 'The release-gate report concludes every gate is open; the frozen demo is not released; the readiness package is planning-only.',
    evidence: [E(RGR, 'INCOMPLETE_GATES_OPEN', 'REPOSITORY_RECORD'), E('tools/frozen-demo/demo-manifest.json', 'DEMO_PREPARATION_COMPLETE_NOT_RELEASED', 'REPOSITORY_RECORD'), E('tools/evaluation-readiness/readiness-registry.json', 'PLANNING_ONLY', 'REPOSITORY_RECORD')],
    limitation: 'A status record states a position; it is not evidence that anything was tested.' },
  { id: 'SAC-03', topic: 'version_bound_identity', source_id: 'S01', lines: [9, 9], also_at: [['S02', 9, 9], ['S03', 9, 9]], tier: 'SUPPLEMENT', control_type: 'VERSION_BINDING',
    requirement: 'A result may not be carried from one version, commit or hosted service to another unless the source, prompt, configuration and run identities all match.',
    interpretation: 'Every result and every future run carries the identities that produced it.', status: 'PARTIALLY_ALIGNED',
    repository_status: 'Candidate results carry a review identity hashed from every version, the prompt, the model and the source; the frozen demo binds module hashes; the readiness registry requires a full run binding. No execution identity exists because no live run exists, and the configuration identity is only the statement that the candidate is local with a mock adapter.',
    evidence: [E('lib/engine-candidate/contract.js', 'export function reviewIdentity', 'SOURCE_CODE'), E('tools/frozen-demo/demo-manifest.json', 'bound_modules', 'REPOSITORY_RECORD'), E('tools/evaluation-readiness/lib/registry.js', 'REQUIRED_BINDING_FIELDS', 'SOURCE_CODE')],
    limitation: 'Binding is shown for local, mocked runs only; it says nothing about a hosted endpoint.' },
  { id: 'SAC-04', topic: 'semantic_support', source_id: 'S01', lines: [9, 9], also_at: [['S01', 66, 66]], tier: 'SUPPLEMENT', control_type: 'INTERPRETATION_LIMIT',
    requirement: 'Exact quotation presence and offsets do not establish semantic support.', interpretation: 'Every place a quotation is shown says so.', status: 'ALIGNED',
    repository_status: 'Reviewer packets and the workspace state that a quotation shows location, not support.',
    evidence: [E('lib/engine-candidate/reviewer-packet.js', 'A quotation shows presence in the record, not support.', 'SOURCE_CODE'), E('tools/local-reviewer-workspace/app/core.js', 'export const QUOTATION_NOTICE', 'SOURCE_CODE')],
    limitation: 'The notice is a statement; it does not test whether any finding is correct.' },
  { id: 'SAC-05', topic: 'evidence_ids', source_id: 'S01', lines: [13, 13], also_at: [['S02', 104, 104]], tier: 'SUPPLEMENT', control_type: 'EVIDENCE_ID_CONTROL',
    requirement: 'Evidence is cited by the canonical numbers E-001 to E-045; new numbers are added only by a controlled change to the canonical ledger itself.',
    interpretation: 'No repository record may assign E-nnn identifiers outside the canonical ledger.', status: 'CONFLICT', conflict_ids: ['CF-SA-01'],
    repository_status: 'The release-gate record numbers its own evidence E-001 to E-009, with meanings unrelated to the canonical entries of the same numbers.',
    evidence: [E(RG, '"evidence_id": "E-001"', 'REPOSITORY_RECORD')],
    limitation: 'Recorded, not renumbered: renumbering would change a hash-bound record and is an owner decision.' },
  { id: 'SAC-06', topic: 'evidence_ids', source_id: 'S02', lines: [96, 100], tier: 'SUPPLEMENT', control_type: 'EVIDENCE_ID_CONTROL',
    requirement: 'The canonical sequence runs from E-001 to E-045, with E-045 recorded as offline engineering evidence.',
    interpretation: 'The repository baseline ledger should carry the canonical sequence.', status: 'REQUIRES_HUMAN_ACTION', human_action: H('owner', 'Decide whether and how the repository ledger is brought to the canonical sequence; entries E-042 to E-044 are correspondence records the owner has directed must not be reproduced publicly.'),
    repository_status: 'docs/enterprise-diligence/EVIDENCE_LEDGER.md ends at E-039.',
    evidence: [E('docs/enterprise-diligence/EVIDENCE_LEDGER.md', '| E-039 |', 'REPOSITORY_RECORD')],
    limitation: 'The repository ledger lags the controlling source; nothing here is added to it.' },
  { id: 'SAC-07', topic: 'measured_limits', source_id: 'S01', lines: [17, 17], tier: 'SUPPLEMENT', control_type: 'EVIDENCE_LIMIT',
    requirement: 'Earlier offline scorer results are narrow fixture results for an earlier Engine version, not independently labeled accuracy.',
    interpretation: 'No such result is carried forward as accuracy, or to another version.', status: 'ALIGNED',
    repository_status: 'The candidate states that accuracy is not established on any record and carries no earlier-version result.',
    evidence: [E('lib/engine-candidate/README.md', 'Accuracy, on any record.', 'REPOSITORY_RECORD')], limitation: 'The earlier-version execution records are not in this branch and were not examined.' },
  { id: 'SAC-08', topic: 'release_gates', source_id: 'S01', lines: [21, 21], also_at: [['S02', 21, 21], ['S03', 21, 21]], tier: 'SUPPLEMENT', control_type: 'RELEASE_GATE',
    requirement: 'Before production, unused holdout records must be labelled and adjudicated independently, with results and uncertainty reported for each condition.',
    interpretation: 'Release-gate RG-1.', status: 'REQUIRES_HUMAN_ACTION', human_action: H('independent_labelers_and_owner', 'Independent labeling and adjudication of an unused, sealed holdout; owner authorization for any provider call on it.'),
    repository_status: 'RG-1 states this criterion and is BLOCKED; no holdout, labeler or adjudication exists.',
    evidence: [E(RG, 'Independent labeling and adjudication of an unused sealed holdout', 'REPOSITORY_RECORD')], limitation: 'Local work can prepare the structure only.' },
  { id: 'SAC-09', topic: 'release_gates', source_id: 'S01', lines: [21, 21], tier: 'SUPPLEMENT', control_type: 'RELEASE_GATE',
    requirement: 'Production requires operator evidence for access and database grants, credential rotation, retention and execution policies, backup restoration and compatible rollback.',
    interpretation: 'Release-gate RG-2.', status: 'REQUIRES_HUMAN_ACTION', human_action: H('owner_as_operator', 'Supply operator exports and records from the environment the Engine would run in.'),
    repository_status: 'RG-2 sub-controls cover each item and are BLOCKED or NOT_ASSESSED.',
    evidence: [E(RG, 'Compatible rollback', 'REPOSITORY_RECORD'), E(RG, 'Credential rotation', 'REPOSITORY_RECORD')], limitation: 'Code review cannot show that a production control operates.' },
  { id: 'SAC-10', topic: 'release_gates', source_id: 'S01', lines: [21, 21], tier: 'SUPPLEMENT', control_type: 'RELEASE_GATE',
    requirement: 'Before production, counsel must dispose of the real data flows, the storage arrangements, privacy duties and any evaluation or licensing statements.',
    interpretation: 'Release-gate RG-3.', status: 'REQUIRES_HUMAN_ACTION', human_action: H('counsel', 'Review the real data flows, storage arrangements, privacy duties and any evaluation or licensing statements.'),
    repository_status: 'RG-3 covers each item and is NOT_ASSESSED; no counsel disposition exists.',
    evidence: [E(RG, 'Storage terms', 'REPOSITORY_RECORD')], limitation: 'No internal document substitutes for counsel.' },
  { id: 'SAC-11', topic: 'release_gates', source_id: 'S01', lines: [21, 21], tier: 'SUPPLEMENT', control_type: 'RELEASE_GATE',
    requirement: 'Creator review remains the recorded requirement for the development package.',
    interpretation: 'A dated creator-review record for the development package.', status: 'CONFLICT', conflict_ids: ['CF-SA-05'],
    repository_status: 'The release-gate record has no creator-review gate or record; its five gates follow the 5 October handoff, which does not list creator review.',
    evidence: [E(RG, '"gate_id": "RG-5"', 'REPOSITORY_RECORD')], limitation: 'Recorded as a gap; no gate is added here.' },
  { id: 'SAC-12', topic: 'release_gates', source_id: 'S01', lines: [21, 21], tier: 'SUPPLEMENT', control_type: 'RELEASE_GATE',
    requirement: 'Quality assurance of production by an independent party is a release gate of its own.', interpretation: 'Release-gate RG-5.', status: 'REQUIRES_HUMAN_ACTION', human_action: H('independent_production_qa', 'Examine an authorized production deployment against a test plan fixed in advance.'),
    repository_status: 'RG-5 is BLOCKED; no authorized deployment exists to examine.', evidence: [E(RG, 'Independent QA of the authorized production deployment', 'REPOSITORY_RECORD')], limitation: 'Nothing local can stand in for it.' },
  { id: 'SAC-13', topic: 'no_release_from_local_progress', source_id: 'S01', lines: [21, 21], tier: 'SUPPLEMENT', control_type: 'EVIDENCE_LIMIT',
    requirement: 'Static checks, and status codes returned to GET requests, cannot show that the Edge Functions execute.', interpretation: 'Local or static evidence never stands for live behaviour.', status: 'ALIGNED',
    repository_status: 'The release-gate record limits its code-review evidence to the repository and classes every local item as unable to pass a gate.',
    evidence: [E(RG, 'It is not a check of what the production host serves.', 'REPOSITORY_RECORD')], limitation: 'The limitation is recorded, not tested against a live host.' },
  { id: 'SAC-14', topic: 'demonstration_track', source_id: 'S01', lines: [44, 44], also_at: [['S03', 112, 112]], tier: 'SUPPLEMENT', control_type: 'TRACK_EVIDENCE',
    requirement: 'A demonstration status needs frozen demo cases, a named version, complete run evidence, a capability matrix, visible limitations and a dated owner release decision; it is not established.',
    interpretation: 'The frozen demo may be prepared, never treated as released.', status: 'PARTIALLY_ALIGNED', human_action: H('owner', 'A dated release decision, if a demonstration is ever to be given.'),
    repository_status: 'Frozen cases, a named version, a capability matrix and visible limitations exist. Run evidence is local mock replay only; no owner release decision exists.',
    evidence: [E('tools/frozen-demo/demo-manifest.json', 'DEMO_PREPARATION_COMPLETE_NOT_RELEASED', 'SYNTHETIC_FIXTURE'), E('docs/architecture/FROZEN_DEMONSTRATION_CAPABILITY_MATRIX.md', 'Demonstrated capability', 'REPOSITORY_RECORD')],
    limitation: 'Synthetic replay proves only behaviour on the constructed corpus.' },
  { id: 'SAC-15', topic: 'commercial_pathway', source_id: 'S01', lines: [37, 39], also_at: [['S01', 45, 46], ['S03', 96, 96]], tier: 'SUPPLEMENT', control_type: 'OBJECTIVE',
    requirement: 'The stated current objectives include preparing a limited commercial evaluation pathway in parallel with demonstration and evidence work.',
    interpretation: 'Read against the later 5 October handoff, which prohibits licensing and acquisition work without a new owner instruction.', status: 'CONFLICT', conflict_ids: ['CF-SA-03'],
    repository_status: 'This branch follows the handoff: public pages state no licence, evaluation or transaction is offered, and no commercial artifact was prepared.',
    evidence: [E('index.html', 'No software access, licence, exclusive grant, or asset transfer is currently offered.', 'PUBLIC_PAGE'), E('docs/architecture/CURRENT_ENGINE_HANDOFF_2026-10-05.md', 'licensing, acquisition, or rights transfer', 'REPOSITORY_RECORD')],
    limitation: 'Which instruction governs commercial preparation is an owner decision; no commercial terms are described here.' },
  { id: 'SAC-16', topic: 'independent_human_dispositions', source_id: 'S01', lines: [70, 70], also_at: [['S01', 74, 74]], tier: 'SUPPLEMENT', control_type: 'HUMAN_AUTHORITY',
    requirement: 'The owner is the sole human reviewer the evaluation package requires; AI does the inspection, fixtures, harnesses, authorized runs, scoring and drafting; nobody is to be recruited or contacted; a dispute stays open unless the owner settles it.',
    interpretation: 'Applies to the evaluation package; the production gate (SAC-08) separately requires independent labeling.', status: 'CONFLICT', conflict_ids: ['CF-SA-02'],
    repository_status: 'The evaluation-readiness package models future review by independent reviewers and a separate adjudicator, with independence attestations, and has no creator-review path.',
    evidence: [E('tools/evaluation-readiness/authority-matrix.json', '"independent_reviewer"', 'REPOSITORY_RECORD'), E('tools/evaluation-readiness/readiness-contract.json', 'ATT-04', 'REPOSITORY_RECORD')],
    limitation: 'The readiness package is planning-only; nothing was recruited or contacted.' },
  { id: 'SAC-17', topic: 'separation_of_extraction_and_evaluation', source_id: 'S01', lines: [72, 72], tier: 'SUPPLEMENT', control_type: 'SEPARATION',
    requirement: 'Deterministic checks, the expectations written for constructed cases, and the creator\'s reviewed judgments stay apart.', interpretation: 'No layer is merged into another.', status: 'PARTIALLY_ALIGNED',
    repository_status: 'The candidate keeps deterministic findings apart from model findings; frozen-demo expectations are separate files; readiness workspaces keep extraction, interpretation, comparison and adjudication apart. Creator-reviewed judgments are not modelled anywhere.',
    evidence: [E('lib/engine-candidate/contract.js', 'extraction_findings', 'SOURCE_CODE'), E('tools/evaluation-readiness/lib/workspace.js', "export const WORKSPACES = Object.freeze(['extraction', 'interpretation', 'comparison', 'adjudication']);", 'SOURCE_CODE')],
    limitation: 'Separation is enforced in local code and tests only.' },
  { id: 'SAC-18', topic: 'freeze_before_labels', source_id: 'S01', lines: [72, 72], tier: 'SUPPLEMENT', control_type: 'EVALUATION_CONTROL',
    requirement: 'Before any labeling or testing, the Codebook and the mapping of errors are frozen and hashed.', interpretation: 'Both must exist as frozen, hashed artifacts before any labeling.', status: 'PARTIALLY_ALIGNED', human_action: H('owner', 'Record the Codebook freeze and approve an error mapping.'),
    repository_status: 'The Codebook is hash-bound (v1.0) but not frozen for evaluation; no error-mapping artifact exists.',
    evidence: [E('tools/evaluation-readiness/codebook-mapping.json', '"freeze_for_evaluation": "NOT_FROZEN"', 'REPOSITORY_RECORD')], limitation: 'A hash identifies the page; it is not a freeze.' },
  { id: 'SAC-19', topic: 'blind_labeling', source_id: 'S01', lines: [72, 72], tier: 'SUPPLEMENT', control_type: 'EVALUATION_CONTROL',
    requirement: 'Conceal Engine output during initial labeling.', interpretation: 'Interpretations are made blind to candidate output.', status: 'ALIGNED',
    repository_status: 'The readiness workspace refuses an interpretation not made blind to candidate output.', evidence: [E('tools/evaluation-readiness/lib/workspace.js', 'blind_to_candidate_output', 'SOURCE_CODE')],
    limitation: 'A declared flag; the workspace cannot observe what a person saw.' },
  { id: 'SAC-20', topic: 'ordering_and_retest', source_id: 'S01', lines: [72, 72], tier: 'SUPPLEMENT', control_type: 'EVALUATION_CONTROL',
    requirement: 'Record random ordering, corrections and reasons; any test-retest claim needs a delayed blind re-label after a minimum interval and coverage.', interpretation: 'Required before any test-retest statement.', status: 'NOT_IMPLEMENTED',
    repository_status: 'No ordering, correction or re-label record exists.', evidence: [], limitation: 'Nothing is claimed about test-retest.' },
  { id: 'SAC-21', topic: 'no_invented_labels', source_id: 'S01', lines: [72, 72], also_at: [['S02', 96, 96]], tier: 'SUPPLEMENT', control_type: 'EVIDENCE_LIMIT',
    requirement: 'No label, and no result of a waiting period, may be made up; approvals copied into fixtures are never reported as decisions by a person.', interpretation: 'Code never authors a human judgment.', status: 'ALIGNED',
    repository_status: 'No label exists; the readiness workspace refuses interpretations authored by code, and the ledger refuses human-role artifacts created by code or fixtures.',
    evidence: [E('tools/evaluation-readiness/lib/ledger.js', 'role_substitution', 'SOURCE_CODE'), E('tools/evaluation-readiness/lib/workspace.js', 'author_not_permitted', 'SOURCE_CODE')], limitation: 'Probes and fixtures carry SYNTHETIC tokens only.' },
  { id: 'SAC-22', topic: 'ai_not_adjudication', source_id: 'S01', lines: [74, 74], tier: 'SUPPLEMENT', control_type: 'HUMAN_AUTHORITY',
    requirement: 'Checks run by AI are automated judgments; they are not adjudication by an independent person.', interpretation: 'No automated agreement stands for adjudication.', status: 'PARTIALLY_ALIGNED', conflict_ids: ['CF-SA-02'],
    repository_status: 'Code cannot adjudicate in the readiness workspace, and cross-model agreement is never called accuracy; who adjudicates differs from the source (see CF-SA-02).',
    evidence: [E('tools/evaluation-readiness/lib/workspace.js', 'adjudicator_is_a_reviewer', 'SOURCE_CODE'), E('tools/claim-provenance/lib/rules.js', 'G03', 'SOURCE_CODE')], limitation: 'Local controls only.' },
  { id: 'SAC-23', topic: 'research_distinction', source_id: 'S01', lines: [76, 76], tier: 'SUPPLEMENT', control_type: 'DISCLOSURE',
    requirement: 'A technical evaluation report states the interests involved, the use of AI, where fixtures came from, that real records are missing and how evaluators depend on each other; it measures the integrity of documentation, not its legal validity; publishing is its own decision.',
    interpretation: 'Public research statements keep detection, operational validity and legal defensibility apart.', status: 'PARTIALLY_ALIGNED', human_action: H('owner', 'Publication of the repaired research pages is a separate owner decision.'),
    repository_status: 'Public pages on this branch state the constructed corpus, the limits and that legal defensibility is not assessed; the repairs are staged, not published.',
    evidence: [E('research.html', 'Detection, reproducibility, reliability, method research, and real-world validation are distinct.', 'PUBLIC_PAGE'), E('jrsstandard.html', 'It does not evaluate whether the underlying decision was correct, legally defensible, or consistent with policy.', 'PUBLIC_PAGE')],
    limitation: 'Wording is checked by the claim-provenance scanner, not by a reader study.' },
  { id: 'SAC-24', topic: 'rights_provenance', source_id: 'S01', lines: [80, 82], tier: 'SUPPLEMENT', control_type: 'RIGHTS_LIMIT',
    requirement: 'Recorded consents and contributions are not widened into commercial or exclusive grants; no new assignment, permission, trademark clearance, publishing agreement or evidence of a selling entity is established.',
    interpretation: 'No repository record states a rights conclusion beyond its evidence.', status: 'ALIGNED',
    repository_status: 'The provenance package records repository-visible evidence only and states it establishes no chain of title, licence or clearance.',
    evidence: [E('docs/architecture/SOFTWARE_ASSET_AND_PROVENANCE_INVENTORY.md', 'It does not establish chain of title', 'REPOSITORY_RECORD')], limitation: 'No legal conclusion; counsel review is RG-3.' },
  { id: 'SAC-25', topic: 'correspondence_records', source_id: 'S01', lines: [84, 84], tier: 'SUPPLEMENT', control_type: 'EVIDENCE_LIMIT',
    requirement: 'Drafts are not proof of dispatch or assent, and historical correspondence records are not rewritten.', interpretation: 'Outside this package; not examined.', status: 'NOT_ASSESSED',
    repository_status: 'No correspondence record is touched by this package.', evidence: [], limitation: 'On the owner\'s direction no correspondence content is reproduced here.' },
  { id: 'SAC-26', topic: 'run_identity_evidence', source_id: 'S01', lines: [88, 88], tier: 'SUPPLEMENT', control_type: 'EVIDENCE_REQUIRED',
    requirement: 'Obtain a redacted bundle of the raw run outputs, with the exact source, prompt and configuration identities that were tested and deployed.', interpretation: 'Required before any earlier run is cited as evidence.', status: 'REQUIRES_HUMAN_ACTION', human_action: H('owner', 'Provide a redacted bundle of the earlier raw run outputs, with their identities, if those runs are to be cited.'),
    repository_status: 'Not located in this branch.', evidence: [], limitation: 'Absence here is not proof of absence elsewhere.' },
  { id: 'SAC-27', topic: 'dated_owner_decisions', source_id: 'S01', lines: [88, 88], tier: 'SUPPLEMENT', control_type: 'HUMAN_AUTHORITY',
    requirement: 'Each specific owner decision is recorded with its date; a general approval never stands in for a missing dated gate record.', interpretation: 'No gate or freeze is treated as decided without a dated record.', status: 'ALIGNED',
    repository_status: 'Every owner-decision field in the release-gate record and the readiness registry is null.',
    evidence: [E(RG, '"owner_decision": null', 'REPOSITORY_RECORD'), E('tools/evaluation-readiness/readiness-registry.json', '"freeze_record_ref": null', 'REPOSITORY_RECORD')], limitation: 'Fields are empty because no decision exists.' },
  { id: 'SAC-28', topic: 'production_change_traceability', source_id: 'S01', lines: [92, 92], tier: 'SUPPLEMENT', control_type: 'DEPLOYMENT_CONTROL',
    requirement: 'Any later production change must be traceable upstream, carry a release reference, go through an authorized deployment route and have its served files checked against what was built.', interpretation: 'Applies to any merge of this branch.', status: 'PARTIALLY_ALIGNED', human_action: H('owner', 'A release reference and authorization before any merge that publishes.'),
    repository_status: 'A deploy-verify workflow byte-compares production against the commit; no release reference or authorization exists for this branch.',
    evidence: [E('.github/workflows/deploy-verify.yml', 'byte', 'SOURCE_CODE')], limitation: 'The workflow compares static assets; it does not verify Edge Function execution.' },
  { id: 'SAC-29', topic: 'protected_implementation', source_id: 'S01', lines: [102, 102], tier: 'SUPPLEMENT', control_type: 'CONFIDENTIALITY',
    requirement: 'Software is not classed secret, exclusive or transaction-ready merely because it is called proprietary; the public-repository position requires an exposure review before any promise of secrecy or exclusivity.',
    interpretation: 'Exclusion from the website is not confidentiality.', status: 'CONFLICT', conflict_ids: ['CF-SA-06'], human_action: H('owner_and_counsel', 'Exposure review of the public repository before any statement that the implementation is protected.'),
    repository_status: 'The repository is public on GitHub. .vercelignore describes its exclusions as protecting the implementation, while the provenance inventory records that exclusion is not a confidentiality control.',
    evidence: [E('.vercelignore', 'PUBLICIZE THE STANDARD, PROTECT THE IMPLEMENTATION', 'REPOSITORY_RECORD'), E('docs/architecture/SOFTWARE_ASSET_AND_PROVENANCE_INVENTORY.md', 'It is not a confidentiality control.', 'REPOSITORY_RECORD')],
    limitation: 'This package changes neither; repository visibility is the owner\'s setting.' },
  { id: 'SAC-30', topic: 'target_vs_current', source_id: 'S03', lines: [96, 96], tier: 'SUPPLEMENT', control_type: 'INTERPRETATION_LIMIT',
    requirement: 'The historical architecture describes intended design; it does not state what is implemented.', interpretation: 'Target and current state are always labelled apart.', status: 'ALIGNED',
    repository_status: 'The readiness contract separates current implementation from target architecture.', evidence: [E('tools/evaluation-readiness/readiness-contract.json', 'TARGET_ARCHITECTURE', 'REPOSITORY_RECORD')], limitation: 'Labels only.' },
  { id: 'SAC-31', topic: 'scope', source_id: 'S03', lines: [98, 98], tier: 'SUPPLEMENT', control_type: 'SCOPE',
    requirement: 'The first proposed workflow is a proposal, not evidence of demand; HR and other consequential eligibility decisions stay outside it; a disclaimer alone does not settle applicability.',
    interpretation: 'No demand claim; scope held to the non-HR workflow.', status: 'PARTIALLY_ALIGNED',
    repository_status: 'No demand claim is made. Public methodology pages describe review environments that include HR and employment records; whether the scope sentence governs the public methodology or only the Engine is not settled (public audit PPA-08).',
    evidence: [E('jrsstandard.html', 'HR review and employment documentation audit', 'PUBLIC_PAGE')], limitation: 'Interpretation question for the owner.' },
  { id: 'SAC-32', topic: 'source_prompt_config_binding', source_id: 'S03', lines: [100, 100], tier: 'SUPPLEMENT', control_type: 'VERSION_BINDING',
    requirement: 'Inspect instructions and existing work before edits, do not assume branches or credentials exist, and pin exact model identifiers.', interpretation: 'Model identity is a pinned, versioned value.', status: 'ALIGNED',
    repository_status: 'The model identifier is pinned in one module and recorded in the candidate identity; each package records its start state.',
    evidence: [E('api/_model.js', 'claude-haiku-4-5-20251001', 'SOURCE_CODE'), E('tools/evaluation-readiness/baseline.json', 'start_head', 'REPOSITORY_RECORD')], limitation: 'No live model is called.' },
  { id: 'SAC-33', topic: 'harness_controls', source_id: 'S03', lines: [102, 102], tier: 'SUPPLEMENT', control_type: 'HARNESS_CONTROL',
    requirement: 'Paid calls only under a dated authorization of spend; a cap on input size; timeouts and cancellation; redirect refusal; a destination allowlist; no key or body logging; bounded retries; fail-closed handling of malformed output.',
    interpretation: 'Required of any live adapter.', status: 'PARTIALLY_ALIGNED',
    repository_status: 'No provider adapter exists, so no paid call is possible; the candidate enforces a maximum input size and rejects malformed output fail-closed; an outbound inventory exists. Timeout, cancellation, redirect refusal and retry budgets belong to a live adapter that does not exist.',
    evidence: [E('lib/engine-candidate/adapter.js', 'NO LIVE PROVIDER IS IMPLEMENTED HERE OR ANYWHERE IN THE CANDIDATE.', 'SOURCE_CODE'), E('lib/engine-candidate/review-candidate.js', 'export const MAX_CHARS = 8000;', 'SOURCE_CODE'), E('.jrs/registries/OUTBOUND_DESTINATIONS.json', 'api.anthropic.com', 'REPOSITORY_RECORD')],
    limitation: 'Provider-side billing caps are not verified.' },
  { id: 'SAC-34', topic: 'evaluation_metric_freeze', source_id: 'S03', lines: [104, 104], tier: 'SUPPLEMENT', control_type: 'EVALUATION_CONTROL',
    requirement: 'Freeze the evaluation metrics and their mappings before execution; report conditions and routes separately; smoke results show connectivity only.', interpretation: 'A metric specification frozen before any run.', status: 'NOT_IMPLEMENTED', human_action: H('owner', 'Approve and freeze a metric specification before any evaluation run.'),
    repository_status: 'The readiness registry holds a calibration freeze slot (unfrozen); no metric specification exists.',
    evidence: [E('tools/evaluation-readiness/readiness-registry.json', '"calibration"', 'REPOSITORY_RECORD')], limitation: 'Structure only.' },
  { id: 'SAC-35', topic: 'sealed_holdout_separation', source_id: 'S03', lines: [104, 104], tier: 'SUPPLEMENT', control_type: 'HOLDOUT_SEPARATION',
    requirement: 'Smoke-test cases never go into a later holdout, and a local result counts as production evidence only after the local and production source, prompt and configuration hashes have been compared.',
    interpretation: 'Development and smoke material never enters a holdout; local results never stand as production evidence.', status: 'PARTIALLY_ALIGNED',
    repository_status: 'Every development text, the frozen demo included, is registered and refused by digest at intake; no holdout builder exists; local evidence is classed as unable to pass a gate.',
    evidence: [E('lib/engine-candidate/dev-material.js', 'export function assertNotDevelopmentMaterial', 'SOURCE_CODE'), E('tools/evaluation-readiness/lib/intake.js', 'frozen_demo_material', 'SOURCE_CODE')],
    limitation: 'Digest matching is a contamination control, not proof of independence.' },
  { id: 'SAC-36', topic: 'adversarial_tests', source_id: 'S03', lines: [106, 106], tier: 'SUPPLEMENT', control_type: 'EVALUATION_CONTROL',
    requirement: 'Adversarial testing covers prompt injection inside untrusted records, malformed input, attempts to draw out disclosures and outcomes wrongly marked ready; a clean result on a frozen set has a bounded meaning.',
    interpretation: 'Each class has a frozen adversarial set.', status: 'PARTIALLY_ALIGNED',
    repository_status: 'The candidate reports instruction-like record text, rejects malformed and determination-language output, and has mutation and metamorphic tests; no disclosure-attempt set and no live adversarial run exist.',
    evidence: [E('lib/engine-candidate/source-prep.js', 'instruction_like_text', 'SOURCE_CODE'), E('lib/engine-candidate/adapter.js', 'export const DETERMINATION', 'SOURCE_CODE')], limitation: 'Mocked tests only.' },
  { id: 'SAC-37', topic: 'real_record_path', source_id: 'S03', lines: [108, 108], tier: 'SUPPLEMENT', control_type: 'DATA_CONTROL',
    requirement: 'Real records only when permissioned, de-identified and under confirmed authority, never in smoke tests; otherwise results are labelled fixture performance; creator-only labels are not independent truth.',
    interpretation: 'No real record without authority; synthetic results labelled as such.', status: 'ALIGNED',
    repository_status: 'Intake is closed and requires authority, rights and custody attestations; frozen-demo results are labelled synthetic.',
    evidence: [E('tools/evaluation-readiness/lib/intake.js', 'export const INTAKE_OPEN = false;', 'SOURCE_CODE'), E('tools/frozen-demo/demo-evidence-record.json', 'all_cases_synthetic', 'SYNTHETIC_FIXTURE')], limitation: 'No real record exists to test the path.' },
  { id: 'SAC-38', topic: 'release_gates', source_id: 'S03', lines: [110, 110], tier: 'SUPPLEMENT', control_type: 'RELEASE_GATE_FORMAT',
    requirement: 'Gates kept as machine-readable records hold their ID, the named version, hashed evidence paths, the threshold and the result obtained, any missing dependency, the owner\'s dated decision and a status of pass, fail or not assessed; averaging may not hide a critical failure; where evidence needing professional authority is missing the gate is not assessed, and nothing is simulated.',
    interpretation: 'Read against the release-gate record.', status: 'CONFLICT', conflict_ids: ['CF-SA-04'],
    repository_status: 'The record carries ID, version, hashed evidence, criterion, missing dependencies and owner decision, but no numeric threshold, and uses BLOCKED for RG-1, RG-2, RG-4 and RG-5 where the source vocabulary is pass, fail or not assessed.',
    evidence: [E(RG, '"status": "BLOCKED"', 'REPOSITORY_RECORD'), E(RG, '"acceptance_criterion"', 'REPOSITORY_RECORD')], limitation: 'No status is changed here.' },
  { id: 'SAC-39', topic: 'no_release_from_local_progress', source_id: 'S03', lines: [112, 112], also_at: [['S01', 88, 88]], tier: 'SUPPLEMENT', control_type: 'STATUS',
    requirement: 'Completed paperwork does not confer demonstration readiness or commercial clearance.', interpretation: 'No package of documents advances a status.', status: 'ALIGNED',
    repository_status: 'Every package records that it advances no gate; constructed, mocked and local evidence classes can never pass a gate.',
    evidence: [E('lib/release-gate/vocabulary.js', 'production_evidence: false', 'SOURCE_CODE'), E('tools/evaluation-readiness/readiness-contract.json', '"relationship_to_release_gates": "none"', 'REPOSITORY_RECORD')], limitation: 'A rule in code; it does not prevent a person from mislabelling.' },
  { id: 'SAC-40', topic: 'completion_package', source_id: 'S03', lines: [112, 112], tier: 'SUPPLEMENT', control_type: 'TRACK_EVIDENCE',
    requirement: 'The completion package is a capability matrix, the frozen demo with its replay disclosure, visible limitations, redacted raw outputs with their scoring scripts, a technical report, data-flow and threat material, a change log, offer documents, a procurement sheet, a gate report and an owner decision sheet.',
    interpretation: 'Deliverables may carry candid missing-evidence statuses.', status: 'PARTIALLY_ALIGNED',
    repository_status: 'Capability matrix, frozen demo, limitations, data-flow records, gate report and an owner decision sheet exist; raw run evidence is absent; offer and procurement documents were not prepared under the handoff.',
    evidence: [E('docs/architecture/FROZEN_DEMONSTRATION_CAPABILITY_MATRIX.md', 'What it does not show', 'REPOSITORY_RECORD'), E('docs/enterprise-diligence/ACTUAL_DATA_FLOW_AND_PROCESSOR_MATRIX_2026-09-15.md', 'Data', 'REPOSITORY_RECORD')], limitation: 'Offer documents are subject to CF-SA-03.' },
  { id: 'SAC-41', topic: 'public_controlled_boundary', source_id: 'S03', lines: [196, 206], tier: 'HISTORICAL_CONTEXT', control_type: 'BOUNDARY',
    requirement: 'Publicize the standard and protect the implementation; do not treat the public methodology as a trade secret.', interpretation: 'Historical design context.', status: 'PARTIALLY_ALIGNED', conflict_ids: ['CF-SA-06'],
    repository_status: 'The website serves the standard and excludes the implementation; the public GitHub repository exposes the implementation.',
    evidence: [E('.vercelignore', 'tools/', 'REPOSITORY_RECORD')], limitation: 'Historical text, not a current instruction.' },
  { id: 'SAC-42', topic: 'public_controlled_boundary', source_id: 'S03', lines: [472, 525], tier: 'HISTORICAL_CONTEXT', control_type: 'BOUNDARY',
    requirement: 'A public, controlled and confidential classification, with evaluation and benchmark datasets controlled.', interpretation: 'Historical design context.', status: 'PARTIALLY_ALIGNED',
    repository_status: 'Development corpora and evaluation tooling are excluded from the website but readable in the public repository; sealed holdouts do not exist.',
    evidence: [E('.vercelignore', 'tests/', 'REPOSITORY_RECORD')], limitation: 'Historical text, not a current instruction.' },
  { id: 'SAC-43', topic: 'research_distinction', source_id: 'S03', lines: [699, 756], tier: 'HISTORICAL_CONTEXT', control_type: 'INTERPRETATION_LIMIT',
    requirement: 'Reproducibility, classification performance, reviewer agreement, robustness and operational validity are separate properties, each measured, not assumed.', interpretation: 'Historical design context.', status: 'PARTIALLY_ALIGNED',
    repository_status: 'The claim-provenance rules keep detection, agreement and reliability apart; several public pages describe the programme as being in "operational validation", which names a property no study has measured (public audit PPA-03).',
    evidence: [E('tools/claim-provenance/lib/rules.js', 'G01', 'SOURCE_CODE'), E('about.html', 'operational validation', 'PUBLIC_PAGE')], limitation: 'Historical text, not a current instruction.' },
  { id: 'SAC-44', topic: 'no_psychological_or_legal_determination', source_id: 'S03', lines: [759, 769], tier: 'HISTORICAL_CONTEXT', control_type: 'HUMAN_OVERSIGHT',
    requirement: 'Never imply that JRS determined a decision defensible; it identifies conditions requiring review, followed by human review.', interpretation: 'Historical design context.', status: 'ALIGNED',
    repository_status: 'The candidate rejects determination language in model output, and sign-off is defined as not an approval.',
    evidence: [E('lib/engine-candidate/adapter.js', 'export const DETERMINATION', 'SOURCE_CODE'), E('lib/engine-candidate/contract.js', 'SIGN_OFF_MEANING', 'SOURCE_CODE')], limitation: 'Historical text, not a current instruction.' },
  { id: 'SAC-45', topic: 'research_distinction', source_id: 'S03', lines: [1398, 1430], tier: 'HISTORICAL_CONTEXT', control_type: 'RESEARCH_GOVERNANCE',
    requirement: 'Research proceeds by tiers and does not jump from methodological testing or reliability to effectiveness claims.', interpretation: 'Historical design context.', status: 'ALIGNED',
    repository_status: 'Public research pages and the claim register make no effectiveness or real-world claim.', evidence: [E('research.html', 'Nothing above is presented as real-world validation.', 'PUBLIC_PAGE')], limitation: 'Historical text, not a current instruction.' },
  { id: 'SAC-46', topic: 'research_distinction', source_id: 'S02', lines: [166, 169], tier: 'HISTORICAL_CONTEXT', control_type: 'EVIDENCE_LIMIT',
    requirement: 'Detection was measured on a constructed corpus; reliability on a separate small sample did not meet its criterion; cross-vendor figures are consistency, not accuracy or reliability.', interpretation: 'Canonical evidence entries E-037 to E-039.', status: 'ALIGNED',
    repository_status: 'The claim register binds these limits, and the public repairs carry them.', evidence: [E('docs/architecture/CLAIM_EVIDENCE_REGISTER.md', 'CL-001', 'REPOSITORY_RECORD'), E('research.html', 'This is agreement between models, not accuracy.', 'PUBLIC_PAGE')],
    limitation: 'Already public in the repository ledger; no new content.' },
  { id: 'SAC-47', topic: 'credential_handling', source_id: 'S02', lines: [66, 66], tier: 'SUPPLEMENT', control_type: 'SECURITY',
    requirement: 'A credential-handling requirement: rotation evidence is required for a credential the source identifies. Details remain in the local source only.', interpretation: 'Owner evidence required.', status: 'REQUIRES_HUMAN_ACTION', human_action: H('owner', 'Confirm the rotation the source requires, by an attestation or record kept outside the repository.'),
    repository_status: 'The repository records one owner attestation of a different credential rotation (E-030); it cannot show this one.', evidence: [], limitation: 'No credential detail is reproduced, on the owner\'s direction.' },
  { id: 'RAC-01', topic: 'no_psychological_or_intent_inference', source_id: 'H05', lines: [22, 22], tier: 'REPOSITORY_SOURCE', control_type: 'INFERENCE_LIMIT', no_october_3_control: true,
    requirement: 'Record-level documentation flaws only; no inference of a writer\'s emotional state, intent, hidden payoff or clinical condition.', interpretation: 'No October 3 control was located for this; the handoff governs.', status: 'ALIGNED',
    repository_status: 'The candidate withholds model text matching emotion, intent, motive, payoff, credibility or clinical terms; the readiness workspace refuses such notes.',
    evidence: [E('lib/engine-candidate/review-candidate.js', 'export const PROHIBITED_INFERENCE', 'SOURCE_CODE'), E('tools/evaluation-readiness/lib/vocabulary.js', 'export const PROHIBITED_INFERENCE', 'SOURCE_CODE')], limitation: 'Pattern screens miss paraphrase.' },
  { id: 'RAC-02', topic: 'extraction_failure_reporting', source_id: 'H05', lines: [27, 27], tier: 'REPOSITORY_SOURCE', control_type: 'EXTRACTION_REPORTING', no_october_3_control: true,
    requirement: 'Explicit reporting of extraction failure, omission, truncation and unsupported content.', interpretation: 'No October 3 control was located; the handoff governs.', status: 'ALIGNED',
    repository_status: 'Deterministic source preparation reports unreadable and partial input (refused), omissions, unsupported content and instruction-like text.',
    evidence: [E('lib/engine-candidate/source-prep.js', 'TRUNCATION_MARKERS', 'SOURCE_CODE'), E('lib/engine-candidate/source-prep.js', 'UNSUPPORTED_MARKERS', 'SOURCE_CODE')], limitation: 'Heuristics; absence of a finding is not proof of absence.' },
  { id: 'RAC-03', topic: 'sealed_holdout_separation', source_id: 'H05', lines: [37, 37], tier: 'REPOSITORY_SOURCE', control_type: 'HOLDOUT_SEPARATION', no_october_3_control: true,
    requirement: 'No development, training or debugging data in sealed holdouts.', interpretation: 'The October 3 source covers smoke cases only (SAC-35); the handoff extends it.', status: 'PARTIALLY_ALIGNED',
    repository_status: 'All 94 development texts are registered and refused; no holdout builder exists to enforce it.', evidence: [E('lib/engine-candidate/dev-material.js', 'DEVELOPMENT_MATERIAL', 'SOURCE_CODE')], limitation: 'Detection, not enforcement.' },
  { id: 'RAC-04', topic: 'no_premature_drr_scoring', source_id: 'H05', lines: [38, 38], tier: 'REPOSITORY_SOURCE', control_type: 'SCORING_LIMIT', no_october_3_control: true,
    requirement: 'No numerical DRR scoring before formal reference interpretations and calibration data are locked.', interpretation: 'No October 3 control was located; the handoff governs.', status: 'ALIGNED',
    repository_status: 'Candidate results carry no score; the readiness DRR function only refuses. The public training page uses a reviewer-assigned one-to-five rating, outside the Engine (public audit PPA-06).',
    evidence: [E('lib/engine-candidate/contract.js', 'There is no numerical score, no DRR score and no overall verdict of any kind.', 'SOURCE_CODE'), E('tools/evaluation-readiness/lib/workspace.js', 'drr_score_before_freeze', 'SOURCE_CODE')], limitation: 'Applies to the Engine and evaluation tooling.' },
  { id: 'RAC-05', topic: 'codebook_correspondence', source_id: 'D3', lines: [7, 9], tier: 'REPOSITORY_SOURCE', control_type: 'METHODOLOGY_AUTHORITY',
    requirement: 'The Codebook is the methodological authority; one candidate key is insufficiently established; no Engine-to-Codebook correspondence without a versioned, owner-approved record.', interpretation: 'Owner decisions D-2 and D-3, with handoff line 39.', status: 'ALIGNED',
    repository_status: 'No correspondence record exists; all 69 correspondence register entries are unapproved; candidate keys are refused as conditions.',
    evidence: [E('lib/engine-candidate/explanations.js', 'export const CODEBOOK_CORRESPONDENCE_RECORD = null;', 'SOURCE_CODE'), E('tools/methodology-integrity/current-correspondence-register.json', '"approved": false', 'REPOSITORY_RECORD')], limitation: 'No mapping is created or implied.' },
  { id: 'RAC-06', topic: 'public_controlled_boundary', source_id: 'H05', lines: [16, 16], tier: 'REPOSITORY_SOURCE', control_type: 'BOUNDARY',
    requirement: 'Public review routes refuse submissions; no public route accepts record text or returns an evaluation or Manifest.', interpretation: 'The handoff governs.', status: 'ALIGNED',
    repository_status: 'The review routes refuse every request with 503 and make no outbound call.', evidence: [E('api/_controlled-review.js', '503', 'SOURCE_CODE')], limitation: 'Repository code; production identity is verified separately.' },
  { id: 'RAC-07', topic: 'release_gates', source_id: 'H05', lines: [45, 51], tier: 'REPOSITORY_SOURCE', control_type: 'RELEASE_GATE',
    requirement: 'External controlled use is not verified and no gate is marked complete; five gates.', interpretation: 'The handoff gate list.', status: 'ALIGNED',
    repository_status: 'All five gates open; no authorization created.', evidence: [E(RGR, 'INCOMPLETE_GATES_OPEN', 'REPOSITORY_RECORD')], limitation: 'See CF-SA-05 for the difference from the October 3 gate list.' },
  { id: 'RAC-08', topic: 'engine_status', source_id: 'H05', lines: [14, 14], tier: 'REPOSITORY_SOURCE', control_type: 'STATUS',
    requirement: 'The Review Engine is a controlled local-development candidate, not a public service, production system, API, sandbox, integration, licensing offer or acquisition pathway.', interpretation: 'The handoff governs.', status: 'ALIGNED',
    repository_status: 'Public pages on this branch state this.', evidence: [E('review-engine.html', 'It is not a public record-processing service, production system, or autonomous decision-maker.', 'PUBLIC_PAGE')], limitation: 'Wording only.' },
];

// Conflicts. None is resolved by this package; each needs the named decision.
export const CONFLICTS = [
  { id: 'CF-SA-01', controls: ['SAC-05'], source: 'S01 line 13; S02 line 104', repository_location: 'lib/release-gate/records/RG-RECORD_engine-0.5.0-local.1.json $.evidence[*].evidence_id (E-001 to E-009); docs/architecture/CURRENT_RELEASE_GATE_REPORT.md, evidence register',
    finding: 'The release-gate record assigns E-001 to E-009 to its own evidence items, reusing canonical evidence-ledger identifiers that mean other things.', classification: 'NEEDS_RECONCILIATION', decision_owner: 'owner', resolution: null },
  { id: 'CF-SA-02', controls: ['SAC-16', 'SAC-22'], source: 'S01 lines 70 and 74 (with line 21 for production)', repository_location: 'tools/evaluation-readiness/authority-matrix.json roles.independent_reviewer, roles.adjudicator; tools/evaluation-readiness/readiness-contract.json ATT-04; docs/architecture/CODEBOOK_MAPPING_AND_INTERPRETATION_SEPARATION_PROTOCOL.md',
    finding: 'The source makes the owner the only required human evaluation reviewer and the decider of disputes for the evaluation package, and requires independent labeling only for production. The readiness package models future evaluation review by independent reviewers and a separate adjudicator, with no creator-review path.', classification: 'NEEDS_RECONCILIATION', decision_owner: 'owner', resolution: null },
  { id: 'CF-SA-03', controls: ['SAC-15'], source: 'S01 lines 37 to 39 and 45 to 46; S03 line 96', repository_location: 'docs/architecture/CURRENT_ENGINE_HANDOFF_2026-10-05.md lines 10, 36 and 40; public pages on this branch (for example index.html)',
    finding: 'The October 3 sources state commercial-preparation objectives; the later 5 October handoff prohibits licensing and acquisition work without a new owner instruction. The governing order puts the October 3 sources first and the handoff last, "where consistent", and the two are not consistent on this point.', classification: 'NEEDS_RECONCILIATION', decision_owner: 'owner', resolution: null },
  { id: 'CF-SA-04', controls: ['SAC-38'], source: 'S03 line 110', repository_location: 'lib/release-gate/records/RG-RECORD_engine-0.5.0-local.1.json $.gates[RG-1, RG-2, RG-4, RG-5].status and sub-control statuses; no threshold field',
    finding: 'The source vocabulary is pass, fail or not assessed, with missing professional-authority evidence recorded as not assessed; the record uses BLOCKED for four gates and records no numeric thresholds.', classification: 'NEEDS_RECONCILIATION', decision_owner: 'owner', resolution: null },
  { id: 'CF-SA-05', controls: ['SAC-11'], source: 'S01 line 21', repository_location: 'docs/architecture/CURRENT_ENGINE_HANDOFF_2026-10-05.md lines 47 to 51; lib/release-gate/vocabulary.js GATES',
    finding: 'The October 3 gate statement lists independent holdout labeling, operator evidence, counsel disposition, creator review of the development package and independent production QA. The handoff and the release-gate record list owner release authorization as a gate and omit creator review.', classification: 'NEEDS_RECONCILIATION', decision_owner: 'owner', resolution: null },
  { id: 'CF-SA-06', controls: ['SAC-29', 'SAC-41'], source: 'S01 line 102; S03 lines 196 to 206 (historical)', repository_location: '.vercelignore (comment "PUBLICIZE THE STANDARD, PROTECT THE IMPLEMENTATION"); repository visibility public',
    finding: 'Implementation, test corpora and evaluation tooling are excluded from the website but public on GitHub; the source requires an exposure review before any promise of secrecy or exclusivity.', classification: 'NEEDS_RECONCILIATION', decision_owner: 'owner_and_counsel', resolution: null },
];
