// JRS source alignment: package reconciliation and public-position audit data. INTERNAL.
// Every classification here is checked by lib/verify.js against the control matrix: a package or
// audit item that names a control must name one that exists, and a public claim marked
// source-aligned must cite at least one control.

export const PACKAGES = [
  { package: 'lib/engine-candidate/', controls: ['SAC-01', 'SAC-03', 'SAC-04', 'SAC-07', 'SAC-17', 'SAC-33', 'SAC-35', 'SAC-36', 'SAC-44', 'RAC-01', 'RAC-02', 'RAC-03', 'RAC-04', 'RAC-05'],
    aligned: 'Scope gate and excluded domains; versioned review identity over versions, prompt, model and source; quotation location-not-support notice; deterministic extraction, omission, truncation and unsupported-content reporting kept apart from model findings; inference screen; no score; mock-only adapter with fail-closed output validation.',
    gap: 'No execution identity (no live run); live-adapter harness controls (timeouts, redirect refusal, retry budgets) do not exist because no live adapter exists; no disclosure-attempt adversarial set; no holdout builder to enforce separation.',
    classification: 'PARTIALLY_ALIGNED', next_action: 'None now. Any future live adapter must implement SAC-33 before use, under an owner authorization.' },
  { package: 'lib/release-gate/', controls: ['SAC-05', 'SAC-08', 'SAC-09', 'SAC-10', 'SAC-11', 'SAC-12', 'SAC-13', 'SAC-27', 'SAC-38', 'SAC-39', 'RAC-07'],
    aligned: 'Five gates, all open; no authorization; constructed, mocked, local and source-reported evidence can never pass a gate; owner-decision fields empty; gate criteria match the October 3 production requirements for holdout labeling, operator evidence, counsel and independent QA.',
    gap: 'CF-SA-01 (evidence identifiers reuse the canonical namespace), CF-SA-04 (BLOCKED where the source vocabulary is pass, fail or not assessed; no numeric thresholds), CF-SA-05 (creator review absent, owner authorization present). The record limitation that the October 3 comparison is pending is superseded by the source-alignment addendum, not edited.',
    classification: 'CONFLICT', next_action: 'Owner decides the evidence-identifier namespace, the status vocabulary and the gate set. The record is not changed by this package.' },
  { package: 'tools/evaluation-readiness/', controls: ['SAC-16', 'SAC-17', 'SAC-18', 'SAC-19', 'SAC-20', 'SAC-21', 'SAC-22', 'SAC-34', 'SAC-35', 'SAC-37'],
    aligned: 'Blind interpretation; no invented labels; code cannot author or adjudicate a human judgment; intake closed with authority, rights and custody attestations; development and frozen-demo material refused by digest.',
    gap: 'CF-SA-02 (the source names the owner as the only required evaluation reviewer and the decider of disputes; the package models independent reviewers and a separate adjudicator). Ordering, correction and re-label records, an error mapping and a frozen metric specification are not implemented.',
    classification: 'CONFLICT', next_action: 'Owner decides the reviewer model for the evaluation package. The readiness authority matrix would then be revised as a new version, not edited in place.' },
  { package: 'tools/methodology-integrity/', controls: ['RAC-05', 'SAC-18'],
    aligned: 'The Codebook is the methodological authority; all correspondence records are unapproved; candidate keys are never mapped to conditions; Codebook v1.0 is hash-bound.',
    gap: 'None against the sources. The Codebook is not frozen for evaluation (an owner act, SAC-18).',
    classification: 'ALIGNED', next_action: 'None.' },
  { package: 'tools/claim-provenance/', controls: ['SAC-02', 'SAC-23', 'SAC-43', 'SAC-45', 'SAC-46'],
    aligned: 'Detection, agreement and reliability are kept apart and bound to their evidence; the public scan reports no unsupported claim.',
    gap: 'The scanner does not treat "operational validation" or "validation phase" as a status claim (public audit PPA-03).',
    classification: 'PARTIALLY_ALIGNED', next_action: 'Owner decides the wording in PPA-03; a scanner rule would follow in a later package if the wording changes.' },
  { package: 'tools/frozen-demo/', controls: ['SAC-14', 'SAC-37', 'SAC-39', 'SAC-40'],
    aligned: 'Frozen synthetic cases, named version, capability matrix, visible limitations, synthetic labelling, status not released.',
    gap: 'Run evidence is mock replay only; no dated owner release decision; the manifest source_commit label names the branch base, not the commit whose module bytes it binds (recorded in the readiness baseline as CF-06).',
    classification: 'PARTIALLY_ALIGNED', next_action: 'None unless a demonstration is to be given, which needs a dated owner release decision.' },
  { package: 'tools/local-reviewer-workspace/', controls: ['SAC-04', 'SAC-17', 'SAC-21'],
    aligned: 'Human dispositions only, bound to one packet; quotation notice; no Codebook mapping.',
    gap: 'Does not capture creator-review metadata such as ordering or blinding declarations (SAC-20).',
    classification: 'PARTIALLY_ALIGNED', next_action: 'None now.' },
  { package: 'Public-claim repairs and public pages (this branch)', controls: ['SAC-02', 'SAC-23', 'SAC-31', 'SAC-43', 'RAC-06', 'RAC-08'],
    aligned: 'Engine status, scope, research limits, study claims, API, sandbox, licence and Manifest language are repaired on the branch.',
    gap: 'Still present for owner or counsel review: PPA-03 (operational validation phrasing), PPA-06 (training rating), PPA-08 (HR positioning of the methodology), PPA-09 (retention disclosure).',
    classification: 'PARTIALLY_ALIGNED', next_action: 'Owner, with counsel for PPA-09, decides; nothing is published without a separate owner approval.' },
  { package: 'Trackers, handoff and repository ledger', controls: ['SAC-06', 'SAC-15', 'RAC-07'],
    aligned: 'The handoff gate list and Engine status agree with the sources on scope, production status and the open gates.',
    gap: 'CF-SA-03 (commercial preparation in the October 3 sources against the handoff prohibition); the repository Evidence Ledger ends at E-039 against the canonical E-045 (SAC-06).',
    classification: 'CONFLICT', next_action: 'Owner decides which instruction governs commercial preparation and whether the repository ledger is updated.' },
  { package: 'Repository boundary (.vercelignore and GitHub visibility)', controls: ['SAC-29', 'SAC-41', 'SAC-42'],
    aligned: 'The website excludes the implementation, tests, research and internal documents.',
    gap: 'CF-SA-06: the GitHub repository is public, so the excluded material is readable there; the source requires an exposure review before any promise of secrecy or exclusivity.',
    classification: 'CONFLICT', next_action: 'Owner and counsel exposure review. Visibility is the owner\'s setting and is not changed here.' },
];

// Public-position audit. Dispositions: ALREADY_CORRECTED, STILL_PRESENT, HISTORICAL_ONLY,
// NOT_ASSESSABLE_FROM_SOURCE_SET, REQUIRES_OWNER_OR_COUNSEL_REVIEW. `present` is page text that must
// still be on the page (public text, already published); `source_aligned` requires a cited control.
export const PUBLIC_AUDIT = [
  { id: 'PPA-01', category: 'Engine status and scope', disposition: 'ALREADY_CORRECTED', controls: ['RAC-08', 'SAC-02', 'SAC-01'], source_aligned: true,
    finding: 'The Engine is described as a controlled local-development candidate, not a public service, API, sandbox, integration, licence or acquisition pathway.', corrected_by: '3758d76',
    present: [['review-engine.html', 'It is not a public record-processing service, production system, or autonomous decision-maker.'], ['index.html', 'No public caller can obtain an evaluation or a development Manifest.']] },
  { id: 'PPA-02', category: 'Research limitations', disposition: 'ALREADY_CORRECTED', controls: ['SAC-23', 'SAC-45', 'SAC-46'], source_aligned: true,
    finding: 'Research pages state the constructed corpus, the separate reliability sample, the failed criterion and that no result is real-world validation.', corrected_by: '7bfb13e',
    present: [['research.html', 'Nothing above is presented as real-world validation.']] },
  { id: 'PPA-03', category: '"validation" and "operational" phrasing', disposition: 'STILL_PRESENT', review: 'REQUIRES_OWNER_OR_COUNSEL_REVIEW', controls: ['SAC-43', 'SAC-02'], source_aligned: false,
    finding: 'Several served pages describe the programme as being in "operational validation" or a "validation phase". Each disclaims validated effectiveness, but the phrase names an operational-validity activity no recorded study performs (studies are closed), and the sources treat operational validity as an unmeasured property. Exceeds the source-aligned evidence; not reopened as a wording repair here.',
    present: [['about.html', 'It is currently an operational validation and evidence-development program.'], ['check.html', 'JRS remains in operational validation.'], ['reference/index.html', 'JRS is in operational validation and makes no claim of validated effectiveness.']] },
  { id: 'PPA-04', category: 'Study claims', disposition: 'ALREADY_CORRECTED', controls: ['SAC-46'], source_aligned: true,
    finding: 'Detection, reliability and cross-vendor figures carry their populations, denominators, windows and limits; the claim-provenance public scan reports 0 unsupported, 0 requiring repair and 0 ambiguous.', corrected_by: '7bfb13e',
    present: [['research.html', 'This is agreement between models, not accuracy.']] },
  { id: 'PPA-05', category: 'API, sandbox, licence, acquisition, commercial and integration language', disposition: 'ALREADY_CORRECTED', controls: ['RAC-08', 'RAC-06'], source_aligned: true,
    finding: 'Current pages state that no API, sandbox, record intake, evaluation access, licence or acquisition pathway is offered.', corrected_by: '3758d76',
    present: [['enterprise.html', 'It does not provide a sandbox, token-gated API, record intake, technical evaluation access, licensing offer, or acquisition pathway.']] },
  { id: 'PPA-06', category: 'Numerical rating on the training page', disposition: 'NOT_ASSESSABLE_FROM_SOURCE_SET', review: 'REQUIRES_OWNER_OR_COUNSEL_REVIEW', controls: ['RAC-04'], source_aligned: false,
    finding: 'The training page has reviewers assign a one-to-five "Decision Defensibility Score". The October 3 sources do not address human training ratings; the handoff limits numerical DRR scoring by the Engine and evaluation tooling. Whether a human training rating is consistent with that limit is an owner decision.',
    present: [['training.html', 'The Decision Defensibility Score']] },
  { id: 'PPA-07', category: 'Manifest claims', disposition: 'ALREADY_CORRECTED', controls: ['RAC-06', 'SAC-04'], source_aligned: true,
    finding: 'The Manifest page describes a public specification, no public Manifest output, and an unsigned hash that does not prove authorship. The October 3 sources observed (2 October, production) pages describing authenticated development Manifest output; this branch narrowed that under the handoff.', corrected_by: '3758d76',
    present: [['manifest.html', 'An unsigned Manifest can be checked for internal consistency, but it does not prove who created it.']] },
  { id: 'PPA-08', category: 'Scope of the public methodology', disposition: 'NOT_ASSESSABLE_FROM_SOURCE_SET', review: 'REQUIRES_OWNER_OR_COUNSEL_REVIEW', controls: ['SAC-31', 'SAC-01'], source_aligned: false,
    finding: 'The Standard page lists review environments including HR and employment documentation. The sources limit use of the diagnostic to non-HR records; whether that limit governs the public methodology, or only the Engine and evaluation, is not stated.',
    present: [['jrsstandard.html', 'HR review and employment documentation audit']] },
  { id: 'PPA-09', category: 'Data handling and privacy', disposition: 'STILL_PRESENT', review: 'REQUIRES_OWNER_OR_COUNSEL_REVIEW', controls: ['SAC-10'], source_aligned: false,
    finding: 'On this branch the security and privacy pages no longer state the 90-day field-level expiry that the repository retention policy sets (introduced by 3758d76; guard check "disclosed retention matches the policy"). The sources record that published policy is not evidence of execution; the disclosure itself is a counsel matter (RG-3).',
    present: [['privacy.html', 'api.jrsstandard.com']] },
  { id: 'PPA-10', category: 'Closed service pages', disposition: 'HISTORICAL_ONLY', controls: ['RAC-08'], source_aligned: true,
    finding: 'Calibration, audit and engagement pages and the terms page are marked closed or retained only for engagements agreed before 4 September 2026.',
    present: [['calibration-request.html', 'Closed to new requests'], ['terms.html', 'These govern paid record-defensibility engagements.']] },
];

// Categories examined in which no issue was found. They are not audit issues and carry no disposition.
export const NO_ISSUE = [
  { category: '"defensible" phrasing', basis: 'Used as a documentation property; pages disclaim legal defensibility.', evidence: ['jrsstandard.html', 'It does not evaluate whether the underlying decision was correct, legally defensible, or consistent with policy.'] },
  { category: '"compliance" phrasing', basis: 'No page asserts that JRS or the Engine is compliant; certification is disclaimed.', evidence: ['methodology.html', 'Nothing here constitutes validated findings, certification, accreditation, or legal advice.'] },
  { category: '"accuracy" and "reliability" phrasing', basis: 'Bound by the claim register; the public scan reports no unsupported statement.', evidence: ['research.html', 'This is agreement between models, not accuracy.'] },
];
